Object.assign(languages,{en:'English',it:'Italiano',es:'Español'});
const extraRules=[
['ankommen','The conjugated verb is in position two in a statement. A question with a question word starts with that word.','Il verbo coniugato occupa la seconda posizione nella frase dichiarativa. Le domande con una parola interrogativa iniziano con essa.','El verbo conjugado ocupa la segunda posición en una oración enunciativa. Las preguntas con palabra interrogativa empiezan con esa palabra.'],
['einkaufen','Learn nouns with their articles. In the accusative, masculine der becomes den and ein becomes einen.','Impara i nomi con il loro articolo. All’accusativo maschile der diventa den ed ein diventa einen.','Aprende los sustantivos con su artículo. En acusativo masculino, der pasa a den y ein a einen.'],
['termine','Use am with weekdays and um with times. Halb zehn means 9:30. In yes/no questions the verb comes first.','Usa am con i giorni della settimana e um con le ore. Halb zehn significa 9:30. Nelle domande sì/no il verbo viene prima.','Usa am con los días y um con las horas. Halb zehn significa las 9:30. En las preguntas de sí o no, el verbo va primero.'],
['wohnen','Kein negates nouns with an indefinite article or no article. Nicht negates an adjective, for example nicht groß.','Kein nega nomi con articolo indeterminativo o senza articolo. Nicht nega un aggettivo, per esempio nicht groß.','Kein niega sustantivos con artículo indefinido o sin artículo. Nicht niega un adjetivo, por ejemplo nicht groß.'],
['alltag','The perfect tense uses haben or sein plus a past participle. The auxiliary comes second and the participle goes at the end.','Il Perfekt usa haben o sein più il participio passato. L’ausiliare è in seconda posizione e il participio alla fine.','El Perfekt se forma con haben o sein y un participio. El auxiliar va en segunda posición y el participio al final.'],
['gesundheit','Modal verbs come second and the infinitive goes at the end. Sollen often reports advice; müssen expresses necessity.','Il verbo modale è in seconda posizione e l’infinito alla fine. Sollen spesso riporta un consiglio; müssen esprime necessità.','El verbo modal va en segunda posición y el infinitivo al final. Sollen suele transmitir un consejo; müssen expresa necesidad.'],
['unterwegs','With two-way prepositions, location (Wo?) takes the dative, destination (Wohin?) takes the accusative. Movement alone is not enough.','Con le preposizioni a doppio caso, lo stato in luogo (Wo?) richiede il dativo; la destinazione (Wohin?) l’accusativo. Il semplice movimento non basta.','Con las preposiciones de doble caso, la ubicación (Wo?) lleva dativo y el destino (Wohin?) acusativo. No basta con que haya movimiento.'],
['schule','After weil, the conjugated verb goes at the end of the subordinate clause. Könnten Sie mir bitte …? is a polite request.','Dopo weil il verbo coniugato va alla fine della subordinata. Könnten Sie mir bitte …? è una richiesta cortese.','Después de weil el verbo conjugado va al final de la subordinada. Könnten Sie mir bitte …? es una petición cortés.'],
['reklamation','A relative clause describes a noun. The pronoun’s gender and number match that noun; its case depends on its role in the relative clause.','La relativa descrive un nome. Genere e numero del pronome dipendono dal nome; il caso dipende dalla funzione nella relativa.','La oración de relativo describe un sustantivo. El género y número del pronombre coinciden con él; el caso depende de su función en la subordinada.'],
['meinung','Obwohl introduces a subordinate clause with the verb at the end. If trotzdem begins a main clause, the verb follows directly.','Obwohl introduce una subordinata con il verbo alla fine. Se trotzdem apre una principale, il verbo segue subito.','Obwohl introduce una subordinada con el verbo al final. Si trotzdem inicia una oración principal, el verbo va justo después.'],
['arbeit','Use um … zu for a purpose when the person acting is the same in both parts. With different people, damit is often suitable.','Usa um … zu per lo scopo quando il soggetto delle due parti è lo stesso. Con soggetti diversi si usa spesso damit.','Usa um … zu para expresar finalidad si el sujeto es el mismo. Con sujetos diferentes suele usarse damit.'],
['planen','Make polite suggestions with Wir könnten … or Wie wäre es mit …? Respond to your partner before making a new suggestion.','Proponi con cortesia: Wir könnten … o Wie wäre es mit …? Rispondi al tuo interlocutore prima di fare una nuova proposta.','Haz propuestas corteses con Wir könnten … o Wie wäre es mit …? Responde a tu interlocutor antes de proponer algo nuevo.'],
['bewerbung-b2','Learn fixed combinations such as Verantwortung übernehmen, to take responsibility. Support each strength with a specific example.','Impara espressioni fisse come Verantwortung übernehmen, assumersi responsabilità. Sostieni ogni punto di forza con un esempio concreto.','Aprende expresiones fijas como Verantwortung übernehmen, asumir responsabilidad. Apoya cada fortaleza con un ejemplo concreto.'],
['beschwerde-b2','A complaint response includes acknowledgement, understanding, explanation and a concrete solution. Promise only confirmed actions. Passive: werden plus participle.','La risposta a un reclamo comprende riferimento al problema, comprensione, spiegazione e soluzione concreta. Prometti solo azioni confermate. Passivo: werden più participio.','La respuesta a una queja incluye referencia al problema, comprensión, explicación y solución concreta. Promete solo lo confirmado. Pasiva: werden más participio.'],
['forum-b2','Organise your argument: topic, position, reasons with examples, opposing view and proposal. Einerseits … andererseits means on the one hand … on the other hand.','Organizza l’argomentazione: tema, posizione, motivi con esempi, punto di vista opposto e proposta. Einerseits … andererseits significa da un lato … dall’altro.','Organiza la argumentación: tema, postura, razones con ejemplos, opinión contraria y propuesta. Einerseits … andererseits significa por un lado … por otro.'],
['loesungen-b2','Separate immediate action from long-term solutions. Falls introduces a condition and sends the verb to the end. Agree who does what by when.','Distingui le misure immediate dalle soluzioni a lungo termine. Falls introduce una condizione e manda il verbo alla fine. Concordate chi fa cosa ed entro quando.','Distingue las medidas inmediatas de las soluciones a largo plazo. Falls introduce una condición y manda el verbo al final. Acordad quién hace qué y para cuándo.'],
['kleidung','After a definite article, adjectives take -e in the nominative singular and -en in the plural. Masculine accusative: einen roten Pullover. Mit takes the dative.','Dopo l’articolo determinativo, l’aggettivo prende -e al nominativo singolare e -en al plurale. Accusativo maschile: einen roten Pullover. Mit regge il dativo.','Después del artículo definido, el adjetivo lleva -e en nominativo singular y -en en plural. Acusativo masculino: einen roten Pullover. Mit exige dativo.']];
extraRules.forEach(([id,en,it,es])=>Object.assign(ruleHelp[id],{en,it,es}));
Object.assign(guides,{en:'Read the explanation and example, then do the exercises.',it:'Leggi la spiegazione e l’esempio, poi svolgi gli esercizi.',es:'Lee la explicación y el ejemplo y después haz los ejercicios.'});
const spokenExamples={};
function A(id,ru,uk,ar,fa,tr,ro,zh,en,it,es){spokenExamples[id]={de:lessons.find(l=>l.id===id).example,ru,uk,ar,fa,tr,ro,zh,en,it,es};}
A('ankommen','Я из Сирии. Где Вы живёте?','Я із Сирії. Де Ви мешкаєте?','أنا من سوريا. أين تسكن؟','من اهل سوریه هستم. شما کجا زندگی می‌کنید؟','Ben Suriyeliyim. Nerede oturuyorsunuz?','Sunt din Siria. Unde locuiți?','我来自叙利亚。您住在哪里？','I come from Syria. Where do you live?','Vengo dalla Siria. Dove abita?','Soy de Siria. ¿Dónde vive usted?');
A('einkaufen','Я покупаю яблоко, банан и буханку хлеба.','Я купую яблуко, банан і хлібину.','أشتري تفاحة وموزة ورغيف خبز.','من یک سیب، یک موز و یک نان می‌خرم.','Bir elma, bir muz ve bir ekmek alıyorum.','Cumpăr un măr, o banană și o pâine.','我买一个苹果、一根香蕉和一个面包。','I am buying an apple, a banana and a loaf of bread.','Compro una mela, una banana e un pane.','Compro una manzana, un plátano y un pan.');
A('termine','У Вас есть время во вторник в десять часов?','Чи маєте Ви час у вівторок о десятій годині?','هل لديك وقت يوم الثلاثاء في الساعة العاشرة؟','آیا سه‌شنبه ساعت ده وقت دارید؟','Salı günü saat onda vaktiniz var mı?','Aveți timp marți la ora zece?','您星期二十点有时间吗？','Do you have time on Tuesday at ten?','Ha tempo martedì alle dieci?','¿Tiene tiempo el martes a las diez?');
A('wohnen','В квартире нет балкона. Кухня не маленькая.','У квартирі немає балкона. Кухня не маленька.','الشقة ليس فيها شرفة. المطبخ ليس صغيراً.','آپارتمان بالکن ندارد. آشپزخانه کوچک نیست.','Dairenin balkonu yok. Mutfak küçük değil.','Apartamentul nu are balcon. Bucătăria nu este mică.','公寓没有阳台。厨房不小。','The apartment has no balcony. The kitchen is not small.','L’appartamento non ha un balcone. La cucina non è piccola.','El piso no tiene balcón. La cocina no es pequeña.');
A('alltag','Я готовил еду. После этого я поехал домой.','Я готував їжу. Після цього я поїхав додому.','طبخت الطعام. بعد ذلك ذهبت إلى المنزل.','من آشپزی کردم. بعد از آن به خانه رفتم.','Yemek yaptım. Sonra eve gittim.','Am gătit. După aceea am mers acasă.','我做了饭。然后我回家了。','I cooked. Afterwards I went home.','Ho cucinato. Poi sono andato a casa.','He cocinado. Después he ido a casa.');
A('gesundheit','Вам следует много пить. Я должен отменить приём.','Вам слід багато пити. Я мушу скасувати прийом.','ينبغي أن تشرب كثيراً. يجب أن ألغي الموعد.','شما باید مایعات زیادی بنوشید. من باید وقت ملاقات را لغو کنم.','Bol sıvı içmelisiniz. Randevuyu iptal etmem gerekiyor.','Ar trebui să beți multe lichide. Trebuie să anulez programarea.','您应该多喝水。我必须取消预约。','You should drink plenty of fluids. I must cancel the appointment.','Dovrebbe bere molto. Devo annullare l’appuntamento.','Debe beber muchos líquidos. Tengo que cancelar la cita.');
A('unterwegs','Я жду на остановке. Я иду к остановке.','Я чекаю на зупинці. Я йду до зупинки.','أنتظر عند الموقف. أذهب إلى الموقف.','من در ایستگاه منتظر هستم. من به ایستگاه می‌روم.','Durakta bekliyorum. Durağa gidiyorum.','Aștept în stație. Merg la stație.','我在车站等。我走向车站。','I am waiting at the stop. I am going to the stop.','Aspetto alla fermata. Vado alla fermata.','Espero en la parada. Voy a la parada.');
A('schule','Мой ребёнок отсутствует, потому что болен. Не могли бы Вы прислать мне задания?','Моя дитина відсутня, бо хворіє. Чи могли б Ви надіслати мені завдання?','طفلي غائب لأنه مريض. هل يمكنك إرسال الواجبات إليّ؟','فرزندم غایب است چون بیمار است. آیا می‌توانید تکالیف را برایم بفرستید؟','Çocuğum hasta olduğu için gelmiyor. Ödevleri bana gönderebilir misiniz?','Copilul meu lipsește pentru că este bolnav. Ați putea să-mi trimiteți temele?','我的孩子因为生病而缺课。您能把作业发给我吗？','My child is absent because they are ill. Could you send me the assignments?','Mio figlio è assente perché è malato. Potrebbe inviarmi i compiti?','Mi hijo falta porque está enfermo. ¿Podría enviarme las tareas?');
A('reklamation','Принтер, который я купил, не работает.','Принтер, який я купив, не працює.','الطابعة التي اشتريتها لا تعمل.','چاپگری که خریده‌ام کار نمی‌کند.','Satın aldığım yazıcı çalışmıyor.','Imprimanta pe care am cumpărat-o nu funcționează.','我买的打印机坏了。','The printer I bought does not work.','La stampante che ho comprato non funziona.','La impresora que compré no funciona.');
A('meinung','Хотя у меня мало времени, я учу немецкий. У меня мало времени. Тем не менее я учу немецкий.','Хоча я маю мало часу, я вивчаю німецьку. Я маю мало часу. Попри це я вивчаю німецьку.','رغم أن وقتي قليل، أتعلم الألمانية. وقتي قليل. مع ذلك أتعلم الألمانية.','اگرچه وقت کمی دارم، آلمانی یاد می‌گیرم. وقت کمی دارم. با این حال آلمانی یاد می‌گیرم.','Az zamanım olmasına rağmen Almanca öğreniyorum. Az zamanım var. Yine de Almanca öğreniyorum.','Deși am puțin timp, învăț germană. Am puțin timp. Totuși învăț germană.','虽然时间不多，我还是学德语。我的时间不多。尽管如此，我还是学德语。','Although I have little time, I learn German. I have little time. Nevertheless I learn German.','Anche se ho poco tempo, studio tedesco. Ho poco tempo. Tuttavia studio tedesco.','Aunque tengo poco tiempo, aprendo alemán. Tengo poco tiempo. Aun así aprendo alemán.');
A('arbeit','Я посещаю курс, чтобы улучшить свой немецкий.','Я відвідую курс, щоб покращити свою німецьку.','أحضر دورة لتحسين لغتي الألمانية.','من در یک دوره شرکت می‌کنم تا زبان آلمانی‌ام را بهتر کنم.','Almancamı geliştirmek için bir kursa katılıyorum.','Urmez un curs pentru a-mi îmbunătăți germana.','我参加课程来提高德语水平。','I attend a course to improve my German.','Frequento un corso per migliorare il mio tedesco.','Asisto a un curso para mejorar mi alemán.');
A('planen','Это хорошая идея. К сожалению, суббота мне не подходит. Как насчёт воскресенья?','Це гарна ідея. На жаль, субота мені не підходить. Як щодо неділі?','هذه فكرة جيدة. للأسف يوم السبت لا يناسبني. ما رأيك بيوم الأحد؟','این ایده خوبی است. متأسفانه شنبه برایم مناسب نیست. یکشنبه چطور است؟','Bu iyi bir fikir. Ne yazık ki cumartesi bana uymuyor. Pazar nasıl olur?','Este o idee bună. Din păcate, sâmbătă nu pot. Ce zici de duminică?','这是个好主意。可惜我星期六不方便。星期天怎么样？','That is a good idea. Unfortunately Saturday does not suit me. How about Sunday?','È una buona idea. Purtroppo sabato non posso. Che ne dici di domenica?','Es una buena idea. Lamentablemente el sábado no me viene bien. ¿Qué tal el domingo?');
A('bewerbung-b2','Я взял на себя обучение новых сотрудников.','Я взяв на себе навчання нових працівників.','توليت تدريب الموظفين الجدد.','من مسئولیت آموزش کارکنان جدید را بر عهده گرفتم.','Yeni çalışanların işe alıştırılmasını üstlendim.','M-am ocupat de instruirea noilor angajați.','我负责了新员工的入职培训。','I took responsibility for training new employees.','Mi sono occupato della formazione dei nuovi dipendenti.','Me encargué de la formación de los nuevos empleados.');
A('beschwerde-b2','Мы сожалеем о задержке. Недостающие детали будут отправлены завтра.','Ми шкодуємо про затримку. Відсутні деталі будуть відправлені завтра.','نأسف للتأخير. سيتم إرسال القطع الناقصة غداً.','از تأخیر متأسفیم. قطعات باقی‌مانده فردا ارسال خواهند شد.','Gecikmeden dolayı üzgünüz. Eksik parçalar yarın gönderilecek.','Regretăm întârzierea. Piesele lipsă vor fi trimise mâine.','我们对延误表示歉意。缺少的零件将于明天寄出。','We regret the delay. The missing parts will be sent tomorrow.','Ci scusiamo per il ritardo. I pezzi mancanti saranno spediti domani.','Lamentamos el retraso. Las piezas que faltan se enviarán mañana.');
A('forum-b2','С одной стороны, это экономит время, с другой стороны, не хватает личного общения.','З одного боку, це заощаджує час, з іншого боку, бракує особистого спілкування.','من جهة يوفر ذلك الوقت، ومن جهة أخرى ينقص التواصل الشخصي.','از یک سو این کار در زمان صرفه‌جویی می‌کند، از سوی دیگر ارتباط حضوری کم می‌شود.','Bir yandan bu zaman kazandırır, diğer yandan yüz yüze iletişim eksik kalır.','Pe de o parte se economisește timp, pe de altă parte lipsește contactul personal.','一方面这节省了时间，另一方面缺少面对面的交流。','On the one hand it saves time; on the other hand personal contact is missing.','Da un lato si risparmia tempo, dall’altro manca il contatto personale.','Por un lado se ahorra tiempo; por otro falta el contacto personal.');
A('loesungen-b2','Если поставка не состоится, мы могли бы обратиться к другому поставщику.','Якщо постачання не відбудеться, ми могли б звернутися до іншого постачальника.','إذا تعذر التسليم، يمكننا الاستفسار لدى مورد آخر.','اگر تحویل انجام نشود، می‌توانیم از تأمین‌کننده دیگری درخواست کنیم.','Teslimat gerçekleşmezse başka bir tedarikçiye sorabiliriz.','Dacă livrarea nu are loc, am putea contacta alt furnizor.','如果无法交货，我们可以询问另一家供应商。','If the delivery falls through, we could ask another supplier.','Se la consegna non avviene, potremmo contattare un altro fornitore.','Si falla la entrega, podríamos consultar a otro proveedor.');
A('kleidung','Красный свитер. Я ношу красный свитер. Мужчина в красном свитере.','Червоний светр. Я ношу червоний светр. Чоловік у червоному светрі.','الكنزة الحمراء. أرتدي كنزة حمراء. الرجل ذو الكنزة الحمراء.','پلیور قرمز. من یک پلیور قرمز می‌پوشم. مرد با پلیور قرمز.','Kırmızı kazak. Kırmızı bir kazak giyiyorum. Kırmızı kazaklı adam.','Puloverul roșu. Port un pulover roșu. Bărbatul cu puloverul roșu.','红色毛衣。我穿一件红色毛衣。穿红色毛衣的男子。','The red sweater. I am wearing a red sweater. The man with the red sweater.','Il maglione rosso. Indosso un maglione rosso. L’uomo con il maglione rosso.','El jersey rojo. Llevo un jersey rojo. El hombre con el jersey rojo.');
const moreWords=[['der Name','name','nome','nombre'],['wohnen','live','abitare','vivir'],['die Sprache','language','lingua','idioma'],['das Brot','bread','pane','pan'],['kaufen','buy','comprare','comprar'],['der Preis','price','prezzo','precio'],['der Termin','appointment','appuntamento','cita'],['die Uhr','clock','orologio','reloj'],['geöffnet','open','aperto','abierto'],['die Wohnung','apartment','appartamento','piso'],['das Zimmer','room','stanza','habitación'],['der Balkon','balcony','balcone','balcón'],['gestern','yesterday','ieri','ayer'],['arbeiten','work','lavorare','trabajar'],['anrufen','call','telefonare','llamar'],['die Schmerzen','pain','dolori','dolores'],['mitbringen','bring along','portare con sé','traer'],['krank','ill','malato','enfermo'],['die Haltestelle','stop','fermata','parada'],['geradeaus','straight ahead','dritto','todo recto'],['neben','next to','accanto a','al lado de'],['die Schule','school','scuola','escuela'],['der Ausflug','outing','gita','excursión'],['weil','because','perché','porque'],['die Lieferung','delivery','consegna','entrega'],['der Mangel','defect','difetto','defecto'],['ersetzen','replace','sostituire','sustituir'],['die Meinung','opinion','opinione','opinión'],['obwohl','although','sebbene','aunque'],['trotzdem','nevertheless','tuttavia','aun así'],['die Bewerbung','job application','candidatura','solicitud de empleo'],['die Erfahrung','experience','esperienza','experiencia'],['die Stelle','job','posto di lavoro','puesto de trabajo'],['der Vorschlag','suggestion','proposta','propuesta'],['vereinbaren','agree on','concordare','acordar'],['die Aufgabe','task','compito','tarea'],['die Voraussetzung','prerequisite','requisito','requisito'],['zuständig','responsible','responsabile','responsable'],['die Kompetenz','competence','competenza','competencia'],['die Beschwerde','complaint','reclamo','queja'],['die Verzögerung','delay','ritardo','retraso'],['die Abholung','collection','ritiro','recogida'],['die Vereinbarung','agreement','accordo','acuerdo'],['der Vorteil','advantage','vantaggio','ventaja'],['vorschlagen','suggest','proporre','proponer'],['die Maßnahme','measure','misura','medida'],['die Frist','deadline','scadenza','plazo'],['zuverlässig','reliable','affidabile','fiable'],['die Jacke','jacket','giacca','chaqueta'],['der Pullover','sweater','maglione','jersey'],['tragen','wear','indossare','llevar']];
moreWords.forEach(([w,en,it,es])=>Object.assign(dictionary[w],{en,it,es}));
