/* Book presentation reuses the lesson content and exercise engine. */
const originalRoute=route, originalLesson=lesson, originalBindWriting=bindWriting;
const mq=window.matchMedia('(max-width:720px)');
let lastBookPage=0;
const artFor=l=>l.id==='kleidung'?'kleidung':l.level==='B2'?'beruf':'alltag';
const altFor=a=>a==='kleidung'?'Buntstiftzeichnung: Frau mit schwarzer Jacke, blauer Hose und weißen Schuhen; Mann mit rotem Pullover und grauer Hose.':a==='beruf'?'Handgezeichnete Berufsszene: Erwachsene besprechen Aufgaben an einem Tisch, daneben Lieferkartons.':'Handgezeichnete Alltagsszene mit Bäckerei, Bushaltestelle und Menschen im Gespräch.';
function teacherTip(text){return `<div class="teacher-tip"><img src="assets/lehrer.jpg" alt="Dzianis Prudnikau, dein Deutschlehrer"><p><b>Ein Tipp von Dzianis</b>${text}</p></div>`;}
function page(body,num,label){return `<section class="paper">${body}<div class="page-no"><span>DEUTSCH AKTIV · ${label}</span><span>${num}</span></div></section>`;}
function bookFrame(left,right,{title,prev,next,number=0,total=0,animate=true}={}){const m=mq.matches;main.innerHTML=`<div class="book-top"><span class="trail">${title||'Dein Deutsch-Ringbuch'}</span><div class="book-levels">${['A1','A2','B1','B2'].map(k=>`<a href="#buch/${k}" class="${level===k?'active':''}">${k==='B2'?'B2 Beruf':k}</a>`).join('')}<a href="#themen">Inhalt ☰</a></div></div><div class="book-stage"><div class="spread ${animate?'flip-in':''}">${left}${right}<div class="binder-rings" aria-hidden="true">${Array.from({length:6},()=>'<span class="binder-ring"></span>').join('')}</div></div></div><div class="book-controls">${prev?`<a class="btn secondary" data-turn="back" href="${prev}">← Zurück</a>`:'<span></span>'}<p>${number?`Seite ${number}${!m&&right?'–'+(number+1):''} · ${total} Seiten`: 'Dein Ringbuch · A1 bis B2 Beruf'}</p>${next?`<a class="btn" data-turn="next" href="${next}">Weiter →</a>`:'<a class="btn" href="#">Zum Cover</a>'}</div>${number?`<div class="book-progress"><span style="width:${Math.min(100,100*number/total)}%"></span></div>`:''}<p class="book-help">Mit Weiter und Zurück blättern · Themen auch direkt über das Inhaltsverzeichnis öffnen</p>`;bindPageTurns();}
let pageTurnSound=null;
let pageSoundEnabled=true;
let pageMotionEnabled=!matchMedia('(prefers-reduced-motion: reduce)').matches;
try{pageSoundEnabled=sessionStorage.getItem('page-sound')!=='off';const saved=sessionStorage.getItem('page-motion');if(saved!==null)pageMotionEnabled=saved==='on';}catch(e){}
function savePagePreference(key,value){try{sessionStorage.setItem(key,value?'on':'off');}catch(e){}}
function playPageRustle(){
 if(!pageSoundEnabled)return;
 try{if(!pageTurnSound){pageTurnSound=new Audio('audio/page-turn.wav');pageTurnSound.preload='auto';pageTurnSound.volume=.75;}pageTurnSound.currentTime=0;pageTurnSound.play().catch(()=>{});}catch(e){}
}
function bindPageTurns(){
 const help=main.querySelector('.book-help');
 const mute=document.createElement('button');mute.type='button';mute.className='page-sound-toggle';
 const update=()=>{mute.textContent=pageSoundEnabled?'Papiergeräusch: an':'Papiergeräusch: aus';mute.setAttribute('aria-pressed',String(pageSoundEnabled));};
 update();mute.onclick=()=>{pageSoundEnabled=!pageSoundEnabled;savePagePreference('page-sound',pageSoundEnabled);if(!pageSoundEnabled)pageTurnSound?.pause();else playPageRustle();update();};help.append(' ',mute);
 const motion=document.createElement('button');motion.type='button';motion.className='page-sound-toggle';
 const updateMotion=()=>{motion.textContent=pageMotionEnabled?'Umblättern: animiert':'Umblättern: ohne Animation';motion.setAttribute('aria-pressed',String(pageMotionEnabled));};
 updateMotion();motion.onclick=()=>{pageMotionEnabled=!pageMotionEnabled;savePagePreference('page-motion',pageMotionEnabled);updateMotion();};help.append(' ',motion);
 let turning=false;
 main.querySelectorAll('[data-turn]').forEach(a=>a.onclick=e=>{
  if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button!==0)return;
  e.preventDefault();if(turning)return;turning=true;
  playPageRustle();
  const destination=a.getAttribute('href'),spread=main.querySelector('.spread');
  if(!pageMotionEnabled){location.hash=destination;return;}
  const back=a.dataset.turn==='back',papers=spread.querySelectorAll(':scope > .paper');
  const original=papers[back?0:papers.length-1],sheet=original.cloneNode(true);
  sheet.className='paper turning-page'+(back?' turn-back':'');sheet.setAttribute('aria-hidden','true');sheet.inert=true;
  sheet.removeAttribute('id');sheet.querySelectorAll('[id]').forEach(el=>el.removeAttribute('id'));
  sheet.style.width=original.offsetWidth+'px';sheet.style.height=original.offsetHeight+'px';
  // Controls can sit below a long lesson: bring the turning sheet into view first.
  const stage=spread.closest('.book-stage');
  window.scrollTo({top:Math.max(0,window.scrollY+stage.getBoundingClientRect().top-20),behavior:'instant'});
  spread.classList.remove('flip-in');spread.classList.add('is-turning');
  original.classList.add('page-under-turn');spread.append(sheet);
  main.querySelectorAll('[data-turn]').forEach(button=>button.setAttribute('aria-disabled','true'));
  const oldHash=location.hash;let done=false;
  const finish=()=>{if(done)return;done=true;if(spread.isConnected&&location.hash===oldHash)location.hash=destination;};
  sheet.addEventListener('animationend',event=>{if(event.target===sheet&&['realPageTurn','realPageBack'].includes(event.animationName))finish();});setTimeout(finish,1300);
 });
}

function cover(which=0){const welcome=page(`<span class="tape-label">Dein Deutsch-Ringbuch</span><div class="cover-title">Deutsch lernen.<span>Seite für Seite.</span></div><p>Für deinen Alltag. Für deinen Beruf.<br>Von den ersten Worten bis zur Prüfung.</p><div class="teacher-intro"><img src="assets/lehrer.jpg" alt="Lehrerporträt von Dzianis Prudnikau"><div><p>Willkommen! Ich bin Dzianis, dein Deutschlehrer. Lass uns gemeinsam entdecken, verstehen und üben.</p><span class="signature">Dzianis Prudnikau</span></div></div><img class="cover-art" src="assets/alltag.webp" alt="${altFor('alltag')}">`,'','WILLKOMMEN');const contents=page(`<span class="step-label">Hier beginnt dein Lernweg</span><h2>Welches Kapitel<br>schlagen wir auf?</h2>${['A1','A2','B1','B2'].map(k=>`<a class="contents-item" href="#buch/${k}"><b>${k}</b><span><strong>${{A1:'Ankommen & erste Worte',A2:'Mein Alltag, meine Geschichten',B1:'Sicher sprechen & schreiben',B2:'Deutsch im Beruf'}[k]}</strong><small>${lessons.filter(l=>l.level===k).length} Lektionen · Erklären, üben, anwenden</small></span><span>↗</span></a>`).join('')}<a class="contents-item" href="#videos"><b>▶</b><span><strong>Videos</strong><small>Deutsch lernen mit Dennis · Erklärvideos</small></span><span>↗</span></a><a class="contents-item" href="#orientierungskurs"><b>LiD</b><span><strong>Orientierungskurs</strong><small>Deutschland entdecken · Videos, Wissen & Lernspiele</small></span><span>↗</span></a><a class="contents-item" href="#pruefung"><b>✓</b><span><strong>Prüfungstraining</strong><small>DTZ · g.a.s.t. / DTB B2 · telc</small></span><span>↗</span></a>${teacherTip('Du kannst vorne beginnen oder direkt ein Thema wählen, das du gerade brauchst.')}`,'','INHALT');bookFrame(mq.matches&&which===1?contents:welcome,mq.matches?'':contents,{title:'Cover & Inhaltsverzeichnis',prev:which?'#':null,next:mq.matches&&which===0?'#cover/1':'#buch/A1'});}
function levelIndex(k,side=0){level=titles[k]?k:'A1';const ls=lessons.filter(l=>l.level===level),art=level==='B2'?'beruf':'alltag';let a=page(`<span class="tape-label">${level==='B2'?'B2 Beruf':level} · Dein Kapitel</span><h1>${titles[level]}</h1><img class="lesson-art" src="assets/${art}.webp" alt="${altFor(art)}"><p class="sketch-caption">Sehen → verstehen → selbst ausprobieren</p>${teacherTip('Jede Lektion hat sechs Grundseiten und ein Wörteratelier mit 20 Wortkarten, Grammatikseiten und drei Lernspielen. Die Übungen kannst du so oft wiederholen, wie du möchtest.')}`,'','LERNWEG');let b=page(`<span class="step-label">Das lernst du in diesem Kapitel</span><h2>Dein Inhaltsverzeichnis</h2>${ls.map((l,i)=>`<a class="contents-item" href="#lektion/${l.id}"><b>${String(i+1).padStart(2,'0')}</b><span><strong>${l.title}</strong><small>${l.goal}</small></span><span>↗</span></a>`).join('')}<div class="pdf-bar"><a class="btn secondary" download href="material/lehrbuch-${level}.pdf">Kapitel als PDF ↓</a></div>`,'','KAPITELÜBERSICHT');bookFrame(mq.matches&&side===1?b:a,mq.matches?'':b,{title:`Lernweg ${level==='B2'?'B2 Beruf':level}`,prev:mq.matches&&side===1?`#buch/${level}`:'#',next:mq.matches&&side===0?`#buch/${level}/1`:`#lektion/${ls[0].id}`});}
function grammarVisual(l){if(l.id==='kleidung')return `<div class="notebook"><h3>Ein Wort verändert sich.</h3><table class="grammar-table"><thead><tr><th>Wer?</th><th>Wen?</th><th>Mit wem?</th></tr></thead><tbody><tr><td>der rot<strong>e</strong><br>Pullover</td><td>den rot<strong>en</strong><br>Pullover</td><td>mit dem rot<strong>en</strong><br>Pullover</td></tr></tbody></table><p class="grammar-note">mit + Dativ → mit einer schwarzen Jacke</p></div>`;let pieces=l.example.split(/(?<=\.)\s+/).filter(Boolean);return `<div class="notebook"><h3>So klingt dein Satz:</h3>${pieces.map(s=>`<p class="example">${esc(s)}</p>`).join('')}<p class="grammar-note">Lies laut. Markiere das Verb. Probiere einen eigenen Satz.</p></div>`;}
lesson=function(id){let l=lessons.find(x=>x.id===id);if(!l)return missing();level=l.level;const ls=lessons.filter(x=>x.level===level),idx=ls.indexOf(l),raw=Number(location.hash.split('/')[2]||0);let step=Math.max(0,Math.min(5,Number.isFinite(raw)?raw:0));if(!mq.matches)step=Math.floor(step/2)*2;const base=idx*6,total=ls.length*6,art=artFor(l);const help=language==='de'?'':ruleHelp[l.id]?.[language]||'';
const pages=[
()=>page(`<span class="tape-label">Lektion ${String(idx+1).padStart(2,'0')} · ${level}</span><h1>${l.title}</h1><p>${l.goal}</p><img class="lesson-art" src="assets/${art}.webp" alt="${altFor(art)}"><div class="word-tags">${l.words.map(w=>`<span>${w}</span>`).join('')}</div>${teacherTip('Schau dir zuerst die Zeichnung an. Welche Wörter kennst du schon? Sage drei Sätze dazu.')}`,base+1,level),
()=>page(`<span class="step-label">01 / Entdecken & verstehen</span><h2>Eine Regel.<br>Viele Möglichkeiten.</h2><p class="rule">${l.rule}</p>${grammarVisual(l)}<div class="pdf-bar"><a class="btn secondary" download href="material/${l.id}.pdf">Lektion als PDF ↓</a></div>`,base+2,level),
()=>page(`<span class="step-label">02 / Lesen & Wörter sammeln</span><h2>Mitten im Leben.</h2><p class="context">${l.text}</p><label for="book-language" class="muted">Sprachhilfe</label><select id="book-language">${Object.entries(languages).map(([k,v])=>`<option value="${k}" ${k===language?'selected':''}>${v}</option>`).join('')}</select><p id="book-rule-help" class="muted" lang="${language}" dir="${['ar','fa'].includes(language)?'rtl':'ltr'}">${esc(help)}</p><table class="vocab"><caption class="muted">Deine Lernwörter</caption><tbody id="book-vocab">${l.words.map(w=>`<tr><td>${w}</td><td>${language==='de'?'—':esc(dictionary[w]?.[language]||'')}</td></tr>`).join('')}</tbody></table>`,base+3,level),
()=>page(`<span class="step-label">03 / Ausprobieren</span><h2>Jetzt bist du dran.</h2>${quiz(l.questions,id)}`,base+4,level),
()=>page(`<span class="step-label">04 / Selbst anwenden</span><h2>Deine eigenen Worte.</h2>${writing(l,id)}`,base+5,level),
()=>page(`<span class="step-label">05 / Mitnehmen & wiederholen</span><h2>Das bleibt im Kopf.</h2>${grammarVisual(l)}${teacherTip('Schließe die Erklärung kurz. Kannst du die Regel mit einem eigenen Beispiel erklären? Vergleiche danach noch einmal.')}<p>${l.goal}</p><div class="pdf-bar"><a class="btn" href="material/${l.id}.pdf" download>Merkblatt & Übungen als PDF ↓</a><a class="btn secondary" href="material/lehrbuch-${level}.pdf" download>Ganzes Kapitel als PDF ↓</a></div><p class="muted">Die Musterlösungen stehen am Ende der PDF-Datei.</p>`,base+6,level)
];let increment=mq.matches?1:2;let prev=step>0?`#lektion/${id}/${step-increment}`:idx>0?`#lektion/${ls[idx-1].id}/${mq.matches?5:4}`:`#buch/${level}`;let next=step+increment<6?`#lektion/${id}/${step+increment}`:idx+1<ls.length?`#lektion/${ls[idx+1].id}`:'#pruefung';bookFrame(pages[step](),mq.matches?'':pages[step+1](),{title:`${level==='B2'?'B2 Beruf':level} / ${l.title}`,prev,next,number:base+step+1,total});bindQuiz(l.questions,id);bindWriting(id);const sel=document.querySelector('#book-language');if(sel)sel.onchange=()=>{language=sel.value;let p=document.querySelector('#book-rule-help');p.textContent=language==='de'?'':ruleHelp[l.id]?.[language]||'';p.lang=language;p.dir=['ar','fa'].includes(language)?'rtl':'ltr';document.querySelector('#book-vocab').innerHTML=l.words.map(w=>`<tr><td>${w}</td><td lang="${language}" dir="${['ar','fa'].includes(language)?'rtl':'ltr'}">${language==='de'?'—':esc(dictionary[w]?.[language]||'')}</td></tr>`).join('');};};
home=()=>cover(0);
const oldRoute2=route;
route=function(){let h=location.hash.slice(1);if(h.startsWith('cover/'))cover(1);else if(h.startsWith('buch/'))levelIndex(h.split('/')[1],Number(h.split('/')[2]||0));else oldRoute2();document.querySelectorAll('[data-nav]').forEach(a=>{if(h.startsWith('buch/')||h.startsWith('cover/'))a.classList.toggle('active',a.dataset.nav==='learn');});updateDownloadButtons();window.scrollTo(0,0);};
function updateDownloadButtons(){const id=location.hash.split('/')[1];if(location.hash.startsWith('#training/')&&examUnits[id]){let b=document.querySelector('#print');if(b){let a=document.createElement('a');a.className='btn secondary';a.href=`material/${id}.pdf`;a.download='';a.textContent='Aufgabe als PDF ↓';b.replaceWith(a);}}}
/* Raster PDF writer: Unicode text is drawn by the browser, then embedded as JPEG pages. */
async function textPDF(text,title){await document.fonts.ready;const pages=[];const canvas=document.createElement('canvas');canvas.width=1240;canvas.height=1754;let ctx=canvas.getContext('2d'),y;function fresh(){ctx.fillStyle='#fffef8';ctx.fillRect(0,0,1240,1754);ctx.fillStyle='#284f3b';ctx.font='bold 36px Arial';ctx.fillText('DEUTSCH AKTIV',90,90);ctx.fillStyle='#333';ctx.font='24px Arial';ctx.fillText(title,90,140);ctx.font='27px Arial';y=210;}function finish(){ctx.save();ctx.fillStyle='#737b78';ctx.font='20px Arial';ctx.textAlign='center';ctx.fillText('created by D.Prudnikau',620,1700);ctx.restore();pages.push(canvas.toDataURL('image/jpeg',.92));}fresh();for(const para of text.split('\n')){let line='';for(const word of para.split(/\s+/)){let candidate=line?line+' '+word:word;if(ctx.measureText(candidate).width>1040&&line){ctx.fillText(line,90,y);y+=42;line=word;if(y>1610){finish();fresh();}}else line=candidate;}if(y>1610){finish();fresh();}ctx.fillText(line,90,y);y+=42;}finish();let encoder=new TextEncoder(),parts=[],offsets=[0],len=0;function add(x){let b=typeof x==='string'?encoder.encode(x):x;parts.push(b);len+=b.length;}function obj(n,body){offsets[n]=len;add(`${n} 0 obj\n${body}\nendobj\n`);}add('%PDF-1.4\n');obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,`<< /Type /Pages /Count ${pages.length} /Kids [${pages.map((_,i)=>`${3+i*3} 0 R`).join(' ')}] >>`);pages.forEach((url,i)=>{let n=3+i*3,bin=atob(url.split(',')[1]),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));obj(n,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im ${n+1} 0 R >> >> /Contents ${n+2} 0 R >>`);offsets[n+1]=len;add(`${n+1} 0 obj\n<< /Type /XObject /Subtype /Image /Width 1240 /Height 1754 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bytes.length} >>\nstream\n`);add(bytes);add('\nendstream\nendobj\n');const s='q 595 0 0 842 0 0 cm /Im Do Q';obj(n+2,`<< /Length ${s.length} >>\nstream\n${s}\nendstream`);});let start=len;add(`xref\n0 ${offsets.length}\n0000000000 65535 f \n`);for(let i=1;i<offsets.length;i++)add(String(offsets[i]).padStart(10,'0')+' 00000 n \n');add(`trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`);const blob=new Blob(parts,{type:'application/pdf'});let a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='mein-deutsch-text.pdf';a.className='btn secondary';a.textContent='PDF ist fertig – herunterladen ↓';a.setAttribute('data-generated-pdf','');let old=document.querySelector('[data-generated-pdf]');if(old){URL.revokeObjectURL(old.href);old.remove();}let target=document.querySelector('#save-text')||document.querySelector('.lesson-layout aside .panel');(target||main).append(a);a.focus();}
bindWriting=function(id){originalBindWriting(id);let b=document.querySelector('#save-text');if(b){b.textContent='Eigenen Text als PDF ↓';b.onclick=()=>textPDF(document.querySelector('#draft').value,lessons.find(l=>l.id===id)?.title||examUnits[id]?.title||'Mein Text');}};
mq.addEventListener('change',()=>{const t=document.activeElement?.tagName;if(t==='TEXTAREA'||t==='INPUT')return;if(document.querySelector('main .spread'))route();});
route();
