/* Aufgaben für die Tages-Challenge (challenge.js). lvl: "A" = A1–A2, "B" = B1. */
window.DM_CHALLENGE = {
  artikel: [
    /* ---------- A1–A2 ---------- */
    { w: "Zeitung", a: "die", lvl: "A", tip: "Nomen auf -ung sind immer feminin: die Zeitung." },
    { w: "Wohnung", a: "die", lvl: "A", tip: "Nomen auf -ung sind immer feminin: die Wohnung." },
    { w: "Rechnung", a: "die", lvl: "A", tip: "Nomen auf -ung sind immer feminin: die Rechnung." },
    { w: "Mädchen", a: "das", lvl: "A", tip: "Nomen auf -chen sind immer neutral: das Mädchen." },
    { w: "Brötchen", a: "das", lvl: "A", tip: "Nomen auf -chen sind immer neutral: das Brötchen." },
    { w: "Montag", a: "der", lvl: "A", tip: "Wochentage sind maskulin: der Montag." },
    { w: "Mittwoch", a: "der", lvl: "A", tip: "Wochentage sind maskulin: der Mittwoch." },
    { w: "Sonntag", a: "der", lvl: "A", tip: "Wochentage sind maskulin: der Sonntag." },
    { w: "Januar", a: "der", lvl: "A", tip: "Monatsnamen sind maskulin: der Januar." },
    { w: "Monat", a: "der", lvl: "A", tip: "Merkwort: der Monat – auch alle Monatsnamen sind maskulin." },
    { w: "Sommer", a: "der", lvl: "A", tip: "Jahreszeiten sind maskulin: der Sommer." },
    { w: "Frühling", a: "der", lvl: "A", tip: "Jahreszeiten sind maskulin: der Frühling." },
    { w: "Morgen", a: "der", lvl: "A", tip: "Tageszeiten sind maskulin: der Morgen (Ausnahme: die Nacht)." },
    { w: "Abend", a: "der", lvl: "A", tip: "Tageszeiten sind maskulin: der Abend (Ausnahme: die Nacht)." },
    { w: "Nacht", a: "die", lvl: "A", tip: "Ausnahme bei den Tageszeiten: die Nacht." },
    { w: "Tag", a: "der", lvl: "A", tip: "Merkwort: der Tag – wie der Morgen und der Abend." },
    { w: "Woche", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Woche." },
    { w: "Jahr", a: "das", lvl: "A", tip: "Merkwort: das Jahr." },
    { w: "Tisch", a: "der", lvl: "A", tip: "Merkwort: der Tisch." },
    { w: "Stuhl", a: "der", lvl: "A", tip: "Merkwort: der Stuhl." },
    { w: "Bett", a: "das", lvl: "A", tip: "Merkwort: das Bett." },
    { w: "Fenster", a: "das", lvl: "A", tip: "Merkwort: das Fenster." },
    { w: "Tür", a: "die", lvl: "A", tip: "Merkwort: die Tür." },
    { w: "Küche", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Küche." },
    { w: "Bad", a: "das", lvl: "A", tip: "Merkwort: das Bad." },
    { w: "Zimmer", a: "das", lvl: "A", tip: "Merkwort: das Zimmer." },
    { w: "Haus", a: "das", lvl: "A", tip: "Merkwort: das Haus." },
    { w: "Krankenhaus", a: "das", lvl: "A", tip: "Das letzte Wort bestimmt den Artikel: das Haus → das Krankenhaus." },
    { w: "Garten", a: "der", lvl: "A", tip: "Merkwort: der Garten." },
    { w: "Auto", a: "das", lvl: "A", tip: "Merkwort: das Auto." },
    { w: "Bus", a: "der", lvl: "A", tip: "Merkwort: der Bus." },
    { w: "Zug", a: "der", lvl: "A", tip: "Merkwort: der Zug." },
    { w: "Fahrrad", a: "das", lvl: "A", tip: "Das letzte Wort bestimmt den Artikel: das Rad → das Fahrrad." },
    { w: "Ticket", a: "das", lvl: "A", tip: "Merkwort: das Ticket." },
    { w: "Straße", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Straße." },
    { w: "Stadt", a: "die", lvl: "A", tip: "Merkwort: die Stadt." },
    { w: "Bahnhof", a: "der", lvl: "A", tip: "Das letzte Wort bestimmt den Artikel: der Hof → der Bahnhof." },
    { w: "Supermarkt", a: "der", lvl: "A", tip: "Das letzte Wort bestimmt den Artikel: der Markt → der Supermarkt." },
    { w: "Apotheke", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Apotheke." },
    { w: "Kasse", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Kasse." },
    { w: "Tasche", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Tasche." },
    { w: "Schlüssel", a: "der", lvl: "A", tip: "Merkwort: der Schlüssel." },
    { w: "Arzt", a: "der", lvl: "A", tip: "Männliche Personen sind maskulin: der Arzt." },
    { w: "Ärztin", a: "die", lvl: "A", tip: "Nomen auf -in (Frauen) sind immer feminin: die Ärztin." },
    { w: "Lehrerin", a: "die", lvl: "A", tip: "Nomen auf -in (Frauen) sind immer feminin: die Lehrerin." },
    { w: "Lehrer", a: "der", lvl: "A", tip: "Personen auf -er sind maskulin: der Lehrer." },
    { w: "Chef", a: "der", lvl: "A", tip: "Männliche Personen sind maskulin: der Chef." },
    { w: "Kollege", a: "der", lvl: "A", tip: "Männliche Person, auch mit -e: der Kollege." },
    { w: "Kind", a: "das", lvl: "A", tip: "Merkwort: das Kind." },
    { w: "Mutter", a: "die", lvl: "A", tip: "Frauen sind feminin: die Mutter." },
    { w: "Vater", a: "der", lvl: "A", tip: "Männer sind maskulin: der Vater." },
    { w: "Bruder", a: "der", lvl: "A", tip: "Männer sind maskulin: der Bruder." },
    { w: "Schwester", a: "die", lvl: "A", tip: "Frauen sind feminin: die Schwester." },
    { w: "Familie", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Familie." },
    { w: "Name", a: "der", lvl: "A", tip: "Ausnahme: -e, aber maskulin – der Name." },
    { w: "Brot", a: "das", lvl: "A", tip: "Merkwort: das Brot." },
    { w: "Milch", a: "die", lvl: "A", tip: "Merkwort: die Milch." },
    { w: "Wasser", a: "das", lvl: "A", tip: "Merkwort: das Wasser." },
    { w: "Kaffee", a: "der", lvl: "A", tip: "Merkwort: der Kaffee." },
    { w: "Tee", a: "der", lvl: "A", tip: "Merkwort: der Tee – wie der Kaffee." },
    { w: "Apfel", a: "der", lvl: "A", tip: "Merkwort: der Apfel." },
    { w: "Banane", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Banane." },
    { w: "Kartoffel", a: "die", lvl: "A", tip: "Merkwort: die Kartoffel." },
    { w: "Ei", a: "das", lvl: "A", tip: "Merkwort: das Ei." },
    { w: "Käse", a: "der", lvl: "A", tip: "Ausnahme: -e, aber maskulin – der Käse." },
    { w: "Fleisch", a: "das", lvl: "A", tip: "Merkwort: das Fleisch." },
    { w: "Reis", a: "der", lvl: "A", tip: "Merkwort: der Reis." },
    { w: "Zucker", a: "der", lvl: "A", tip: "Merkwort: der Zucker." },
    { w: "Salz", a: "das", lvl: "A", tip: "Merkwort: das Salz." },
    { w: "Geld", a: "das", lvl: "A", tip: "Merkwort: das Geld." },
    { w: "Handy", a: "das", lvl: "A", tip: "Merkwort: das Handy." },
    { w: "Telefon", a: "das", lvl: "A", tip: "Merkwort: das Telefon." },
    { w: "Computer", a: "der", lvl: "A", tip: "Geräte auf -er sind oft maskulin: der Computer." },
    { w: "Termin", a: "der", lvl: "A", tip: "Merkwort: der Termin." },
    { w: "Arbeit", a: "die", lvl: "A", tip: "Merkwort: die Arbeit." },
    { w: "Büro", a: "das", lvl: "A", tip: "Merkwort: das Büro." },
    { w: "Kurs", a: "der", lvl: "A", tip: "Merkwort: der Kurs." },
    { w: "Schule", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Schule." },
    { w: "Kita", a: "die", lvl: "A", tip: "Kita = Kindertagesstätte, und die Stätte ist feminin." },
    { w: "Buch", a: "das", lvl: "A", tip: "Merkwort: das Buch." },
    { w: "Heft", a: "das", lvl: "A", tip: "Merkwort: das Heft." },
    { w: "Stift", a: "der", lvl: "A", tip: "Merkwort: der Stift." },
    { w: "Uhr", a: "die", lvl: "A", tip: "Merkwort: die Uhr." },
    { w: "Hose", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Hose." },
    { w: "Jacke", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Jacke." },
    { w: "Schuh", a: "der", lvl: "A", tip: "Merkwort: der Schuh." },
    { w: "Hemd", a: "das", lvl: "A", tip: "Merkwort: das Hemd." },
    { w: "Kleid", a: "das", lvl: "A", tip: "Merkwort: das Kleid." },
    { w: "Mantel", a: "der", lvl: "A", tip: "Merkwort: der Mantel." },
    { w: "Kopf", a: "der", lvl: "A", tip: "Merkwort: der Kopf." },
    { w: "Hand", a: "die", lvl: "A", tip: "Merkwort: die Hand." },
    { w: "Auge", a: "das", lvl: "A", tip: "Ausnahme: -e, aber neutral – das Auge." },
    { w: "Bein", a: "das", lvl: "A", tip: "Merkwort: das Bein." },
    { w: "Bauch", a: "der", lvl: "A", tip: "Merkwort: der Bauch." },
    { w: "Fieber", a: "das", lvl: "A", tip: "Merkwort: das Fieber." },
    { w: "Tablette", a: "die", lvl: "A", tip: "Nomen auf -ette sind feminin: die Tablette." },
    { w: "Hund", a: "der", lvl: "A", tip: "Merkwort: der Hund." },
    { w: "Katze", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Katze." },
    { w: "Blume", a: "die", lvl: "A", tip: "Viele Nomen auf -e sind feminin: die Blume." },
    { w: "Wetter", a: "das", lvl: "A", tip: "Merkwort: das Wetter." },
    { w: "Regen", a: "der", lvl: "A", tip: "Wetterwörter sind oft maskulin: der Regen, der Schnee." },

    /* ---------- B1 ---------- */
    { w: "Erfahrung", a: "die", lvl: "B", tip: "Nomen auf -ung sind immer feminin: die Erfahrung." },
    { w: "Bewerbung", a: "die", lvl: "B", tip: "Nomen auf -ung sind immer feminin: die Bewerbung." },
    { w: "Versicherung", a: "die", lvl: "B", tip: "Nomen auf -ung sind immer feminin: die Versicherung." },
    { w: "Anmeldung", a: "die", lvl: "B", tip: "Nomen auf -ung sind immer feminin: die Anmeldung." },
    { w: "Kündigung", a: "die", lvl: "B", tip: "Nomen auf -ung sind immer feminin: die Kündigung." },
    { w: "Ausbildung", a: "die", lvl: "B", tip: "Nomen auf -ung sind immer feminin: die Ausbildung." },
    { w: "Meinung", a: "die", lvl: "B", tip: "Nomen auf -ung sind immer feminin: die Meinung." },
    { w: "Prüfung", a: "die", lvl: "B", tip: "Nomen auf -ung sind immer feminin: die Prüfung." },
    { w: "Erkältung", a: "die", lvl: "B", tip: "Nomen auf -ung sind immer feminin: die Erkältung." },
    { w: "Überweisung", a: "die", lvl: "B", tip: "Nomen auf -ung sind immer feminin: die Überweisung." },
    { w: "Gesundheit", a: "die", lvl: "B", tip: "Nomen auf -heit sind immer feminin: die Gesundheit." },
    { w: "Sicherheit", a: "die", lvl: "B", tip: "Nomen auf -heit sind immer feminin: die Sicherheit." },
    { w: "Möglichkeit", a: "die", lvl: "B", tip: "Nomen auf -keit sind immer feminin: die Möglichkeit." },
    { w: "Freundschaft", a: "die", lvl: "B", tip: "Nomen auf -schaft sind immer feminin: die Freundschaft." },
    { w: "Nachbarschaft", a: "die", lvl: "B", tip: "Nomen auf -schaft sind immer feminin: die Nachbarschaft." },
    { w: "Gewerkschaft", a: "die", lvl: "B", tip: "Nomen auf -schaft sind immer feminin: die Gewerkschaft." },
    { w: "Information", a: "die", lvl: "B", tip: "Nomen auf -tion sind immer feminin: die Information." },
    { w: "Situation", a: "die", lvl: "B", tip: "Nomen auf -tion sind immer feminin: die Situation." },
    { w: "Qualifikation", a: "die", lvl: "B", tip: "Nomen auf -tion sind immer feminin: die Qualifikation." },
    { w: "Kaution", a: "die", lvl: "B", tip: "Nomen auf -tion sind immer feminin: die Kaution." },
    { w: "Universität", a: "die", lvl: "B", tip: "Nomen auf -tät sind immer feminin: die Universität." },
    { w: "Nationalität", a: "die", lvl: "B", tip: "Nomen auf -tät sind immer feminin: die Nationalität." },
    { w: "Kultur", a: "die", lvl: "B", tip: "Nomen auf -ur sind meist feminin: die Kultur." },
    { w: "Bäckerei", a: "die", lvl: "B", tip: "Nomen auf -ei sind feminin: die Bäckerei." },
    { w: "Polizei", a: "die", lvl: "B", tip: "Nomen auf -ei sind feminin: die Polizei." },
    { w: "Krankenkasse", a: "die", lvl: "B", tip: "Das letzte Wort bestimmt den Artikel: die Kasse → die Krankenkasse." },
    { w: "Unterschrift", a: "die", lvl: "B", tip: "Das letzte Wort bestimmt den Artikel: die Schrift → die Unterschrift." },
    { w: "Rente", a: "die", lvl: "B", tip: "Viele Nomen auf -e sind feminin: die Rente." },
    { w: "Behörde", a: "die", lvl: "B", tip: "Viele Nomen auf -e sind feminin: die Behörde." },
    { w: "Erlaubnis", a: "die", lvl: "B", tip: "Ausnahme bei -nis: die Erlaubnis." },
    { w: "Praktikum", a: "das", lvl: "B", tip: "Nomen auf -um sind meist neutral: das Praktikum." },
    { w: "Zentrum", a: "das", lvl: "B", tip: "Nomen auf -um sind meist neutral: das Zentrum." },
    { w: "Studium", a: "das", lvl: "B", tip: "Nomen auf -um sind meist neutral: das Studium." },
    { w: "Datum", a: "das", lvl: "B", tip: "Nomen auf -um sind meist neutral: das Datum." },
    { w: "Dokument", a: "das", lvl: "B", tip: "Nomen auf -ment sind meist neutral: das Dokument." },
    { w: "Medikament", a: "das", lvl: "B", tip: "Nomen auf -ment sind meist neutral: das Medikament." },
    { w: "Ergebnis", a: "das", lvl: "B", tip: "Viele Nomen auf -nis sind neutral: das Ergebnis." },
    { w: "Zeugnis", a: "das", lvl: "B", tip: "Viele Nomen auf -nis sind neutral: das Zeugnis." },
    { w: "Gespräch", a: "das", lvl: "B", tip: "Viele Nomen mit Ge- sind neutral: das Gespräch." },
    { w: "Gebäude", a: "das", lvl: "B", tip: "Viele Nomen mit Ge- sind neutral: das Gebäude." },
    { w: "Gemüse", a: "das", lvl: "B", tip: "Viele Nomen mit Ge- sind neutral: das Gemüse." },
    { w: "Geschenk", a: "das", lvl: "B", tip: "Viele Nomen mit Ge- sind neutral: das Geschenk." },
    { w: "Gefühl", a: "das", lvl: "B", tip: "Viele Nomen mit Ge- sind neutral: das Gefühl." },
    { w: "Gehalt", a: "das", lvl: "B", tip: "Viele Nomen mit Ge- sind neutral: das Gehalt." },
    { w: "Einkommen", a: "das", lvl: "B", tip: "Merkwort: das Einkommen – wie das Essen und das Treffen." },
    { w: "Frühstück", a: "das", lvl: "B", tip: "Das letzte Wort bestimmt den Artikel: das Stück → das Frühstück." },
    { w: "Kindergeld", a: "das", lvl: "B", tip: "Das letzte Wort bestimmt den Artikel: das Geld → das Kindergeld." },
    { w: "Konto", a: "das", lvl: "B", tip: "Merkwort: das Konto." },
    { w: "Formular", a: "das", lvl: "B", tip: "Merkwort: das Formular." },
    { w: "Rezept", a: "das", lvl: "B", tip: "Merkwort: das Rezept." },
    { w: "Vertrag", a: "der", lvl: "B", tip: "Merkwort: der Vertrag." },
    { w: "Mietvertrag", a: "der", lvl: "B", tip: "Das letzte Wort bestimmt den Artikel: der Vertrag → der Mietvertrag." },
    { w: "Antrag", a: "der", lvl: "B", tip: "Merkwort: der Antrag – wie der Vertrag." },
    { w: "Lohn", a: "der", lvl: "B", tip: "Merkwort: der Lohn." },
    { w: "Urlaub", a: "der", lvl: "B", tip: "Merkwort: der Urlaub." },
    { w: "Beruf", a: "der", lvl: "B", tip: "Merkwort: der Beruf." },
    { w: "Arbeitgeber", a: "der", lvl: "B", tip: "Personen auf -er sind maskulin: der Arbeitgeber." },
    { w: "Kunde", a: "der", lvl: "B", tip: "Männliche Person, auch mit -e: der Kunde." },
    { w: "Ausweis", a: "der", lvl: "B", tip: "Merkwort: der Ausweis." },
    { w: "Führerschein", a: "der", lvl: "B", tip: "Das letzte Wort bestimmt den Artikel: der Schein → der Führerschein." },
    { w: "Kühlschrank", a: "der", lvl: "B", tip: "Das letzte Wort bestimmt den Artikel: der Schrank → der Kühlschrank." },
    { w: "Lebenslauf", a: "der", lvl: "B", tip: "Das letzte Wort bestimmt den Artikel: der Lauf → der Lebenslauf." },
    { w: "Feierabend", a: "der", lvl: "B", tip: "Das letzte Wort bestimmt den Artikel: der Abend → der Feierabend." },
    { w: "Bescheid", a: "der", lvl: "B", tip: "Merkwort: der Bescheid (z. B. vom Amt)." },
    { w: "Optimismus", a: "der", lvl: "B", tip: "Nomen auf -ismus sind immer maskulin: der Optimismus." },
    { w: "Tourismus", a: "der", lvl: "B", tip: "Nomen auf -ismus sind immer maskulin: der Tourismus." }
  ],

  verb: [
    /* ---------- A1–A2 ---------- */
    { lvl: "A", q: "Wir ___ am Samstag ins Kino.", o: ["gehen", "geht", "gehst"], a: 0, tip: "wir + Verb mit -en: wir gehen." },
    { lvl: "A", q: "Du ___ sehr gut Deutsch.", o: ["sprechst", "sprichst", "spricht"], a: 1, tip: "sprechen wechselt e → i bei du und er: du sprichst." },
    { lvl: "A", q: "Er ___ jeden Morgen die Zeitung.", o: ["lest", "lesen", "liest"], a: 2, tip: "lesen wechselt e → ie bei du und er: er liest." },
    { lvl: "A", q: "___ du heute Zeit?", o: ["Habst", "Hast", "Hat"], a: 1, tip: "haben ist unregelmäßig: du hast." },
    { lvl: "A", q: "Ich ___ aus Syrien.", o: ["kommst", "kommt", "komme"], a: 2, tip: "ich + Verb mit -e: ich komme." },
    { lvl: "A", q: "Anna ___ in Essen.", o: ["wohnt", "wohnst", "wohnen"], a: 0, tip: "er/sie + Verb mit -t: Anna wohnt." },
    { lvl: "A", q: "Mein Sohn ___ mit dem Bus zur Schule.", o: ["fahrt", "fahren", "fährt"], a: 2, tip: "fahren wechselt a → ä bei du und er: er fährt." },
    { lvl: "A", q: "Ihr ___ heute sehr müde.", o: ["seid", "sind", "seit"], a: 0, tip: "sein bei ihr: ihr seid (mit d, nicht seit)." },
    { lvl: "A", q: "Ich ___ morgen nicht arbeiten.", o: ["kannst", "kann", "können"], a: 1, tip: "Modalverb bei ich ohne Endung: ich kann." },
    { lvl: "A", q: "Du ___ heute früh ins Bett gehen.", o: ["muss", "müssen", "musst"], a: 2, tip: "müssen bei du: du musst – ohne Umlaut." },
    { lvl: "A", q: "Der Kurs ___ um neun Uhr an.", o: ["fangt", "fängt", "fangen"], a: 1, tip: "anfangen: a → ä bei er, Vorsilbe an am Ende." },
    { lvl: "A", q: "Ich ___ meine Mutter jeden Sonntag an.", o: ["rufen", "ruft", "rufe"], a: 2, tip: "anrufen ist trennbar: ich rufe … an." },
    { lvl: "A", q: "___ bitte das Fenster zu, Ali!", o: ["Mach", "Machst", "Machen"], a: 0, tip: "Imperativ mit du: Verbstamm ohne -st: Mach!" },
    { lvl: "A", q: "___ Sie bitte Platz!", o: ["Nimm", "Nehmt", "Nehmen"], a: 2, tip: "Imperativ mit Sie: Infinitiv + Sie: Nehmen Sie!" },
    { lvl: "A", q: "Ich habe gestern Pizza ___.", o: ["gegessen", "geesst", "essen"], a: 0, tip: "essen ist unregelmäßig: Partizip gegessen." },
    { lvl: "A", q: "Wir sind nach Berlin ___.", o: ["gefahrt", "gefahren", "fahren"], a: 1, tip: "fahren ist unregelmäßig: Partizip gefahren." },
    { lvl: "A", q: "Er ___ gestern lange geschlafen.", o: ["ist", "habt", "hat"], a: 2, tip: "schlafen = keine Bewegung → Perfekt mit haben." },
    { lvl: "A", q: "Meine Frau ist um sechs Uhr ___.", o: ["aufgesteht", "aufgestanden", "aufstehen"], a: 1, tip: "Trennbar: auf + ge + standen = aufgestanden." },
    { lvl: "A", q: "Ich ___ einen Kaffee, bitte.", o: ["möchtest", "möchten", "möchte"], a: 2, tip: "möchten bei ich: ich möchte." },
    { lvl: "A", q: "___ ihr Kinder?", o: ["Habt", "Hat", "Haben"], a: 0, tip: "haben bei ihr: ihr habt." },
    { lvl: "A", q: "Das Baby ___ viel.", o: ["schlaft", "schlafen", "schläft"], a: 2, tip: "schlafen wechselt a → ä bei er/es: es schläft." },
    { lvl: "A", q: "Was ___ du am Wochenende?", o: ["machst", "macht", "machen"], a: 0, tip: "du + Verb mit -st: du machst." },
    { lvl: "A", q: "Wie ___ du?", o: ["heiße", "heißt", "heißen"], a: 1, tip: "du + -st, nach ß nur -t: du heißt." },
    { lvl: "A", q: "Mein Mann ___ als Koch.", o: ["arbeitest", "arbeiten", "arbeitet"], a: 2, tip: "Stamm auf -t → er arbeitet (mit -et)." },
    { lvl: "A", q: "Du ___ zu schnell!", o: ["fahrst", "fährst", "fahren"], a: 1, tip: "fahren wechselt a → ä bei du: du fährst." },
    { lvl: "A", q: "Der Arzt ___ mir ein Rezept.", o: ["gebt", "geben", "gibt"], a: 2, tip: "geben wechselt e → i bei du und er: er gibt." },
    { lvl: "A", q: "Ich ___ heute keine Zeit.", o: ["habe", "hat", "haben"], a: 0, tip: "haben bei ich: ich habe." },
    { lvl: "A", q: "Wir ___ am Wochenende Fußball spielen.", o: ["will", "willst", "wollen"], a: 2, tip: "wollen bei wir: wir wollen." },
    { lvl: "A", q: "___ ich hier rauchen?", o: ["Darf", "Darfst", "Dürfen"], a: 0, tip: "dürfen bei ich: ich darf – ohne Endung." },
    { lvl: "A", q: "Er ___ seine Freundin am Bahnhof ab.", o: ["holen", "holt", "holst"], a: 1, tip: "abholen ist trennbar: er holt … ab." },
    { lvl: "A", q: "Wann ___ der Film an?", o: ["fangt", "fangen", "fängt"], a: 2, tip: "anfangen bei er/es: der Film fängt an." },
    { lvl: "A", q: "Ich bin gestern zu Hause ___.", o: ["gebleibt", "geblieben", "bleiben"], a: 1, tip: "bleiben ist unregelmäßig: Partizip geblieben." },
    { lvl: "A", q: "Wir haben heute viel Deutsch ___.", o: ["gelernen", "lernt", "gelernt"], a: 2, tip: "Regelmäßige Verben: ge- + Stamm + -t = gelernt." },
    { lvl: "A", q: "Hast du die Hausaufgaben ___?", o: ["gemacht", "gemachen", "macht"], a: 0, tip: "machen ist regelmäßig: Partizip gemacht." },
    { lvl: "A", q: "Der Bus ist schon ___.", o: ["geabfahren", "abfahren", "abgefahren"], a: 2, tip: "Trennbar: ab + ge + fahren = abgefahren." },
    { lvl: "A", q: "Ich ___ dir morgen beim Umzug.", o: ["helfe", "hilfe", "hilft"], a: 0, tip: "helfen: e → i nur bei du und er, ich helfe." },
    { lvl: "A", q: "___ du mir bitte helfen?", o: ["Kann", "Kannst", "Könnt"], a: 1, tip: "können bei du: du kannst." },
    { lvl: "A", q: "Was ___ du gern?", o: ["esst", "essen", "isst"], a: 2, tip: "essen wechselt e → i bei du: du isst." },
    { lvl: "A", q: "___ Sie bitte langsam!", o: ["Sprich", "Sprechen", "Sprecht"], a: 1, tip: "Imperativ mit Sie: Sprechen Sie bitte langsam!" },
    { lvl: "A", q: "Ihr ___ morgen um acht Uhr da sein.", o: ["müssen", "muss", "müsst"], a: 2, tip: "müssen bei ihr: ihr müsst." },
    { lvl: "A", q: "Er ___ heute krank.", o: ["ist", "sind", "bist"], a: 0, tip: "sein bei er: er ist." },
    { lvl: "A", q: "Entschuldigung, ich ___ Sie nicht verstehen.", o: ["könne", "können", "kann"], a: 2, tip: "können bei ich: ich kann." },
    { lvl: "A", q: "Der Zug ist pünktlich ___.", o: ["angekommen", "angekommt", "ankommen"], a: 0, tip: "Trennbar: an + ge + kommen = angekommen." },
    { lvl: "A", q: "Wo ___ du?", o: ["wohnt", "wohnst", "wohnen"], a: 1, tip: "du + Verb mit -st: du wohnst." },
    { lvl: "A", q: "Mein Kind ___ Fieber.", o: ["ist", "haben", "hat"], a: 2, tip: "Fieber haben: mein Kind hat Fieber." },
    { lvl: "A", q: "Ich habe dir eine Nachricht ___.", o: ["geschicken", "geschickt", "schicken"], a: 1, tip: "schicken ist regelmäßig: Partizip geschickt." },
    { lvl: "A", q: "Er ___ im Supermarkt ein.", o: ["kaufen", "kaufst", "kauft"], a: 2, tip: "einkaufen ist trennbar: er kauft … ein." },
    { lvl: "A", q: "Lukas, ___ bitte leise!", o: ["sei", "bist", "sein"], a: 0, tip: "Imperativ von sein mit du: Sei leise!" },
    { lvl: "A", q: "Was ___ das?", o: ["kosten", "kostest", "kostet"], a: 2, tip: "das = es → Verb mit -et: das kostet." },
    { lvl: "A", q: "Seit wann ___ ihr in Deutschland?", o: ["seid", "sind", "seit"], a: 0, tip: "Verb sein bei ihr: ihr seid. „seit“ ist eine Präposition." },
    { lvl: "A", q: "Der Kurs hat um neun Uhr ___.", o: ["angefangt", "angefangen", "anfangen"], a: 1, tip: "anfangen ist unregelmäßig: an + ge + fangen." },
    { lvl: "A", q: "Hier ___ Sie bitte unterschreiben.", o: ["musst", "muss", "müssen"], a: 2, tip: "Höflich mit Sie: Sie müssen." },

    /* ---------- B1 ---------- */
    { lvl: "B", q: "Wenn ich Zeit hätte, ___ ich dich besuchen.", o: ["werde", "würde", "wurde"], a: 1, tip: "Irreale Bedingung → Konjunktiv II: würde + Infinitiv." },
    { lvl: "B", q: "Wenn ich mehr Geld ___, würde ich ein Auto kaufen.", o: ["habe", "hatte", "hätte"], a: 2, tip: "Irrealer Wunsch → Konjunktiv II von haben: hätte." },
    { lvl: "B", q: "Wenn ich du ___, würde ich zum Arzt gehen.", o: ["wäre", "war", "bin"], a: 0, tip: "Ratschlag mit Konjunktiv II: Wenn ich du wäre …" },
    { lvl: "B", q: "Es ___ schön, wenn du am Samstag kommen könntest.", o: ["war", "würde", "wäre"], a: 2, tip: "Konjunktiv II von sein: es wäre." },
    { lvl: "B", q: "An deiner Stelle ___ ich den Vertrag nicht unterschreiben.", o: ["würde", "werde", "wurde"], a: 0, tip: "Ratschlag: An deiner Stelle würde ich …" },
    { lvl: "B", q: "Wenn es nicht so kalt ___, würden wir spazieren gehen.", o: ["war", "wäre", "ist"], a: 1, tip: "Irreale Bedingung: wenn … wäre, würden wir …" },
    { lvl: "B", q: "___ du mir bitte den Zucker geben?", o: ["Wurdest", "Würde", "Würdest"], a: 2, tip: "Höfliche Bitte: Würdest du …? (du → -st)." },
    { lvl: "B", q: "Das ___ ich nicht gedacht!", o: ["wäre", "hätte", "würde"], a: 1, tip: "denken bildet Perfekt mit haben → Konjunktiv II: hätte gedacht." },
    { lvl: "B", q: "Die Briefe ___ morgen verschickt.", o: ["wird", "werdet", "werden"], a: 2, tip: "Passiv: werden + Partizip; Briefe = Plural → werden." },
    { lvl: "B", q: "Das Paket ___ morgen geliefert.", o: ["wird", "werden", "wurde"], a: 0, tip: "Passiv Präsens (auch Zukunft): das Paket wird geliefert." },
    { lvl: "B", q: "In diesem Büro ___ auch Englisch gesprochen.", o: ["werden", "wirst", "wird"], a: 2, tip: "Englisch ist Singular → Passiv mit wird: wird gesprochen." },
    { lvl: "B", q: "Mein Fahrrad ___ letzte Woche gestohlen.", o: ["wurde", "würde", "wird"], a: 0, tip: "Vergangenheit im Passiv: wurde + Partizip." },
    { lvl: "B", q: "Der Termin ___ gestern abgesagt.", o: ["würde", "wurde", "wird"], a: 1, tip: "gestern → Passiv Präteritum: wurde abgesagt." },
    { lvl: "B", q: "Die Wohnung muss renoviert ___.", o: ["wird", "worden", "werden"], a: 2, tip: "Passiv mit Modalverb: muss + Partizip + werden." },
    { lvl: "B", q: "Die Rechnung muss bis Freitag ___ werden.", o: ["bezahlen", "bezahlt", "gebezahlt"], a: 1, tip: "Verben auf be- ohne ge-: bezahlt." },
    { lvl: "B", q: "Die Kinder ___ um 16 Uhr von der Kita abgeholt werden.", o: ["muss", "müsst", "müssen"], a: 2, tip: "Die Kinder = Plural → müssen." },
    { lvl: "B", q: "Als ich am Bahnhof ankam, ___ der Zug schon abgefahren.", o: ["war", "hatte", "ist"], a: 0, tip: "Plusquamperfekt: abfahren mit sein → war abgefahren." },
    { lvl: "B", q: "Nachdem er gegessen ___, ging er spazieren.", o: ["hat", "war", "hatte"], a: 2, tip: "Vor dem Präteritum: Plusquamperfekt mit hatte." },
    { lvl: "B", q: "Nachdem wir ___ hatten, gingen wir ins Kino.", o: ["gegessen", "geessen", "essen"], a: 0, tip: "Partizip von essen: gegessen (mit -ge- in der Mitte)." },
    { lvl: "B", q: "Bevor ich nach Deutschland kam, ___ ich schon Englisch gelernt.", o: ["habe", "hatte", "war"], a: 1, tip: "Noch früher als kam → Plusquamperfekt: hatte gelernt." },
    { lvl: "B", q: "Letztes Jahr ___ wir in Spanien.", o: ["sind", "wart", "waren"], a: 2, tip: "Vergangenheit von sein bei wir: wir waren." },
    { lvl: "B", q: "Gestern ___ ich keine Zeit.", o: ["habe", "hatte", "hätte"], a: 1, tip: "Präteritum von haben: ich hatte." },
    { lvl: "B", q: "Als Kind ___ ich nicht schwimmen.", o: ["kann", "könnte", "konnte"], a: 2, tip: "Präteritum von können: ich konnte (ohne Umlaut)." },
    { lvl: "B", q: "Früher ___ ich in Polen.", o: ["wohnte", "wohne", "wohnen"], a: 0, tip: "früher → Vergangenheit: ich wohnte." },
    { lvl: "B", q: "Früher ___ ich jeden Tag Fußball.", o: ["spiele", "spielt", "spielte"], a: 2, tip: "Präteritum regelmäßig: Stamm + -te = spielte." },
    { lvl: "B", q: "Gestern ___ ich beim Arzt.", o: ["war", "bin", "wäre"], a: 0, tip: "Präteritum von sein: ich war." },
    { lvl: "B", q: "Ich habe den ganzen Tag ___.", o: ["arbeitet", "gearbeitet", "gearbeitt"], a: 1, tip: "Stamm auf -t → Partizip mit -et: gearbeitet." },
    { lvl: "B", q: "Wir haben uns gestern im Park ___.", o: ["getrefft", "treffen", "getroffen"], a: 2, tip: "treffen ist unregelmäßig: Partizip getroffen." },
    { lvl: "B", q: "Sie ist letztes Jahr nach Deutschland ___.", o: ["gekommt", "gekommen", "kommen"], a: 1, tip: "kommen ist unregelmäßig: Partizip gekommen." },
    { lvl: "B", q: "Hast du dich schon um die Stelle ___?", o: ["bewerbt", "gebewerbt", "beworben"], a: 2, tip: "sich bewerben: unregelmäßig, mit be- ohne ge- → beworben." },
    { lvl: "B", q: "Ich habe mich sehr über deinen Besuch ___.", o: ["gefreut", "freut", "gefreuen"], a: 0, tip: "freuen ist regelmäßig: Partizip gefreut." },
    { lvl: "B", q: "Ich freue ___ auf das Wochenende.", o: ["mir", "sich", "mich"], a: 2, tip: "sich freuen: bei ich → mich (Akkusativ)." },
    { lvl: "B", q: "Wir treffen ___ um acht Uhr vor dem Kino.", o: ["uns", "euch", "sich"], a: 0, tip: "Reflexivpronomen bei wir: uns." },
    { lvl: "B", q: "Ich ___ mich über dein Geschenk.", o: ["freut", "freue", "freuen"], a: 1, tip: "ich + Verb mit -e: ich freue mich." },
    { lvl: "B", q: "Kannst du ___ bitte setzen?", o: ["dir", "sich", "dich"], a: 2, tip: "sich setzen: bei du → dich." },
    { lvl: "B", q: "Ich wasche ___ die Hände.", o: ["mich", "mir", "sich"], a: 1, tip: "Mit Akkusativobjekt (die Hände) → Reflexivpronomen im Dativ: mir." },
    { lvl: "B", q: "Die Kinder ___ sich auf die Ferien.", o: ["freut", "freust", "freuen"], a: 2, tip: "Die Kinder = sie (Plural) → sie freuen sich." },
    { lvl: "B", q: "Er hat ___ beim Sport verletzt.", o: ["sich", "ihn", "ihm"], a: 0, tip: "Reflexiv bei er/sie/es: sich." },
    { lvl: "B", q: "Ich ___ mich nicht an seinen Namen erinnern.", o: ["könne", "kannst", "kann"], a: 2, tip: "können bei ich: ich kann." },
    { lvl: "B", q: "Ich ___ mich sehr für diese Stelle.", o: ["interessiere", "interessierst", "interessieren"], a: 0, tip: "ich + Verb mit -e: ich interessiere mich." },
    { lvl: "B", q: "Wir ___ uns beim Vermieter über den Lärm beschwert.", o: ["sind", "haben", "hat"], a: 1, tip: "Reflexive Verben bilden das Perfekt mit haben." },
    { lvl: "B", q: "Er ___ sich jeden Morgen.", o: ["rasiere", "rasieren", "rasiert"], a: 2, tip: "er + Verb mit -t: er rasiert sich." },
    { lvl: "B", q: "Ich muss ___ beeilen, der Bus kommt gleich.", o: ["mir", "mich", "sich"], a: 1, tip: "sich beeilen: bei ich → mich." },
    { lvl: "B", q: "Stell ___ vor, ich habe die Stelle bekommen!", o: ["dich", "sich", "dir"], a: 2, tip: "sich etwas vorstellen: Dativ → Stell dir vor!" },
    { lvl: "B", q: "Ich ___ mich herzlich für Ihre Hilfe.", o: ["bedanke", "bedankt", "bedanken"], a: 0, tip: "ich + Verb mit -e: ich bedanke mich." },
    { lvl: "B", q: "Worauf ___ du?", o: ["wartet", "warten", "wartest"], a: 2, tip: "Stamm auf -t → du wartest (mit -est)." },
    { lvl: "B", q: "Ich habe ___ erkältet.", o: ["mich", "mir", "sich"], a: 0, tip: "sich erkälten: bei ich → mich." },
    { lvl: "B", q: "Ich ___ mich heute nicht wohl.", o: ["fühlt", "fühle", "fühlen"], a: 1, tip: "ich + Verb mit -e: ich fühle mich." },
    { lvl: "B", q: "___ ihr euch schon für den Kurs angemeldet?", o: ["Seid", "Hat", "Habt"], a: 2, tip: "Reflexive Verben: Perfekt mit haben → ihr habt." },
    { lvl: "B", q: "Mein Sohn ___ sich um einen Ausbildungsplatz.", o: ["bewerbt", "bewirbt", "bewerben"], a: 1, tip: "bewerben wechselt e → i bei er: er bewirbt sich." },
    { lvl: "B", q: "Ich weiß nicht, ob er heute ___.", o: ["kommen", "kommst", "kommt"], a: 2, tip: "Im Nebensatz steht das Verb am Ende: ob er kommt." }
  ],

  kasus: [
    /* ---------- A1–A2 ---------- */
    { lvl: "A", q: "Ich fahre mit ___ Bus zur Arbeit.", o: ["dem", "den", "der"], a: 0, tip: "mit + Dativ: mit dem Bus." },
    { lvl: "A", q: "Er fährt mit ___ Fahrrad.", o: ["das", "den", "dem"], a: 2, tip: "mit + Dativ, neutral: mit dem Fahrrad." },
    { lvl: "A", q: "Ich kaufe ___ Apfel.", o: ["einen", "einem", "ein"], a: 0, tip: "kaufen + Akkusativ, maskulin: einen Apfel." },
    { lvl: "A", q: "Ich gehe heute mit ___ Tochter zur Ärztin.", o: ["meine", "meiner", "meinen"], a: 1, tip: "mit + Dativ, feminin: mit meiner Tochter." },
    { lvl: "A", q: "Er kommt aus ___ Türkei.", o: ["die", "dem", "der"], a: 2, tip: "aus + Dativ: aus der Türkei." },
    { lvl: "A", q: "Das Geschenk ist für ___ Mutter.", o: ["meiner", "meine", "meinem"], a: 1, tip: "für + Akkusativ, feminin: für meine Mutter." },
    { lvl: "A", q: "Ich gehe nie ohne ___ Jacke raus.", o: ["meiner", "meinem", "meine"], a: 2, tip: "ohne + Akkusativ, feminin: ohne meine Jacke." },
    { lvl: "A", q: "Kannst du ___ helfen?", o: ["mir", "mich", "ich"], a: 0, tip: "helfen + Dativ: Kannst du mir helfen?" },
    { lvl: "A", q: "Ich liebe ___.", o: ["dir", "du", "dich"], a: 2, tip: "lieben + Akkusativ: Ich liebe dich." },
    { lvl: "A", q: "Ich wohne bei ___ Eltern.", o: ["meinen", "meine", "meiner"], a: 0, tip: "bei + Dativ Plural: bei meinen Eltern (-en)." },
    { lvl: "A", q: "Nach ___ Kurs gehe ich einkaufen.", o: ["den", "dem", "der"], a: 1, tip: "nach + Dativ, maskulin: nach dem Kurs." },
    { lvl: "A", q: "Ich habe ___ Bruder und eine Schwester.", o: ["ein", "einem", "einen"], a: 2, tip: "haben + Akkusativ, maskulin: einen Bruder." },
    { lvl: "A", q: "Die Kinder spielen ___ Garten.", o: ["ins", "im", "in"], a: 1, tip: "Wo? → Dativ: in dem = im Garten." },
    { lvl: "A", q: "Ich lege das Buch auf ___ Tisch.", o: ["dem", "der", "den"], a: 2, tip: "legen = Wohin? → Akkusativ: auf den Tisch." },
    { lvl: "A", q: "Das Buch liegt auf ___ Tisch.", o: ["dem", "den", "der"], a: 0, tip: "liegen = Wo? → Dativ: auf dem Tisch." },
    { lvl: "A", q: "Heute Abend gehe ich ___ Kino.", o: ["im", "in", "ins"], a: 2, tip: "Wohin? → Akkusativ: in das = ins Kino." },
    { lvl: "A", q: "Wir sind gerade ___ Supermarkt.", o: ["im", "ins", "in"], a: 0, tip: "Wo? → Dativ: in dem = im Supermarkt." },
    { lvl: "A", q: "Ich hänge das Bild an ___ Wand.", o: ["der", "die", "den"], a: 1, tip: "hängen (Wohin?) → Akkusativ: an die Wand." },
    { lvl: "A", q: "Das Bild hängt an ___ Wand.", o: ["die", "den", "der"], a: 2, tip: "hängt (Wo?) → Dativ, feminin: an der Wand." },
    { lvl: "A", q: "Gib ___ bitte das Salz!", o: ["mich", "mir", "ich"], a: 1, tip: "Wem gibst du etwas? → Dativ: mir." },
    { lvl: "A", q: "Ich rufe ___ morgen an.", o: ["dir", "du", "dich"], a: 2, tip: "anrufen + Akkusativ: Ich rufe dich an." },
    { lvl: "A", q: "Wie geht es ___?", o: ["Ihnen", "Sie", "Ihr"], a: 0, tip: "Wie geht es + Dativ: Wie geht es Ihnen?" },
    { lvl: "A", q: "Ich danke ___ für die Hilfe.", o: ["dich", "du", "dir"], a: 2, tip: "danken + Dativ: Ich danke dir." },
    { lvl: "A", q: "Ich suche ___ Schlüssel.", o: ["meinen", "meinem", "mein"], a: 0, tip: "suchen + Akkusativ, maskulin: meinen Schlüssel." },
    { lvl: "A", q: "Hast du ___ Ausweis dabei?", o: ["deinem", "deinen", "dein"], a: 1, tip: "haben + Akkusativ, maskulin: deinen Ausweis." },
    { lvl: "A", q: "Heute habe ich leider ___ Zeit.", o: ["kein", "keinen", "keine"], a: 2, tip: "die Zeit → Akkusativ feminin: keine Zeit." },
    { lvl: "A", q: "Wir brauchen ___ neues Auto.", o: ["einen", "ein", "einem"], a: 1, tip: "das Auto → Akkusativ neutral: ein Auto." },
    { lvl: "A", q: "Ich komme gerade von ___ Arbeit.", o: ["die", "dem", "der"], a: 2, tip: "von + Dativ, feminin: von der Arbeit." },
    { lvl: "A", q: "Seit ___ Jahr lerne ich Deutsch.", o: ["einem", "einen", "ein"], a: 0, tip: "seit + Dativ, neutral: seit einem Jahr." },
    { lvl: "A", q: "Das Handy gehört ___.", o: ["mich", "ich", "mir"], a: 2, tip: "gehören + Dativ: Das gehört mir." },
    { lvl: "A", q: "Gefällt ___ die Wohnung?", o: ["dir", "dich", "du"], a: 0, tip: "gefallen + Dativ: Gefällt dir …?" },
    { lvl: "A", q: "Ich sehe ___ Mann dort nicht.", o: ["dem", "den", "der"], a: 1, tip: "sehen + Akkusativ, maskulin: den Mann." },
    { lvl: "A", q: "Am Wochenende besuchen wir ___ Freunde.", o: ["unseren", "unserer", "unsere"], a: 2, tip: "besuchen + Akkusativ Plural: unsere Freunde." },
    { lvl: "A", q: "Ich habe Zahnschmerzen. Ich gehe ___ Zahnarzt.", o: ["zur", "zum", "zu"], a: 1, tip: "zu + dem (maskulin) = zum Zahnarzt." },
    { lvl: "A", q: "Ich bringe den Brief ___ Post.", o: ["zum", "zu", "zur"], a: 2, tip: "zu + der (feminin) = zur Post." },
    { lvl: "A", q: "Der Schlüssel liegt unter ___ Tasche.", o: ["der", "die", "den"], a: 0, tip: "liegen = Wo? → Dativ, feminin: unter der Tasche." },
    { lvl: "A", q: "Fragen Sie bitte ___ Kollegen.", o: ["Ihrem", "Ihr", "Ihren"], a: 2, tip: "fragen + Akkusativ, maskulin: Ihren Kollegen." },
    { lvl: "A", q: "Ich schreibe ___ Freundin eine Nachricht.", o: ["meiner", "meine", "meinen"], a: 0, tip: "Wem? → Dativ, feminin: meiner Freundin." },
    { lvl: "A", q: "Ich stelle die Milch in ___ Kühlschrank.", o: ["dem", "den", "der"], a: 1, tip: "stellen = Wohin? → Akkusativ: in den Kühlschrank." },
    { lvl: "A", q: "Die Milch steht ___ Kühlschrank.", o: ["ins", "in", "im"], a: 2, tip: "stehen = Wo? → Dativ: in dem = im Kühlschrank." },
    { lvl: "A", q: "Am Wochenende fahren wir ___ Berlin.", o: ["zu", "nach", "in"], a: 1, tip: "Städte und Länder ohne Artikel: nach Berlin." },
    { lvl: "A", q: "Das ist ___ neue Lehrerin.", o: ["unserer", "unseren", "unsere"], a: 2, tip: "Nach „Das ist“ steht Nominativ: unsere Lehrerin." },

    /* ---------- B1 ---------- */
    { lvl: "B", q: "Wegen ___ Regens bleiben wir zu Hause.", o: ["des", "dem", "den"], a: 0, tip: "wegen + Genitiv, maskulin: des Regens (mit -s)." },
    { lvl: "B", q: "Trotz ___ Erkältung geht sie arbeiten.", o: ["die", "den", "der"], a: 2, tip: "trotz + Genitiv, feminin: trotz der Erkältung." },
    { lvl: "B", q: "Während ___ Unterrichts bleibt das Handy aus.", o: ["des", "dem", "den"], a: 0, tip: "während + Genitiv, maskulin: des Unterrichts." },
    { lvl: "B", q: "Wegen ___ Krankheit konnte er nicht kommen.", o: ["seine", "seiner", "seinen"], a: 1, tip: "wegen + Genitiv, feminin: seiner Krankheit." },
    { lvl: "B", q: "Am Ende ___ Monats bekomme ich mein Gehalt.", o: ["dem", "den", "des"], a: 2, tip: "Genitiv, maskulin: am Ende des Monats." },
    { lvl: "B", q: "Ich habe mir einen ___ Pullover gekauft.", o: ["warme", "warmen", "warmer"], a: 1, tip: "Akkusativ maskulin: einen warmen Pullover." },
    { lvl: "B", q: "Das ist eine ___ Idee!", o: ["guter", "gutes", "gute"], a: 2, tip: "Nominativ feminin mit eine: eine gute Idee." },
    { lvl: "B", q: "Ich wohne in einer ___ Wohnung.", o: ["kleinen", "kleine", "kleiner"], a: 0, tip: "Dativ nach einer: immer -en: in einer kleinen Wohnung." },
    { lvl: "B", q: "Der ___ Mann im Erdgeschoss ist mein Nachbar.", o: ["alten", "alter", "alte"], a: 2, tip: "Nominativ mit der: der alte Mann." },
    { lvl: "B", q: "Ich trinke morgens gern ___ Kaffee.", o: ["schwarzen", "schwarzer", "schwarzes"], a: 0, tip: "Ohne Artikel, Akkusativ maskulin: schwarzen Kaffee." },
    { lvl: "B", q: "Wir suchen eine Wohnung mit einem ___ Balkon.", o: ["großem", "großen", "großer"], a: 1, tip: "Dativ nach einem: immer -en: mit einem großen Balkon." },
    { lvl: "B", q: "Bei ___ Wetter bleiben wir lieber zu Hause.", o: ["schlechten", "schlechtes", "schlechtem"], a: 2, tip: "Ohne Artikel, Dativ neutral: bei schlechtem Wetter." },
    { lvl: "B", q: "Wie gefallen dir meine ___ Schuhe?", o: ["neue", "neuen", "neuer"], a: 1, tip: "Nach meine im Plural immer -en: meine neuen Schuhe." },
    { lvl: "B", q: "Vielen Dank für Ihre ___ Hilfe!", o: ["schnellen", "schneller", "schnelle"], a: 2, tip: "Akkusativ feminin: für Ihre schnelle Hilfe." },
    { lvl: "B", q: "Ich wünsche dir ein ___ Wochenende!", o: ["schönes", "schönen", "schöne"], a: 0, tip: "Akkusativ neutral mit ein: ein schönes Wochenende." },
    { lvl: "B", q: "Das ist der Mann, ___ neben mir wohnt.", o: ["den", "dem", "der"], a: 2, tip: "Er wohnt neben mir → Subjekt → Nominativ: der." },
    { lvl: "B", q: "Das ist die Frau, ___ ich geholfen habe.", o: ["der", "die", "denen"], a: 0, tip: "helfen + Dativ → feminin: der." },
    { lvl: "B", q: "Das ist das Buch, ___ ich gerade lese.", o: ["dass", "das", "den"], a: 1, tip: "Relativpronomen für das Buch: das (nicht dass)." },
    { lvl: "B", q: "Die Kollegen, mit ___ ich arbeite, sind sehr nett.", o: ["den", "die", "denen"], a: 2, tip: "mit + Dativ Plural → Relativpronomen: denen." },
    { lvl: "B", q: "Der Kurs, ___ ich besuche, ist sehr gut.", o: ["der", "den", "dem"], a: 1, tip: "Ich besuche den Kurs → Akkusativ: den." },
    { lvl: "B", q: "Die Stadt, in ___ ich wohne, ist klein.", o: ["die", "den", "der"], a: 2, tip: "Wo wohne ich? → in + Dativ, feminin: der." },
    { lvl: "B", q: "Kennst du die Frau, ___ Sohn in meiner Klasse ist?", o: ["deren", "dessen", "die"], a: 0, tip: "Besitz bei einer Frau: deren Sohn." },
    { lvl: "B", q: "Das ist mein Nachbar, ___ Auto immer vor meiner Garage steht.", o: ["deren", "dem", "dessen"], a: 2, tip: "Besitz bei einem Mann: dessen Auto." },
    { lvl: "B", q: "Ich hänge die Lampe über ___ Tisch.", o: ["den", "dem", "der"], a: 0, tip: "hängen = Wohin? → Akkusativ: über den Tisch." },
    { lvl: "B", q: "Das Auto steht vor ___ Haus.", o: ["das", "dem", "den"], a: 1, tip: "stehen = Wo? → Dativ, neutral: vor dem Haus." },
    { lvl: "B", q: "Stell das Fahrrad bitte hinter ___ Garage!", o: ["der", "den", "die"], a: 2, tip: "stellen = Wohin? → Akkusativ, feminin: hinter die Garage." },
    { lvl: "B", q: "Die Katze schläft unter ___ Bett.", o: ["das", "dem", "den"], a: 1, tip: "schlafen = Wo? → Dativ, neutral: unter dem Bett." },
    { lvl: "B", q: "Im Kurs setzt er sich neben ___ Kollegin.", o: ["seiner", "seinen", "seine"], a: 2, tip: "sich setzen = Wohin? → Akkusativ: neben seine Kollegin." },
    { lvl: "B", q: "Im Kurs sitzt er neben ___ Kollegin.", o: ["seiner", "seine", "seinen"], a: 0, tip: "sitzen = Wo? → Dativ, feminin: neben seiner Kollegin." },
    { lvl: "B", q: "Ich lerne Deutsch, ___ ich in Deutschland arbeiten möchte.", o: ["deshalb", "trotzdem", "weil"], a: 2, tip: "Grund + Verb am Ende → weil." },
    { lvl: "B", q: "Ich bin krank. ___ gehe ich heute nicht zur Arbeit.", o: ["Deshalb", "Weil", "Obwohl"], a: 0, tip: "Folge + Verb auf Position 2 → deshalb." },
    { lvl: "B", q: "___ ich müde bin, mache ich noch die Hausaufgaben.", o: ["Weil", "Obwohl", "Deshalb"], a: 1, tip: "Gegensatz + Verb am Ende → obwohl." },
    { lvl: "B", q: "Es regnet. ___ fahre ich mit dem Fahrrad zur Arbeit.", o: ["Obwohl", "Weil", "Trotzdem"], a: 2, tip: "Gegensatz + Verb auf Position 2 → trotzdem." },
    { lvl: "B", q: "Ich weiß nicht, ___ der Kurs morgen stattfindet.", o: ["dass", "ob", "wenn"], a: 1, tip: "Ja/Nein-Frage im Nebensatz → ob." },
    { lvl: "B", q: "Ich hoffe, ___ du bald wieder gesund wirst.", o: ["ob", "wenn", "dass"], a: 2, tip: "Nach hoffen folgt ein Inhalt → dass." },
    { lvl: "B", q: "Ich weiß, ___ du recht hast.", o: ["dass", "das", "ob"], a: 0, tip: "Konjunktion mit Doppel-s: dass + Verb am Ende." },
    { lvl: "B", q: "Er fragt, ___ wir morgen Zeit haben.", o: ["dass", "wenn", "ob"], a: 2, tip: "Indirekte Ja/Nein-Frage → ob." },
    { lvl: "B", q: "Immer ___ ich Zeit habe, rufe ich meine Mutter an.", o: ["wenn", "als", "ob"], a: 0, tip: "Wiederholung (immer) → wenn." },
    { lvl: "B", q: "___ ich nach Deutschland kam, konnte ich kein Deutsch.", o: ["Wenn", "Als", "Ob"], a: 1, tip: "Ein Mal in der Vergangenheit → als." },
    { lvl: "B", q: "Ich habe viel gelernt, ___ habe ich die Prüfung bestanden.", o: ["weil", "obwohl", "deshalb"], a: 2, tip: "Folge + Verb auf Position 2 → deshalb." },
    { lvl: "B", q: "Er ist müde, ___ er gut geschlafen hat.", o: ["weil", "obwohl", "deshalb"], a: 1, tip: "Gegensatz + Verb am Ende → obwohl." }
  ],

  satz: [
    /* ---------- A1–A2 ---------- */
    { lvl: "A", words: ["Ich", "komme", "aus der Ukraine"], end: ".", tip: "Aussagesatz: Das Verb steht auf Position 2." },
    { lvl: "A", words: ["Wo", "wohnen", "Sie"], end: "?", tip: "W-Frage: W-Wort, dann Verb, dann Subjekt." },
    { lvl: "A", words: ["Wie", "heißt", "du"], end: "?", tip: "W-Frage: W-Wort auf Position 1, Verb auf Position 2." },
    { lvl: "A", words: ["Kommst", "du", "morgen"], end: "?", tip: "Ja/Nein-Frage: Das Verb steht auf Position 1." },
    { lvl: "A", words: ["Morgen", "gehe", "ich", "zum Arzt"], end: ".", tip: "Zeit auf Position 1 → Verb auf 2, Subjekt danach." },
    { lvl: "A", words: ["Der Kurs", "fängt", "um neun Uhr", "an"], end: ".", tip: "Trennbares Verb: anfangen → Der Kurs fängt … an." },
    { lvl: "A", words: ["Ich", "kaufe", "im Supermarkt", "ein"], end: ".", tip: "Trennbares Verb: einkaufen → ich kaufe … ein." },
    { lvl: "A", words: ["Ich", "muss", "heute", "arbeiten"], end: ".", tip: "Modalverb auf Position 2, Infinitiv am Ende." },
    { lvl: "A", words: ["Kannst", "du", "mir", "helfen"], end: "?", tip: "Ja/Nein-Frage mit Modalverb: Infinitiv am Ende." },
    { lvl: "A", words: ["Gestern", "habe", "ich", "Fußball", "gespielt"], end: ".", tip: "Perfekt: haben auf Position 2, Partizip am Ende." },
    { lvl: "A", words: ["Wir", "sind", "nach Berlin", "gefahren"], end: ".", tip: "Perfekt: sein auf Position 2, Partizip am Ende." },
    { lvl: "A", words: ["Was", "machst", "du", "am Wochenende"], end: "?", tip: "W-Frage: W-Wort, Verb, Subjekt, dann der Rest." },
    { lvl: "A", words: ["Um wie viel Uhr", "beginnt", "der Kurs"], end: "?", tip: "W-Frage: Fragewort, dann Verb, dann Subjekt." },
    { lvl: "A", words: ["Morgen", "rufe", "ich", "dich", "an"], end: ".", tip: "Trennbares Verb: anrufen → rufe … an; Pronomen direkt nach dem Subjekt." },
    { lvl: "A", words: ["Haben", "Sie", "einen Termin"], end: "?", tip: "Ja/Nein-Frage: Das Verb steht auf Position 1." },
    { lvl: "A", words: ["Ich", "möchte", "einen Termin", "machen"], end: ".", tip: "möchten auf Position 2, Infinitiv am Ende." },
    { lvl: "A", words: ["Wann", "kommt", "der Bus"], end: "?", tip: "W-Frage: W-Wort, Verb, Subjekt." },
    { lvl: "A", words: ["Am Montag", "habe", "ich", "einen Termin"], end: ".", tip: "Zeit auf Position 1 → Verb auf 2, dann Subjekt." },
    { lvl: "A", words: ["Meine Frau", "arbeitet", "in einem Krankenhaus"], end: ".", tip: "Aussagesatz: Das Verb steht auf Position 2." },
    { lvl: "A", words: ["Wie viel", "kostet", "das Brot"], end: "?", tip: "W-Frage: Wie viel, dann Verb, dann Subjekt." },
    { lvl: "A", words: ["Ich", "bin", "um sechs Uhr", "aufgestanden"], end: ".", tip: "Perfekt: sein auf Position 2, Partizip am Ende." },
    { lvl: "A", words: ["Kann", "ich", "mit Karte", "bezahlen"], end: "?", tip: "Ja/Nein-Frage: Modalverb vorne, Infinitiv am Ende." },
    { lvl: "A", words: ["Darf", "ich", "hier", "parken"], end: "?", tip: "Ja/Nein-Frage: Modalverb vorne, Infinitiv am Ende." },
    { lvl: "A", words: ["Die Kinder", "spielen", "im Garten"], end: ".", tip: "Aussagesatz: Das Verb steht auf Position 2." },
    { lvl: "A", words: ["Bitte", "machen", "Sie", "das Fenster", "zu"], end: ".", tip: "Imperativ mit Sie: Verb, Sie, … , Vorsilbe zu am Ende." },
    { lvl: "A", words: ["Ich", "habe", "meinen Schlüssel", "vergessen"], end: ".", tip: "Perfekt: haben auf Position 2, Partizip am Ende." },
    { lvl: "A", words: ["Wo", "ist", "die Toilette"], end: "?", tip: "W-Frage: W-Wort, Verb, Subjekt." },
    { lvl: "A", words: ["Heute", "regnet", "es"], end: ".", tip: "Zeit auf Position 1 → Verb auf 2, Subjekt danach." },
    { lvl: "A", words: ["Mein Mann", "holt", "die Kinder", "von der Kita", "ab"], alt: [["Mein Mann", "holt", "von der Kita", "die Kinder", "ab"]], end: ".", tip: "Trennbares Verb: abholen → holt … ab." },
    { lvl: "A", words: ["Am Wochenende", "besuchen", "wir", "unsere Freunde"], end: ".", tip: "Zeit auf Position 1 → Verb auf 2, dann Subjekt." },
    { lvl: "A", words: ["Wohin", "fährt", "der Zug"], end: "?", tip: "W-Frage: W-Wort, Verb, Subjekt." },

    /* ---------- B1 ---------- */
    { lvl: "B", words: ["Ich bleibe zu Hause,", "weil", "ich", "krank", "bin"], end: ".", tip: "Nebensatz mit weil: Das Verb steht am Ende." },
    { lvl: "B", words: ["Ich hoffe,", "dass", "du", "bald", "gesund", "wirst"], end: ".", tip: "Nebensatz mit dass: Das Verb steht am Ende." },
    { lvl: "B", words: ["Weißt du,", "ob", "der Supermarkt", "geöffnet", "hat"], end: "?", tip: "Nebensatz mit ob: konjugiertes Verb ganz am Ende." },
    { lvl: "B", words: ["Ich komme mit,", "wenn", "ich", "Zeit", "habe"], end: ".", tip: "Nebensatz mit wenn: Das Verb steht am Ende." },
    { lvl: "B", words: ["Ich gehe zur Arbeit,", "obwohl", "ich", "müde", "bin"], end: ".", tip: "Nebensatz mit obwohl: Das Verb steht am Ende." },
    { lvl: "B", words: ["Das ist der Mann,", "der", "neben mir", "wohnt"], end: ".", tip: "Relativsatz: Relativpronomen vorne, Verb am Ende." },
    { lvl: "B", words: ["Das ist die Wohnung,", "die", "ich", "gemietet", "habe"], end: ".", tip: "Relativsatz: Partizip, dann Hilfsverb ganz am Ende." },
    { lvl: "B", words: ["Das ist die Kollegin,", "mit der", "ich", "zusammenarbeite"], end: ".", tip: "Relativsatz mit Präposition: mit der … Verb am Ende." },
    { lvl: "B", words: ["Ich lerne Deutsch,", "um", "in Deutschland", "zu arbeiten"], end: ".", tip: "um … zu: zu + Infinitiv steht am Ende." },
    { lvl: "B", words: ["Ich habe vergessen,", "die Rechnung", "zu bezahlen"], end: ".", tip: "Infinitiv mit zu steht am Ende." },
    { lvl: "B", words: ["Es ist wichtig,", "pünktlich", "zu sein"], end: ".", tip: "Infinitiv mit zu steht am Ende." },
    { lvl: "B", words: ["Die Wohnung", "wird", "morgen", "renoviert"], end: ".", tip: "Passiv: werden auf Position 2, Partizip am Ende." },
    { lvl: "B", words: ["Der Brief", "wurde", "gestern", "abgeschickt"], end: ".", tip: "Passiv Präteritum: wurde auf Position 2, Partizip am Ende." },
    { lvl: "B", words: ["Hier", "darf", "nicht", "geraucht", "werden"], end: ".", tip: "Passiv mit Modalverb: Partizip + werden am Ende." },
    { lvl: "B", words: ["Das Formular", "muss", "bis Freitag", "abgegeben", "werden"], end: ".", tip: "Passiv mit Modalverb: Partizip + werden am Ende." },
    { lvl: "B", words: ["Könnten", "Sie", "bitte", "das Fenster", "schließen"], alt: [["Könnten", "Sie", "das Fenster", "bitte", "schließen"]], end: "?", tip: "Höfliche Bitte: Konjunktiv II vorne, Infinitiv am Ende." },
    { lvl: "B", words: ["Würden", "Sie", "mich", "zurückrufen"], end: "?", tip: "Höfliche Bitte: Würden Sie … + Infinitiv am Ende." },
    { lvl: "B", words: ["Wenn ich du wäre,", "würde", "ich", "zum Arzt", "gehen"], end: ".", tip: "Nach dem Nebensatz kommt sofort das Verb: würde ich …" },
    { lvl: "B", words: ["Ich würde gern wissen,", "wann", "der Kurs", "beginnt"], end: ".", tip: "Indirekte W-Frage: Das Verb steht am Ende." },
    { lvl: "B", words: ["Ich weiß nicht,", "wo", "der Bahnhof", "ist"], end: ".", tip: "Indirekte W-Frage: Das Verb steht am Ende." },
    { lvl: "B", words: ["Können Sie mir sagen,", "wo", "das Bürgeramt", "ist"], end: "?", tip: "Höfliche indirekte Frage: Das Verb steht am Ende." },
    { lvl: "B", words: ["Kannst du mir sagen,", "wie spät", "es", "ist"], end: "?", tip: "Indirekte W-Frage: Das Verb steht am Ende." },
    { lvl: "B", words: ["Ich habe keine Zeit,", "weil", "ich", "arbeiten", "muss"], end: ".", tip: "Nebensatz mit Modalverb: Infinitiv, dann Modalverb am Ende." },
    { lvl: "B", words: ["Ich freue mich,", "dass", "du", "gekommen", "bist"], end: ".", tip: "Nebensatz im Perfekt: Partizip, dann Hilfsverb am Ende." },
    { lvl: "B", words: ["Er hat gesagt,", "dass", "er", "später", "kommt"], end: ".", tip: "Nebensatz mit dass: Das Verb steht am Ende." },
    { lvl: "B", words: ["Der Arzt hat gesagt,", "dass", "ich", "viel", "trinken", "soll"], end: ".", tip: "Nebensatz mit Modalverb: Infinitiv, dann Modalverb am Ende." },
    { lvl: "B", words: ["Ich rufe an,", "weil", "ich", "meinen Termin", "absagen", "muss"], end: ".", tip: "Nebensatz mit Modalverb: Infinitiv, dann Modalverb am Ende." },
    { lvl: "B", words: ["Ich bin nicht sicher,", "ob", "ich", "morgen", "kommen", "kann"], end: ".", tip: "Nebensatz mit ob: Infinitiv, dann Modalverb am Ende." },
    { lvl: "B", words: ["Als", "ich", "nach Deutschland", "kam,", "konnte", "ich", "kein Deutsch"], end: ".", tip: "Nebensatz zuerst → danach steht sofort das Verb: konnte ich." },
    { lvl: "B", words: ["Nachdem", "ich", "gegessen", "hatte,", "ging", "ich", "spazieren"], end: ".", tip: "Nebensatz zuerst → Verb am Ende, dann Verb – Verb." },
    { lvl: "B", words: ["Obwohl", "es", "regnet,", "gehen", "wir", "spazieren"], end: ".", tip: "Nebensatz zuerst → danach Verb vor dem Subjekt." },
    { lvl: "B", words: ["Ich hätte gern", "einen Termin", "beim Zahnarzt"], alt: [["Ich hätte gern", "beim Zahnarzt", "einen Termin"]], end: ".", tip: "Höflicher Wunsch mit Konjunktiv II: Ich hätte gern …" }
  ],

  wort: [
    /* ---------- A1–A2 ---------- */
    { lvl: "A", q: "Wo bekommt man Medikamente?", o: ["in der Bäckerei", "im Rathaus", "in der Apotheke"], a: 2, tip: "Medikamente gibt es in der Apotheke." },
    { lvl: "A", q: "Das Gegenteil von „groß“ ist …", o: ["klein", "lang", "alt"], a: 0, tip: "groß ↔ klein." },
    { lvl: "A", q: "Das Gegenteil von „billig“ ist …", o: ["schnell", "neu", "teuer"], a: 2, tip: "billig ↔ teuer: Es kostet viel Geld." },
    { lvl: "A", q: "Das Gegenteil von „früh“ ist …", o: ["spät", "schnell", "kurz"], a: 0, tip: "früh ↔ spät." },
    { lvl: "A", q: "Das Gegenteil von „offen“ ist …", o: ["leer", "geschlossen", "kalt"], a: 1, tip: "offen ↔ geschlossen (oder: zu)." },
    { lvl: "A", q: "Das Gegenteil von „gesund“ ist …", o: ["müde", "traurig", "krank"], a: 2, tip: "gesund ↔ krank." },
    { lvl: "A", q: "Was sagt man am Morgen?", o: ["„Gute Nacht!“", "„Guten Morgen!“", "„Guten Abend!“"], a: 1, tip: "Am Morgen sagt man: Guten Morgen!" },
    { lvl: "A", q: "Sie möchten im Café bezahlen. Was sagen Sie?", o: ["„Die Speisekarte, bitte.“", "„Guten Appetit!“", "„Die Rechnung, bitte.“"], a: 2, tip: "Zum Bezahlen fragt man nach der Rechnung." },
    { lvl: "A", q: "Was passt? Einen Termin …", o: ["vereinbaren", "kochen", "waschen"], a: 0, tip: "Feste Verbindung: einen Termin vereinbaren." },
    { lvl: "A", q: "Sie sind krank. Was braucht Ihr Arbeitgeber vom Arzt?", o: ["ein Kochrezept", "eine Quittung", "eine Krankschreibung"], a: 2, tip: "Der Arzt schreibt Sie krank: die Krankschreibung." },
    { lvl: "A", q: "Wo kauft man Brot und Brötchen?", o: ["beim Bäcker", "beim Friseur", "beim Arzt"], a: 0, tip: "Der Bäcker backt und verkauft Brot." },
    { lvl: "A", q: "Sie haben etwas nicht verstanden. Was sagen Sie?", o: ["„Bitte schön.“", "„Wie bitte?“", "„Gern geschehen.“"], a: 1, tip: "„Wie bitte?“ = Bitte noch einmal sagen." },
    { lvl: "A", q: "Jemand sagt „Vielen Dank!“. Was antworten Sie?", o: ["„Entschuldigung.“", "„Gute Besserung.“", "„Gern geschehen.“"], a: 2, tip: "Auf Danke antwortet man: Gern geschehen." },
    { lvl: "A", q: "Ihre Kollegin ist krank. Was sagen Sie?", o: ["„Guten Appetit!“", "„Gute Besserung!“", "„Herzlichen Glückwunsch!“"], a: 1, tip: "Kranken Menschen wünscht man gute Besserung." },
    { lvl: "A", q: "Ihr Nachbar hat Geburtstag. Was sagen Sie?", o: ["„Gute Besserung!“", "„Gute Reise!“", "„Herzlichen Glückwunsch!“"], a: 2, tip: "Zum Geburtstag sagt man: Herzlichen Glückwunsch!" },
    { lvl: "A", q: "Was sagt man vor dem Essen?", o: ["„Guten Appetit!“", "„Gute Besserung!“", "„Viel Glück!“"], a: 0, tip: "Vor dem Essen wünscht man guten Appetit." },
    { lvl: "A", q: "Was ist ein Möbelstück?", o: ["der Apfel", "der Bus", "der Schrank"], a: 2, tip: "Schrank, Tisch, Bett und Stuhl sind Möbel." },
    { lvl: "A", q: "Wo arbeitet eine Lehrerin?", o: ["in der Schule", "in der Apotheke", "in der Bank"], a: 0, tip: "Lehrerinnen unterrichten in der Schule." },
    { lvl: "A", q: "Welcher Tag kommt nach Montag?", o: ["Mittwoch", "Dienstag", "Sonntag"], a: 1, tip: "Montag, Dienstag, Mittwoch …" },
    { lvl: "A", q: "Wie viele Minuten hat eine Stunde?", o: ["30", "100", "60"], a: 2, tip: "Eine Stunde hat 60 Minuten." },
    { lvl: "A", q: "Wohin bringen Eltern ihre kleinen Kinder (1–6 Jahre)?", o: ["in die Universität", "in die Kita", "ins Büro"], a: 1, tip: "Kleine Kinder gehen in die Kita." },
    { lvl: "A", q: "Was macht man in der Küche?", o: ["duschen", "schlafen", "kochen"], a: 2, tip: "In der Küche kocht man." },
    { lvl: "A", q: "Sie kommen zu spät zum Kurs. Was sagen Sie?", o: ["„Entschuldigung, ich bin zu spät.“", "„Gute Nacht!“", "„Herzlich willkommen!“"], a: 0, tip: "Wenn man zu spät kommt, entschuldigt man sich." },
    { lvl: "A", q: "Im Winter ist es kalt. Was ziehen Sie an?", o: ["eine Badehose", "Sandalen", "eine warme Jacke"], a: 2, tip: "Bei Kälte braucht man warme Kleidung." },
    { lvl: "A", q: "Es regnet. Was brauchen Sie?", o: ["einen Regenschirm", "eine Sonnenbrille", "einen Ball"], a: 0, tip: "Gegen Regen hilft ein Regenschirm." },
    { lvl: "A", q: "Wo kauft man eine Fahrkarte für den Bus?", o: ["in der Apotheke", "am Automaten", "beim Friseur"], a: 1, tip: "Fahrkarten gibt es am Automaten oder in der App." },
    { lvl: "A", q: "Ich habe Hunger. Ich möchte …", o: ["schlafen", "telefonieren", "etwas essen"], a: 2, tip: "Hunger → essen, Durst → trinken." },
    { lvl: "A", q: "Sie suchen eine Wohnung. Wo lesen Sie Angebote?", o: ["auf der Speisekarte", "in Wohnungsanzeigen", "im Fahrplan"], a: 1, tip: "Wohnungen findet man in Anzeigen, z. B. im Internet." },
    { lvl: "A", q: "Sie rufen beim Arzt an. Was sagen Sie zuerst?", o: ["„Tschüss, bis bald!“", "„Gute Besserung!“", "„Guten Tag, hier ist …“"], a: 2, tip: "Am Telefon grüßt man und sagt seinen Namen." },
    { lvl: "A", q: "Was bedeutet „Feierabend“?", o: ["Die Arbeit ist für heute vorbei.", "Man hat Geburtstag.", "Man feiert eine Party."], a: 0, tip: "Feierabend = Ende der Arbeit am Tag." },
    { lvl: "A", q: "Ein anderes Wort für „Doktor“ ist …", o: ["Lehrer", "Koch", "Arzt"], a: 2, tip: "Doktor = Arzt." },
    { lvl: "A", q: "Was ist Gemüse?", o: ["die Karotte", "der Apfel", "die Banane"], a: 0, tip: "Apfel und Banane sind Obst, die Karotte ist Gemüse." },
    { lvl: "A", q: "Wie fragt man nach dem Preis?", o: ["„Wie spät ist es?“", "„Was kostet das?“", "„Wie geht es Ihnen?“"], a: 1, tip: "Nach dem Preis fragt man: Was kostet das?" },
    { lvl: "A", q: "Wie fragt man nach der Uhrzeit?", o: ["„Wie alt bist du?“", "„Wie lange dauert das?“", "„Wie spät ist es?“"], a: 2, tip: "Uhrzeit: Wie spät ist es? / Wie viel Uhr ist es?" },
    { lvl: "A", q: "Sie kennen ein Wort nicht. Was fragen Sie?", o: ["„Wo ist das?“", "„Was bedeutet das?“", "„Wer ist das?“"], a: 1, tip: "Nach der Bedeutung fragt man: Was bedeutet das?" },
    { lvl: "A", q: "Was braucht man für einen Brief?", o: ["eine Fahrkarte", "eine Speisekarte", "eine Briefmarke"], a: 2, tip: "Auf einen Brief klebt man eine Briefmarke." },
    { lvl: "A", q: "Sie sind umgezogen. Wo melden Sie die neue Adresse an?", o: ["beim Bürgeramt", "bei der Bank", "in der Apotheke"], a: 0, tip: "Eine neue Adresse meldet man beim Bürgeramt an." },

    /* ---------- B1 ---------- */
    { lvl: "B", q: "Sie können nicht zum Termin kommen. Was schreiben Sie?", o: ["„Leider muss ich den Termin ausmachen.“", "„Leider muss ich den Termin abholen.“", "„Leider muss ich den Termin absagen.“"], a: 2, tip: "absagen = nicht kommen; ausmachen = vereinbaren." },
    { lvl: "B", q: "Was bedeutet „einen Termin verschieben“?", o: ["den Termin auf eine andere Zeit legen", "den Termin ganz absagen", "pünktlich zum Termin kommen"], a: 0, tip: "verschieben = später oder früher machen." },
    { lvl: "B", q: "Sie schreiben an eine Behörde und kennen keinen Namen. Wie beginnen Sie?", o: ["„Hallo Leute,“", "„Sehr geehrte Damen und Herren,“", "„Liebe Grüße,“"], a: 1, tip: "Formeller Brief ohne Namen: Sehr geehrte Damen und Herren." },
    { lvl: "B", q: "Wie beenden Sie einen formellen Brief?", o: ["„Bis bald!“", "„Tschüss“", "„Mit freundlichen Grüßen“"], a: 2, tip: "Formeller Gruß am Ende: Mit freundlichen Grüßen." },
    { lvl: "B", q: "Im Brief vom Amt steht „Frist: 15. März“. Was bedeutet das?", o: ["Am 15. März habe ich frei.", "Bis zum 15. März muss ich reagieren.", "Am 15. März bekomme ich Geld."], a: 1, tip: "Eine Frist ist der letzte Tag für etwas." },
    { lvl: "B", q: "Was schicken Sie mit einer Bewerbung mit?", o: ["den Mietvertrag", "die Steuererklärung", "den Lebenslauf"], a: 2, tip: "Zur Bewerbung gehören Anschreiben, Lebenslauf und Zeugnisse." },
    { lvl: "B", q: "Was ist die „Warmmiete“?", o: ["Miete mit Heizung und Nebenkosten", "Miete nur für den Winter", "Miete ohne Nebenkosten"], a: 0, tip: "Kaltmiete + Nebenkosten (mit Heizung) = Warmmiete." },
    { lvl: "B", q: "Was zahlt man oft beim Einzug als Sicherheit für den Vermieter?", o: ["die Rente", "das Kindergeld", "die Kaution"], a: 2, tip: "Die Kaution bekommt man beim Auszug normalerweise zurück." },
    { lvl: "B", q: "Was bedeutet „Ich bin krankgeschrieben“?", o: ["Der Arzt sagt, ich darf nicht arbeiten.", "Ich habe einen Brief geschrieben.", "Ich bin wieder gesund."], a: 0, tip: "Krankgeschrieben = mit Bescheinigung vom Arzt zu Hause." },
    { lvl: "B", q: "Die Ärztin fragt: „Seit wann haben Sie die Beschwerden?“ Was antworten Sie?", o: ["„Um drei Uhr.“", "„Seit drei Tagen.“", "„In drei Tagen.“"], a: 1, tip: "Seit wann? → seit + Zeitraum bis heute." },
    { lvl: "B", q: "Sie möchten höflich widersprechen. Was sagen Sie?", o: ["„Das ist doch Quatsch!“", "„Sie haben keine Ahnung.“", "„Da bin ich anderer Meinung.“"], a: 2, tip: "Höflich widersprechen: Da bin ich anderer Meinung." },
    { lvl: "B", q: "Sie möchten einen Vorschlag machen. Was passt?", o: ["„Wir fahren am Samstag, fertig!“", "„Wie wäre es, wenn wir am Samstag fahren?“", "„Das ist mir egal.“"], a: 1, tip: "Vorschlag: Wie wäre es, wenn …?" },
    { lvl: "B", q: "Was bedeutet „Ich stimme Ihnen zu“?", o: ["Ich habe eine andere Meinung.", "Ich verstehe Sie nicht.", "Ich habe die gleiche Meinung."], a: 2, tip: "zustimmen = einverstanden sein." },
    { lvl: "B", q: "Ein anderes Wort für „beginnen“ ist …", o: ["anfangen", "aufhören", "aufstehen"], a: 0, tip: "beginnen = anfangen; das Gegenteil ist aufhören." },
    { lvl: "B", q: "Das Gegenteil von „in eine Wohnung einziehen“ ist …", o: ["anziehen", "umziehen", "ausziehen"], a: 2, tip: "einziehen ↔ ausziehen; umziehen = die Wohnung wechseln." },
    { lvl: "B", q: "Das Gegenteil von „Vorteil“ ist …", o: ["Nachteil", "Vorurteil", "Vorschlag"], a: 0, tip: "Vorteil ↔ Nachteil." },
    { lvl: "B", q: "Was bedeutet „ein unbefristeter Arbeitsvertrag“?", o: ["Der Vertrag ist ungültig.", "Der Vertrag hat kein Enddatum.", "Der Vertrag gilt nur drei Monate."], a: 1, tip: "unbefristet = ohne Ende; befristet = mit Enddatum." },
    { lvl: "B", q: "Was passiert bei einem Vorstellungsgespräch?", o: ["Man stellt Möbel in die Wohnung.", "Man stellt einen Antrag beim Amt.", "Man stellt sich beim Arbeitgeber vor."], a: 2, tip: "Im Vorstellungsgespräch lernt der Arbeitgeber Sie kennen." },
    { lvl: "B", q: "Was bedeutet „Bitte geben Sie mir Bescheid“?", o: ["Bitte besuchen Sie mich.", "Bitte informieren Sie mich.", "Bitte bezahlen Sie mich."], a: 1, tip: "Bescheid geben = jemanden informieren." },
    { lvl: "B", q: "Die Heizung in Ihrer Mietwohnung ist kaputt. Wen informieren Sie?", o: ["die Krankenkasse", "das Finanzamt", "den Vermieter"], a: 2, tip: "Für Reparaturen in der Wohnung ist der Vermieter zuständig." },
    { lvl: "B", q: "Ihr Hausarzt gibt Ihnen eine Überweisung. Was bedeutet das?", o: ["Sie sollen zu einem Facharzt gehen.", "Sie müssen eine Rechnung bezahlen.", "Sie bekommen Medikamente."], a: 0, tip: "Mit der Überweisung schickt der Hausarzt Sie zum Facharzt." },
    { lvl: "B", q: "Wo heiratet man in Deutschland offiziell?", o: ["beim Jobcenter", "beim Finanzamt", "beim Standesamt"], a: 2, tip: "Das Standesamt ist für Ehe, Geburt und Tod zuständig." },
    { lvl: "B", q: "Wofür ist das Finanzamt zuständig?", o: ["für Steuern", "für Reisepässe", "für Arbeitsstellen"], a: 0, tip: "Finanzamt = Steuern." },
    { lvl: "B", q: "„Könnten Sie das bitte wiederholen?“ bedeutet:", o: ["Schreiben Sie das bitte auf.", "Sagen Sie das bitte noch einmal.", "Sprechen Sie bitte leiser."], a: 1, tip: "wiederholen = noch einmal sagen." },
    { lvl: "B", q: "Was passt? Einen Antrag …", o: ["legen", "setzen", "stellen"], a: 2, tip: "Feste Verbindung: einen Antrag stellen." },
    { lvl: "B", q: "Was passt? Eine Entscheidung …", o: ["stellen", "treffen", "geben"], a: 1, tip: "Feste Verbindung: eine Entscheidung treffen." },
    { lvl: "B", q: "Was ist die „Probezeit“?", o: ["die Zeit vor einer Prüfung", "die Pause bei der Arbeit", "die erste Zeit in einer neuen Stelle"], a: 2, tip: "In der Probezeit testen sich Firma und Mitarbeiter." },
    { lvl: "B", q: "Was bedeutet „Schichtarbeit“?", o: ["Man arbeitet zu wechselnden Zeiten, auch nachts.", "Man arbeitet nur am Wochenende.", "Man arbeitet immer von zu Hause."], a: 0, tip: "Schichten: Frühschicht, Spätschicht, Nachtschicht." },
    { lvl: "B", q: "Sie möchten in einer Besprechung etwas sagen. Was ist höflich?", o: ["„Seien Sie still!“", "„Jetzt rede ich!“", "„Darf ich kurz etwas sagen?“"], a: 2, tip: "Höflich das Wort nehmen: Darf ich kurz etwas sagen?" },
    { lvl: "B", q: "Was ist ein „Vorurteil“?", o: ["eine feste Meinung, ohne die Person zu kennen", "ein Urteil vom Gericht", "ein guter Vorschlag"], a: 0, tip: "Ein Vorurteil hat man schon vorher, ohne Erfahrung." },
    { lvl: "B", q: "Was bedeutet „etwas erledigen“?", o: ["etwas vergessen", "etwas fertig machen", "etwas kaputt machen"], a: 1, tip: "erledigen = eine Aufgabe zu Ende bringen." },
    { lvl: "B", q: "Was ist ein „Ehrenamt“?", o: ["ein Büro im Rathaus", "ein Amt nur für Ehepaare", "eine Arbeit ohne Bezahlung für andere"], a: 2, tip: "Ehrenamtlich arbeitet man freiwillig und ohne Lohn." },
    { lvl: "B", q: "Was gehört zu den „Nebenkosten“ einer Wohnung?", o: ["Essen und Kleidung", "Wasser, Müll und Hausreinigung", "Bus- und Bahntickets"], a: 1, tip: "Nebenkosten sind Kosten für das Haus neben der Miete." },
    { lvl: "B", q: "Ein Brief vom Amt ist nicht bei Ihnen angekommen. Was sagen Sie?", o: ["„Das Schreiben habe ich leider nicht enthalten.“", "„Das Schreiben habe ich leider nicht behalten.“", "„Das Schreiben habe ich leider nicht erhalten.“"], a: 2, tip: "erhalten = bekommen; enthalten und behalten passen hier nicht." },
    { lvl: "B", q: "Ihr Chef sagt: „Sie sind sehr zuverlässig.“ Was bedeutet das?", o: ["Man kann sich auf Sie verlassen.", "Sie sind oft krank.", "Sie arbeiten sehr schnell."], a: 0, tip: "zuverlässig = man kann sich auf jemanden verlassen." },
    { lvl: "B", q: "Im Bewerbungsgespräch: „Was sind Ihre Stärken?“ Was ist eine gute Antwort?", o: ["„Das weiß ich nicht.“", "„Ich komme oft zu spät.“", "„Ich bin zuverlässig und arbeite gern im Team.“"], a: 2, tip: "Nennen Sie positive Eigenschaften mit Bezug zur Arbeit." },
    { lvl: "B", q: "Was ist die „Kündigungsfrist“?", o: ["die Zeit zwischen Kündigung und Vertragsende", "der erste Arbeitstag", "das Geld nach der Kündigung"], a: 0, tip: "Nach der Kündigung läuft der Vertrag noch bis zum Ende der Frist." }
  ]
};
