/* Local website guide: prepared multilingual answers, no remote chat service. */
(()=>{
 const languages={de:'Deutsch',ar:'العربية',fa:'فارسی',ru:'Русский',tr:'Türkçe',zh:'中文',en:'English',it:'Italiano',es:'Español'};
 let lang='de',turns=[],opened=false;
 const root=document.createElement('aside');root.id='site-helper';root.setAttribute('aria-label','Website-Hilfe');document.body.append(root);
 const norm=s=>s.toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss');
 const keywords=[
 ['niveau','level','start','anfang','anfanger','lernweg','beginner','beginnen','anmeldung','registr','kosten','account','login','уров','начать','регистра','seviye','kayıt','مستوى','تسجيل','سطح','ثبت','级别','注册','livello','nivel','empezar'],
 ['blattern','weiter','zuruck','navigation','bedienen','konfigur','einstell','navigate','turn page','навига','листать','настро','gezin','sayfa','تقليب','التنقل','صفحه','翻页','设置','sfoglia','navegar','paginas'],
 ['ubung','aufgabe','runde','schwier','exercise','practice','easier','harder','упраж','задан','сложн','alıştır','zorluk','تمرين','تمارين','صعوبة','تمرین','سخت','练习','难度','eserciz','diffic','ejercicio'],
 ['wort','grammatik','konjug','praposition','vocab','grammar','noun','verb','adjektiv','слова','словар','граммат','спряж','kelime','dil bilgisi','مفردات','قواعد','تصريف','واژ','دستور','صرف','词汇','语法','变位','lessico','grammatica','vocabulario'],
 ['ubersetz','translation','translate','language','sprache','перевод','язык','çeviri','dil','ترجم','لغة','ترجمه','زبان','翻译','语言','traduz','lingua','traducc','idioma'],
 ['audio','horen','laut','ton','gerausch','sound','listen','volume','звук','слуш','ses','dinle','صوت','سماع','صدا','شنیدن','音频','声音','ascolt','suono','sonido','escuchar'],
 ['pdf','download','herunterlad','speicher','drucken','скач','сохран','indir','تنزيل','تحميل','دانلود','ذخیره','下载','保存','scaric','salvar','descarg','guardar'],
 ['prufung','dtz','dtb','lid','leben in deutschland','orientierung','exam','test','экзам','sınav','امتحان','اختبار','آزمون','考试','esame','examen'],
 ['video','youtube','film','видео','فيديو','ویدیو','视频'],
 ['kontakt','contact','mail','dennis','lehrer','teacher','human','учител','связ','почт','iletişim','öğretmen','تواصل','بريد','معلم','تماس','ایمیل','联系','邮件','contatt','correo']
 ];
 function classify(input){const q=norm(input).trim();const m=q.match(/\b(a1|a2|b1|b2)\b/);if(/^(hallo|hi|hello|hey|guten tag|привет|здравствуйте|merhaba|مرحبا|سلام|你好|ciao|hola)[! .]*$/.test(q))return {topic:'hello'};let hits=[];keywords.forEach((words,i)=>{let score=words.reduce((n,w)=>n+(q.includes(norm(w))?1:0),0);if(q.includes(norm(siteHelpText[lang].titles[i])))score+=5;if(score)hits.push({topic:i,score});});hits.sort((a,b)=>b.score-a.score);return hits.length?{...hits[0],level:m?.[1].toUpperCase()}:m?{topic:0,level:m[1].toUpperCase()}:{topic:'fallback'};}
 const tx=()=>siteHelpText[lang];
 function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
 function links(topic,chosen){if(topic===0)return (chosen?[chosen]:['A1','A2','B1','B2']).map(k=>[k,`#buch/${k}`]);const l=typeof lessons!=='undefined'?lessons.find(x=>location.hash.split('/')[1]===x.id):null;const dest=l?`#wortschatz/${l.id}/0`:'#themen';return {1:[[tx().ui[9], '#themen']],2:[[tx().ui[9],l?`#wortschatz/${l.id}/3`:'#themen']],3:[[tx().ui[9],dest]],4:[[tx().ui[9],l&&['A1','A2'].includes(l.level)?`#wortschatz/${l.id}/0`:'#buch/A1']],5:[[tx().ui[9],l?`#lektion/${l.id}/3`:'#lektion/ankommen/3']],6:[[tx().ui[9],l?`#wortschatz/${l.id}/0`:'#themen']],7:[['DTZ / DTB B2','#pruefung'],['Leben in Deutschland','#orientierungskurs']],8:[[tx().ui[9],'#videos']],9:[['E-Mail schreiben','mailto:dennis.prudnikau@gmail.com'],['WhatsApp schreiben','https://wa.me/491738775907']]}[topic]||[];}
 function message(turn){const wrap=node('div',undefined,'help-message '+(turn.user?'help-user':'help-bot'));wrap.dir=turn.user?'auto':(['ar','fa'].includes(lang)?'rtl':'ltr');if(turn.user)wrap.append(node('p',turn.user));else if(turn.topic==='learning'){wrap.lang='de';wrap.dir='ltr';for(const p of turn.paragraphs)wrap.append(node('p',p));const actions=node('div',undefined,'help-links');for(const [label,url] of turn.actions){const a=node('a',label);a.href=url;a.onclick=()=>setOpen(false);actions.append(a);}wrap.append(actions);}else{const t=turn.topic;const text=t==='hello'?tx().ui[6]:t==='fallback'?tx().ui[8]:tx().answers[t];wrap.append(node('p',text));const actions=node('div',undefined,'help-links');for(const [label,url] of links(t,turn.level)){const a=node('a',label);a.href=url;if(url[0]==='#')a.onclick=()=>setOpen(false);actions.append(a);}wrap.append(actions);if(t==='fallback'){const choices=node('div',undefined,'help-topics help-suggestions');const suggestions=lang==='de'?[['Wie lerne ich am besten?',null],['Welches Niveau passt zu mir?',0],['Wo finde ich Wortschatz und Grammatik?',3],['Wie lade ich eine PDF herunter?',6],['Wie schalte ich den Ton ein?',5]]:[0,3,6,5].map(i=>[tx().titles[i],i]);for(const [label,topic] of suggestions){const b=node('button',label);b.type='button';b.onclick=()=>ask(label,topic===null?undefined:{topic});choices.append(b);}wrap.append(choices);}}return wrap;}
 function ask(text,result){const previous=[...turns].reverse().find(t=>!t.user);turns.push({user:text},result||findLearningHelp(text,previous,lang)||classify(text));turns=turns.slice(-24);renderChat();root.querySelector('#help-input').focus();}
 function renderChat(){const pane=root.querySelector('#help-panel');if(!pane)return;const t=tx();pane.lang=lang;pane.dir=['ar','fa'].includes(lang)?'rtl':'ltr';pane.replaceChildren();const header=node('div',undefined,'help-head');header.append(node('h2',t.ui[0]));const close=node('button','×','help-close');close.type='button';close.setAttribute('aria-label',t.ui[2]);close.onclick=()=>setOpen(false);header.append(close);pane.append(header);
 const controls=node('div',undefined,'help-toolbar');const label=node('label',t.ui[1]);label.htmlFor='help-language';const select=node('select');select.id='help-language';for(const [code,name] of Object.entries(languages)){const o=node('option',name);o.value=code;o.selected=lang===code;select.append(o);}select.onchange=()=>{lang=select.value;renderChat();root.querySelector('#help-language').focus();};const reset=node('button',t.ui[5]);reset.type='button';reset.onclick=()=>{turns=[];renderChat();root.querySelector('#help-input').focus();};controls.append(label,select,reset);pane.append(controls);if(!turns.length)pane.append(node('p',t.ui[7],'help-note'));
 const log=node('div',undefined,'help-log');log.id='help-log';log.setAttribute('role','log');log.setAttribute('aria-live','polite');log.setAttribute('aria-label',t.ui[0]);log.append(message({topic:'hello'}));turns.forEach(turn=>log.append(message(turn)));pane.append(log);
 const topics=node('div',undefined,'help-topics');t.titles.forEach((title,i)=>{const b=node('button',title);b.type='button';b.onclick=()=>ask(title,{topic:i});topics.append(b);});if(turns.length){const det=node('details',undefined,'help-topics-wrap');det.append(node('summary',t.titles.length?('☰ '+(t.ui[10]||'Themen')):'Themen'),topics);pane.append(det);}else pane.append(topics);
 const form=node('form');form.className='help-form';const inputLabel=node('label',t.ui[3]);inputLabel.htmlFor='help-input';const input=node('input');input.id='help-input';input.type='text';input.maxLength=500;input.autocomplete='off';input.placeholder=t.ui[3];input.required=true;const send=node('button',t.ui[4]);send.type='submit';form.append(inputLabel,input,send);form.onsubmit=e=>{e.preventDefault();const q=input.value.trim();if(q)ask(q);};pane.append(form);requestAnimationFrame(()=>{const users=log.querySelectorAll('.help-user');const last=users[users.length-1];if(last){log.scrollTop=Math.max(0,last.offsetTop-log.offsetTop-8);const bot=last.nextElementSibling;if(bot)bot.classList.add('help-new');}else log.scrollTop=0;});
 }
 function setOpen(value){opened=value;root.querySelector('#help-panel').hidden=!value;const launcher=root.querySelector('#help-launch');launcher.setAttribute('aria-expanded',String(value));if(value){renderChat();root.querySelector('#help-input').focus();}else launcher.focus();}
 const launcher=node('button','Hilfe / Help','help-launch');launcher.type='button';launcher.id='help-launch';launcher.setAttribute('aria-controls','help-panel');launcher.setAttribute('aria-expanded','false');launcher.onclick=()=>setOpen(!opened);const panel=node('section');panel.id='help-panel';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Website-Hilfe / Website help');panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);}});root.append(panel,launcher);
 document.querySelectorAll('[data-open-help]').forEach(b=>b.onclick=()=>setOpen(true));
})();
