function exampleAudioSrc(id,lang){return lang==='de'?`audio/aufnahmen/${id}-de.wav`:`audio/${id}-${lang}.mp3`;}
function exampleAudioLabel(lang){return lang==='de'?'Originalaufnahme · Deutsch':'Künstlich erzeugte Stimme · Übersetzung';}
function audioPanel(id){const isLow=['A1','A2'].includes(lessons.find(l=>l.id===id)?.level);if(!isLow)language='de';const allowed=isLow?Object.fromEntries(Object.entries(languages).filter(([k])=>['de','ar','fa','ru','uk','tr','zh','en','it','es'].includes(k))):{de:'Deutsch'};return `<div class="listen-box"><h3>Hören & nachsprechen</h3><label for="audio-language" class="muted">Sprache für Beispiel und Erklärung</label><select id="audio-language">${Object.entries(allowed).map(([k,v])=>`<option value="${k}" ${language===k?'selected':''}>${k==='de'?'Deutsch':v}</option>`).join('')}</select><p class="translation-copy" id="spoken-text">${esc(spokenExamples[id][language])}</p><audio id="example-audio" controls controlslist="nodownload" preload="none" src="${exampleAudioSrc(id,language)}">Dein Browser unterstützt die Audiowiedergabe nicht.</audio><div class="listen-row"><label class="muted" for="audio-rate">Tempo</label><select id="audio-rate" style="width:auto"><option value="1">Normal</option><option value="0.8">Langsam</option></select><button class="btn secondary" id="audio-german" type="button">Deutsch hören</button></div><p class="tts-status" id="audio-status" role="status">${exampleAudioLabel(language)}</p></div>`;}
function enhanceLesson(){const id=location.hash.split('/')[1],l=lessons.find(x=>x.id===id);if(!l||!location.hash.startsWith('#lektion/'))return;const r=currentPractice(id);const text=document.querySelector('.paper .context');if(text&&text.parentElement.querySelector('#book-language'))text.textContent=r.text;
const paper=[...document.querySelectorAll('.paper')].find(p=>p.querySelector('.rule')||p.querySelector('#book-language'));if(paper&&!paper.querySelector('.listen-box')){let box=document.createElement('div');box.innerHTML=audioPanel(id);paper.append(box);let select=document.querySelector('#audio-language'),audio=document.querySelector('#example-audio');function langChanged(k){language=k;select.value=k;audio.pause();audio.src=exampleAudioSrc(id,k);audio.playbackRate=Number(document.querySelector('#audio-rate').value);document.querySelector('#spoken-text').textContent=spokenExamples[id][k];document.querySelector('#spoken-text').dir=['ar','fa'].includes(k)?'rtl':'ltr';document.querySelector('#spoken-text').lang=k;document.querySelector('#audio-status').textContent=exampleAudioLabel(k);let helper=document.querySelector('#book-language');if(helper){helper.value=k;helper.dispatchEvent(new Event('change'));}else{let help=paper.querySelector('.audio-rule-help');if(!help){help=document.createElement('p');help.className='audio-rule-help muted';paper.querySelector('.rule')?.after(help);}help.textContent=k==='de'?'':ruleHelp[id][k];help.lang=k;help.dir=['ar','fa'].includes(k)?'rtl':'ltr';}}select.onchange=()=>langChanged(select.value);document.querySelector('#audio-rate').onchange=e=>audio.playbackRate=Number(e.target.value);document.querySelector('#audio-german').onclick=()=>{langChanged('de');audio.play().catch(()=>document.querySelector('#audio-status').textContent='Bitte starte das Audio über die Wiedergabetaste.');};audio.onerror=()=>document.querySelector('#audio-status').textContent='Die Audiodatei konnte nicht geladen werden. Bitte versuche es später erneut.';const helper=document.querySelector('#book-language');if(helper){let handler=helper.onchange;helper.onchange=()=>{handler();if(select.value!==helper.value){select.value=helper.value;audio.pause();audio.src=exampleAudioSrc(id,helper.value);document.querySelector('#audio-status').textContent=exampleAudioLabel(helper.value);audio.playbackRate=Number(document.querySelector('#audio-rate').value);document.querySelector('#spoken-text').textContent=spokenExamples[id][helper.value];document.querySelector('#spoken-text').dir=['ar','fa'].includes(helper.value)?'rtl':'ltr';}};}langChanged(language);}
}
const finalBaseRoute=route;
route=function(){document.querySelectorAll('audio').forEach(a=>a.pause());finalBaseRoute();enhanceLesson();};
route();
