/* Short, visual A1; guided explanations for A2. Existing exercises and translations remain available. */
const beginnerUnits={
ankommen:{icon:'👋',intro:'Hallo! Ich bin Samira.',ask:'Wie heißt du?',tiles:[['👤','Ich heiße …'],['🌍','Ich komme aus …'],['🏠','Ich wohne in …']],grammar:[['👤','Ich','bin','Samira.'],['👤','Du','bist','Pavel.'],['💬','Wo','wohnst','du?']],note:'Ich bin. Du bist.',missions:['Schreibe: Ich heiße … Ich wohne in …','Frage: Wie heißt du?','Schreibe: Das ist … Er / Sie ist …']},
einkaufen:{icon:'🛒',intro:'Ich kaufe Brot und Äpfel.',ask:'Was kaufst du?',tiles:[['🍞','das Brot'],['🍎','der Apfel'],['🥛','die Milch']],grammar:[['🍎','Ich','kaufe','einen Apfel.'],['🍞','Ich','möchte','ein Brot.'],['💶','Das Brot','kostet','2 Euro.']],note:'der Apfel → einen Apfel',missions:['Schreibe: Ich möchte …, bitte.','Frage: Was kostet …?','Schreibe 3 Dinge für dein Frühstück.']},
termine:{icon:'📅',intro:'Mein Termin: Montag, 9 Uhr.',ask:'Wann hast du Zeit?',tiles:[['📅','am Montag'],['🕘','um 9 Uhr'],['✅','Ja, das passt.']],grammar:[['📅','Ich','komme','am Montag.'],['🕘','Ich','komme','um 9 Uhr.'],['💬','Haben','Sie','Zeit?']],note:'📅 am Montag · 🕘 um 9 Uhr',missions:['Schreibe: Ich habe am … Zeit.','Schreibe: Ich kann um … nicht.','Schreibe: Mein Termin ist am … um …']},
wohnen:{icon:'🏠',intro:'Meine Wohnung hat zwei Zimmer.',ask:'Wie wohnst du?',tiles:[['🛏️','das Zimmer'],['🍳','die Küche'],['🛁','das Bad']],grammar:[['🏠','Ich','habe','eine Wohnung.'],['❌','Ich','habe','keinen Balkon.'],['💡','Die Küche','ist','nicht dunkel.']],note:'kein Balkon · nicht dunkel',missions:['Schreibe: Meine Wohnung hat …','Schreibe: Ich habe keinen / keine / kein …','Schreibe: Mein Zimmer ist …']}
};
const beginnerIcons={Name:'👤',Vorname:'👤',Familienname:'👪',Land:'🌍',Stadt:'🏙️',Sprache:'💬',Adresse:'📍',Beruf:'💼',heißen:'👤',kommen:'🚶',wohnen:'🏠',sprechen:'💬',lernen:'📖',sein:'👤',neu:'✨',alt:'👴',jung:'🧒',freundlich:'😊',gut:'👍',international:'🌍',Brot:'🍞',Milch:'🥛',Apfel:'🍎',Preis:'🏷️',Geld:'💶',Kasse:'🧾',Tüte:'🛍️',Gemüse:'🥕',kaufen:'🛒',bezahlen:'💳',brauchen:'📝',kosten:'🏷️',essen:'🍽️',nehmen:'🤲',frisch:'🥬',teuer:'💶💶💶',günstig:'💶',süß:'🍯',lecker:'😋',billig:'💶',Termin:'📅',Tag:'☀️',Woche:'🗓️',Uhr:'🕘',Minute:'⏱️',Stunde:'🕐',Kalender:'🗓️',Pause:'☕',haben:'🤲',beginnen:'▶️',dauern:'⏳',warten:'⏳',fragen:'❓',vereinbaren:'🤝',pünktlich:'✅',früh:'🌅',spät:'🌙',frei:'✅',kurz:'⏱️',lang:'⏳',Wohnung:'🏠',Zimmer:'🛏️',Küche:'🍳',Bad:'🛁',Tisch:'🍽️',Stuhl:'🪑',Miete:'💶',Schlüssel:'🔑',suchen:'🔍',finden:'✅',öffnen:'🔓',schließen:'🔒',putzen:'🧹',groß:'🐘',klein:'🐭',hell:'☀️',dunkel:'🌙',ruhig:'🤫',sauber:'✨'};
const visualSteps=['👀 Schauen','🧩 Wörter','🎨 Sätze','🎧 Hören & Lesen','🎯 Üben','✍️ Schreiben','✅ Fertig'];
const fullVcard=vcard;vcard=function(l,w){if(l.level!=='A1')return fullVcard(l,w);return `<a class="v-card visual-word" href="${vlink(l,w)}"><span class="word-icon" aria-hidden="true">${beginnerIcons[w.key]||'💬'}</span><strong>${esc(w.word)}</strong>${vtranslation(l,w)}<small>${w.pos==='Verb'?esc('ich '+w.forms[0]):w.pos==='Nomen'?esc(w.plural):esc(w.opposite)}</small></a>`;};
const fullPlatformLesson=platformLesson;platformLesson=function(id,raw=0){fullPlatformLesson(id,raw);const l=lessons.find(x=>x.id===id);if(!l)return;document.body.dataset.learningLevel=l.level;const step=Math.max(0,Math.min(6,Number(raw)||0)),c=main.querySelector('.pl-lesson-content');if(l.level==='A2'){main.querySelector('.pl-lesson-head').insertAdjacentHTML('beforeend','<p class="visual-level-note">👀 Bild ansehen · 📖 Lesen · 💬 Eigene Sätze bilden</p>');if(step===0){main.querySelector('.pl-scene h2').textContent='Deine Situation';main.querySelector('.pl-scene .pl-kicker').textContent='A2 · Schau und lies';}return;}if(l.level!=='A1')return;const u=beginnerUnits[id];if(!u)return;
main.querySelector('.pl-lesson-head p')?.remove();main.querySelector('.pl-lesson-aside')?.remove();main.querySelector('.pl-lesson-body').classList.add('visual-single');main.querySelectorAll('.pl-steps a').forEach((a,i)=>a.innerHTML=`<span>${i+1}</span>${visualSteps[i]}`);main.querySelectorAll('#pl-step-select option').forEach((o,i)=>o.textContent=visualSteps[i]);const next=main.querySelector('.pl-bottom-nav .btn:last-child');if(step<6)next.textContent='Weiter →';
if(step===0)c.innerHTML=`<section class="visual-start"><img src="assets/${platformImage(l)}.webp" alt="${esc(l.title)}"><div><span class="visual-icon" aria-hidden="true">${u.icon}</span><h2>${u.intro}</h2><p>👀 Schau das Bild an.</p><p>💬 ${u.ask}</p></div></section><div class="visual-tiles">${u.tiles.map(([i,t])=>`<div><span aria-hidden="true">${i}</span><strong>${t}</strong></div>`).join('')}</div>`;
if(step===1){const p=c.querySelector(':scope > p');if(p)p.textContent='👆 Tippe auf ein Wort.';c.querySelectorAll('.pl-vocab-group h2').forEach((h,i)=>h.textContent=['🧩 Nomen','🏃 Verben','🎨 Adjektive'][i]);}
if(step===2){const old=c.innerHTML;c.innerHTML=`<h2>🎨 So geht der Satz.</h2><div class="visual-sentences">${u.grammar.map(([icon,...parts])=>`<div><span aria-hidden="true">${icon}</span>${parts.map((p,i)=>`<b class="sentence-part part-${i}">${p}</b>`).join('')}</div>`).join('')}</div><p class="visual-rule">${u.note}</p><details class="visual-more"><summary>📖 Mehr Erklärung & Übersetzung</summary>${old}</details>`;if(lowLevel(l))document.querySelector('#pl-rule-lang').onchange=e=>{const t=document.querySelector('#pl-rule-translation'),k=e.target.value;t.textContent=k==='de'?'':ruleHelp[id][k];t.lang=k;t.dir=['ar','fa'].includes(k)?'rtl':'ltr';};}
if(step===3){c.querySelectorAll('.step-label').forEach(x=>x.remove());c.querySelector('h2').textContent='💬 Lies mit.';c.querySelector('.pl-dialogue')?.nextElementSibling?.remove();const hs=c.querySelectorAll('h2');if(hs[1])hs[1].textContent='✅ Was ist richtig?';if(hs[2])hs[2].textContent='🎧 Hör zu. Sprich nach.';}
if(step===4){c.querySelector('h2').textContent='🎯 Du bist dran.';const p=c.querySelector('h2 + p');if(p)p.textContent='Wähle die Antwort.';}
if(step===5){c.querySelector('h2').textContent='✍️ Dein Satz';c.querySelector('h2 + p').textContent='Schreibe 1–2 Sätze.';document.querySelector('label[for="draft"]').textContent='Dein Text';document.querySelector('#draft').rows=3;c.querySelectorAll('.muted').forEach(p=>p.remove());c.querySelector('h3').textContent='✅ Prüfe deinen Satz.';const labels=c.querySelectorAll('label.check');labels.forEach((x,i)=>{if(i>1)x.remove();else x.lastChild.textContent=i?' Mein Verb passt.':' Mein Satz passt.';});let n=0;const prompt=()=>{document.querySelector('#pl-task').innerHTML=`<p>${u.missions[n]}</p>`;};prompt();document.querySelector('#pl-new-task').onclick=()=>{n=(n+1)%u.missions.length;prompt();};document.querySelector('#pl-task-level').onchange=()=>{prompt();const difficulty=document.querySelector('#pl-task-level').value;document.querySelector('#pl-task').insertAdjacentHTML('beforeend',`<p>${difficulty==='easy'?'1 Satz.':difficulty==='hard'?'3 Sätze.':'2 Sätze.'}</p>`);};}
if(step===6){const h=c.querySelector('h2');h.textContent='✅ Gut gemacht!';c.querySelector('.pl-prompt').innerHTML='<p>🧩 Sage 3 Wörter.</p><p>💬 Sage 1 Satz.</p>';document.querySelector('#pl-complete').textContent='Fertig ✓';}
};
const fullWordBook=wordBook;wordBook=function(id,key){fullWordBook(id,key);const l=lessons.find(x=>x.id===id);document.body.dataset.learningLevel=l?.level||'';if(l?.level!=='A1')return;const papers=main.querySelectorAll('.paper');for(const p of papers){p.querySelectorAll('.teacher-tip,.v-help').forEach(x=>x.remove());}const w=wordLibrary[key];const first=papers[0];if(first&&w){first.querySelector('h1').insertAdjacentHTML('beforebegin',`<span class="visual-icon" aria-hidden="true">${beginnerIcons[key]||'💬'}</span>`);const definition=first.querySelector('.v-definition');if(definition)definition.remove();const tables=first.querySelectorAll('table');tables.forEach(t=>{const detail=document.createElement('details');detail.innerHTML='<summary>📖 Alle Formen</summary>';t.replaceWith(detail);detail.append(t);});}if(first){const nodes=[...first.children];const start=nodes.findIndex(n=>n.tagName==='H3');if(start>=0){const detail=document.createElement('details');detail.className='visual-more';detail.innerHTML='<summary>📖 Grammatik</summary>';first.insertBefore(detail,nodes[start]);nodes.slice(start).forEach(n=>detail.append(n));}}const second=papers[1];if(second){const h=second.querySelector('h2');if(h)h.textContent='💬 Lies den Satz.';const headings=[...second.querySelectorAll('h3')];for(const h of headings){if(h.textContent==='Entdecke das Muster'){const p=h.nextElementSibling;p?.remove();h.remove();}}}const input=main.querySelector('#v-own');if(input)input.rows=2;};
const visualBaseRoute=route;route=function(){document.body.dataset.learningLevel='';visualBaseRoute();};
const fullVocabBook=vocabBook;vocabBook=function(id,raw=0){fullVocabBook(id,raw);const l=lessons.find(x=>x.id===id);document.body.dataset.learningLevel=l?.level||'';if(l?.level!=='A1')return;main.querySelectorAll('.teacher-tip,.teacher-note').forEach(x=>x.remove());const intro=main.querySelector('.paper > p');if(intro)intro.textContent='👆 Wähle ein Wort.';main.querySelectorAll('.paper > .muted').forEach(x=>x.remove());};
const fullPlatformCourse=platformCourse;platformCourse=function(selected='A1'){fullPlatformCourse(selected);document.body.dataset.learningLevel=selected;if(selected!=='A1')return;const intro=main.querySelector('.pl-course-head p');if(intro)intro.textContent='👆 Wähle ein Thema.';main.querySelector('.pl-note')?.remove();main.querySelectorAll('.pl-course-item').forEach(a=>{const id=a.getAttribute('href').split('/')[1],u=beginnerUnits[id];if(u){a.querySelector('h2').textContent=u.icon+' '+a.querySelector('h2').textContent;a.querySelector('p').textContent=u.intro;a.querySelector('small').textContent='👀 Schauen · 🎧 Hören · 💬 Sprechen';}});};
