/* LiD: original learning tasks based on the supplied 07.05.2025 catalogue. */
const lidLangs={uk:'Українська · Ukrainisch',de:'Deutsch',ar:'العربية · Arabisch',fa:'فارسی · Persisch',ru:'Русский · Russisch',tr:'Türkçe · Türkisch',zh:'中文 · Chinesisch',en:'English',it:'Italiano',es:'Español'};
const lidState={lang:'de',level:'normal',sessions:{},solved:new Set(),mix:null,match:null,time:null};
const lidPDF='https://www.bamf.de/SharedDocs/Anlagen/DE/Integration/Einbuergerung/gesamtfragenkatalog-lebenindeutschland.pdf?__blob=publicationFile&v=23';
function lidShuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function lidHeader(title,sub){return `<a class="back" href="#orientierungskurs">← Orientierungskurs</a><div class="lid-heading"><img class="dm-3d dm-3d-float lid-3d" src="assets/3d/gebaeude.webp" alt="" width="192" height="192" aria-hidden="true"><span class="tape-label">Orientierungskurs · Leben in Deutschland</span><h1>${title}</h1><p>${sub}</p></div><nav class="oral-tabs" aria-label="Leben in Deutschland"><a href="#orientierungskurs">Lernmissionen</a><a href="#orientierungskurs/mix">Wissensrunde</a><a href="#orientierungskurs/match">Begriffe verbinden</a><a href="#orientierungskurs/time">Zeitreise</a></nav>`;}
function lidFooter(){return `<div class="lid-source"><p>Eigene Lernübungen nach dem BAMF-Fragenkatalog, Stand 07.05.2025. Keine vollständige Prüfungssimulation. Die Aufgaben wechseln innerhalb eines festen Übungspools.</p><a href="${lidPDF}" download>Gesamten Fragenkatalog als PDF herunterladen ↓</a> · <a href="https://www.bamf.de/DE/Themen/Integration/ZugewanderteTeilnehmende/OnlineTestcenter/online-testcenter-node.html" target="_blank" rel="noopener">Alle offiziellen Fragen beim BAMF üben ↗</a><p>Deine Lernsterne und Antworten gelten für diese geöffnete Sitzung. Beim Neuladen beginnen sie von vorn.</p></div>`;}
function lidLangControl(){return `<label for="lid-lang">Erklärungen übersetzen</label><select id="lid-lang">${Object.entries(lidLangs).map(([k,v])=>`<option value="${k}" ${lidState.lang===k?'selected':''}>${v}</option>`).join('')}</select>`;}
function lidBindLang(render){lidBindHint();document.querySelector('#lid-lang')?.addEventListener('change',e=>{lidState.lang=e.target.value;render();document.querySelector('#lid-lang')?.focus({preventScroll:true});});}
function lidTranslation(m){const i=lidModules.indexOf(m);return lidState.lang==='de'?'':`<div class="lid-translation" lang="${lidState.lang}" dir="${['ar','fa'].includes(lidState.lang)?'rtl':'ltr'}"><p>${esc(lidTranslations[lidState.lang][i])}</p></div>`;}
function lidImage(m){const imgs={park:['assets/sprechen/park.webp','Erwachsene und ein Kind verbringen Zeit im Park.','KI-erstellte Alltagsszene: gemeinsam leben.'],arzt:['assets/sprechen/arzt.webp','Ein Patient spricht mit einer Ärztin.','KI-erstellte Alltagsszene: medizinische Versorgung.'],markt:['assets/sprechen/markt.webp','Zwei Menschen unterhalten sich am Marktstand.','KI-erstellte Alltagsszene: Begegnung auf dem Markt.'],adler:['assets/lid/grundrechte.webp','Menschen vor dem Reichstagsgebäude, davor ein Gesetzbuch mit Paragrafenzeichen und eine Waage.','Illustration: Grundgesetz und Rechtsstaat.'],karte:['assets/lid/nrw.webp','Karte von Nordrhein-Westfalen mit dem Rhein, dem Kölner Dom, einem Förderturm aus dem Ruhrgebiet und dem Landtag in Düsseldorf.','Illustration: Nordrhein-Westfalen.']};if(!m.img)return '';let x=imgs[m.img];return `<figure class="lid-figure ${['adler','karte'].includes(m.img)?'lid-diagram':''}"><img src="${x[0]}" alt="${x[1]}" loading="lazy"><figcaption>${x[2]}</figcaption></figure>`;}
function lidLesson(m,open=false){open=open||lidState.hint;return `<details class="lid-hint" id="lid-hint" ${open?'open':''}><summary><span class="lid-hint-ico" aria-hidden="true">💡</span><span><b>Kurz erklärt</b><small>${open?'Hier ist die Erklärung zum Nachlesen.':'Probier es zuerst selbst. Brauchst du Hilfe? Dann klapp die Erklärung auf.'}</small></span></summary><aside class="lid-notebook"><span class="step-label">Kurz erklärt</span><h2>${m.title}</h2>${lidImage(m)}<ol class="lid-facts">${m.facts.map(f=>`<li>${esc(f)}</li>`).join('')}</ol>${lidLangControl()}${lidTranslation(m)}<p class="oral-note">Die Übersetzung erklärt die Kernbegriffe. Die Übungsfragen bleiben auf Deutsch.</p><a href="${lidPDF}#page=${m.page}" target="_blank" rel="noopener">Passende Katalogseiten öffnen (PDF) ↗</a></aside></details>`;}
function lidBindHint(){const d=document.querySelector('#lid-hint');if(d)d.addEventListener('toggle',()=>{lidState.hint=d.open;});}
function lidVideo(){const videos=[['5EcgHJ2-7OQ','https://www.youtube.com/watch?v=5EcgHJ2-7OQ'],['2xV67QRP8B8','https://youtu.be/2xV67QRP8B8'],['6wdCdGV1nWE','https://youtu.be/6wdCdGV1nWE']];return `<section class="lid-course-video panel" aria-labelledby="lid-video-heading"><span class="step-label">Ansehen & verstehen</span><h2 id="lid-video-heading">Videos zum Orientierungskurs</h2>${videos.map(([id,url],i)=>`<article class="lid-video-item"><h3>Orientierungskurs · Video ${i+1}</h3><div class="video-player"><iframe src="https://www.youtube.com/embed/${id}?rel=0" title="Orientierungskurs – Video ${i+1}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="video-actions"><a class="btn" href="${url}" target="_blank" rel="noopener noreferrer">Video ${i+1} auf YouTube öffnen ↗</a></div></article>`).join('')}<p class="muted">Falls ein Video hier nicht abgespielt wird, öffne es direkt auf YouTube.</p></section>`;}

function lidHome(){let total=lidModules.reduce((a,m)=>a+m.questions.length,0);main.innerHTML=lidHeader('Deutschland entdecken.','Finde heraus, wie Demokratie, Geschichte und Zusammenleben deinen Alltag betreffen. Wähle eine Mission und entscheide selbst.')+lidVideo()+`<div class="lid-progress"><b>${lidState.solved.size} von ${total} Lernsternen</b><progress aria-label="Einmal richtig beantwortete Lernaufgaben" value="${lidState.solved.size}" max="${total}"></progress><span>Für jede erstmals richtig beantwortete Aufgabe gibt es einen Stern.</span></div><div class="lid-grid">${lidModules.map((m,i)=>`<a class="lid-card" href="#orientierungskurs/${m.id}"><span class="lid-number">${String(i+1).padStart(2,'0')}</span><span class="eyebrow">${m.tag}</span><h2>${m.title}</h2><p>${m.intro}</p><span>${m.questions.length} Situationen · Mission öffnen →</span></a>`).join('')}</div><section class="lid-games"><h2>Anders üben.</h2><div class="oral-cards"><a class="oral-card" href="#orientierungskurs/match"><h3>Begriffs-Paare</h3><p>Wer beschließt Gesetze? Welche Versicherung passt? Verbinde die passenden Karten.</p></a><a class="oral-card" href="#orientierungskurs/time"><h3>Eine Reise durch die Zeit</h3><p>Ordne Ereignisse den Jahren zu. Die Zeitleiste zeigt dir anschließend den Zusammenhang.</p></a><a class="oral-card" href="#orientierungskurs/mix"><h3>Die 10-Fragen-Runde</h3><p>Zufällige Aufgaben aus den Missionen. Direktes Feedback und eine Auswertung am Ende.</p></a></div></section><details class="lid-exam-info"><summary>Was erwartet mich in der Prüfung?</summary><p>Der Test „Leben in Deutschland“ hat 33 Fragen: 30 allgemeine und 3 zu deinem Bundesland. Pro Frage ist eine von vier Antworten richtig. Du hast 60 Minuten Zeit. Mit mindestens 15 richtigen Antworten ist der LiD-Test bestanden; mit mindestens 17 wird auch das für die Einbürgerung erforderliche Wissen nachgewiesen.</p><p>Hier übst du ausgewählte Themen mit eigenen Aufgaben. Für die vollständige Vorbereitung nutze zusätzlich die 300 allgemeinen und die 10 Fragen deines Bundeslandes im offiziellen Katalog. Unser Landesmodul behandelt NRW.</p><a href="https://www.bamf.de/DE/Themen/Integration/ZugewanderteTeilnehmende/Integrationskurse/Abschlusspruefung/abschlusspruefung-node.html" target="_blank" rel="noopener">Prüfungsinformationen des BAMF ↗</a></details>`+lidFooter();}
function lidNewTask(m,previous){lidState.hint=false;let bag=previous?.bag||[];if(!bag.length){bag=lidShuffle(m.questions.map((_,i)=>i));if(bag.length>1&&bag.at(-1)===previous?.index)[bag[0],bag[bag.length-1]]=[bag.at(-1),bag[0]];}let index=bag.pop();return {index,bag,order:lidShuffle([0,1,2,3]),selected:null,checked:false};}
function lidTask(m,s,mix=false){const q=m.questions[s.index], count=mix?4:lidState.level==='easy'?2:lidState.level==='normal'?3:4;let allowed=new Set([q.answer,...s.order.filter(i=>i!==q.answer).slice(0,count-1)]);const choices=s.order.filter(i=>allowed.has(i));const correct=s.selected===q.answer;return `<section class="lid-task"><span class="step-label">${mix?'Wissensrunde':'Deine Entscheidung'} · ${m.tag}</span><h2 id="lid-question">${esc(q.prompt)}</h2><fieldset aria-labelledby="lid-question">${choices.map(i=>`<label class="lid-answer ${s.checked&&i===q.answer?'is-right':''} ${s.checked&&i===s.selected&&!correct?'is-wrong':''}"><input type="radio" name="lid-answer" value="${i}" ${s.selected===i?'checked':''} ${s.checked?'disabled':''}>${esc(q.options[i])}</label>`).join('')}</fieldset><button class="btn" id="lid-check" ${s.checked?'disabled':''}>Antwort prüfen</button><div id="lid-feedback" role="status" aria-live="polite">${s.checked?`<div class="lid-feedback ${correct?'correct':'wrong'}"><b>${correct?'Richtig erkannt!':'Schau noch einmal auf den Zusammenhang.'}</b><p>Richtige Antwort: ${esc(q.options[q.answer])}</p><p>${esc(q.explanation)}</p>${lidTranslation(m)}</div>`:''}</div><div class="lid-actions"><button class="btn secondary" id="lid-next">${mix?'Nächste Frage →':'Andere Situation ↻'}</button>${!mix&&s.checked?'<button class="btn secondary" id="lid-retry">Noch einmal versuchen</button>':''}</div>${!mix?`<p class="oral-note">${m.questions.length} Situationen in dieser Mission. Alle kommen vor, bevor die nächste Runde beginnt.</p>`:''}</section>`;}
function lidBindTask(m,s,render,onNext,mix=false){document.querySelectorAll('[name="lid-answer"]').forEach(r=>r.onchange=()=>s.selected=Number(r.value));document.querySelector('#lid-check').onclick=()=>{if(s.selected===null){document.querySelector('#lid-feedback').textContent='Wähle zuerst eine Antwort.';return;}s.checked=true;if(s.selected===m.questions[s.index].answer)lidState.solved.add(m.id+'-'+s.index);render();document.querySelector('#lid-feedback')?.scrollIntoView({block:'nearest',behavior:'smooth'});};document.querySelector('#lid-next').onclick=()=>{if(mix&&!s.checked){document.querySelector('#lid-feedback').textContent='Prüfe zuerst deine Antwort, bevor du weitergehst.';return;}onNext();};document.querySelector('#lid-retry')?.addEventListener('click',()=>{s.selected=null;s.checked=false;render();});lidBindLang(render);}
function lidMission(m){const s=lidState.sessions[m.id]||(lidState.sessions[m.id]=lidNewTask(m));main.innerHTML=lidHeader(m.title+'.',m.intro)+`<div class="lid-tools"><label for="lid-level">Schwierigkeit</label><select id="lid-level"><option value="easy" ${lidState.level==='easy'?'selected':''}>Leichter · 2 Antworten</option><option value="normal" ${lidState.level==='normal'?'selected':''}>Gleich schwer · 3 Antworten</option><option value="hard" ${lidState.level==='hard'?'selected':''}>Schwieriger · 4 Antworten</option></select></div><div class="lid-layout">${lidTask(m,s)}${lidLesson(m,s.checked)}</div>`+lidFooter();lidBindTask(m,s,()=>lidMission(m),()=>{lidState.sessions[m.id]=lidNewTask(m,s);lidMission(m);document.querySelector('#lid-question').scrollIntoView({block:'nearest'});});document.querySelector('#lid-level').onchange=e=>{lidState.level=e.target.value;s.selected=null;s.checked=false;lidMission(m);};}
function lidStartMix(){lidState.hint=false;lidState.mix={items:lidShuffle(lidModules.flatMap(m=>m.questions.map((q,i)=>({m,index:i,order:lidShuffle([0,1,2,3]),selected:null,checked:false})))).slice(0,10),pos:0};}
function lidMix(){if(!lidState.mix)lidStartMix();const r=lidState.mix;if(r.pos>=r.items.length){const score=r.items.filter(s=>s.selected===s.m.questions[s.index].answer).length;main.innerHTML=lidHeader('Deine Wissensrunde.',`${score} von 10 Antworten richtig. Das ist eine Lernrunde, keine Prüfungsbewertung.`)+`<section class="lid-task"><h2>${score===10?'Alle Zusammenhänge erkannt!':'Mit den Erklärungen weiterlernen.'}</h2>${r.items.map(s=>`<details><summary>${s.selected===s.m.questions[s.index].answer?'✓':'↻'} ${esc(s.m.questions[s.index].prompt)}</summary><p>Richtig: ${esc(s.m.questions[s.index].options[0])}</p><p>${esc(s.m.questions[s.index].explanation)}</p><a href="#orientierungskurs/${s.m.id}">Diese Mission wiederholen →</a></details>`).join('')}<button class="btn" id="lid-new-round">Neue Runde mit 10 Fragen</button></section>`+lidFooter();document.querySelector('#lid-new-round').onclick=()=>{lidStartMix();lidMix();};return;}let s=r.items[r.pos];main.innerHTML=lidHeader('Wissen verbinden.',`Frage ${r.pos+1} von 10 · Vier Antworten, eine ist richtig.`)+`<progress class="lid-round-progress" aria-label="Fortschritt der Wissensrunde" value="${r.pos}" max="10"></progress><div class="lid-layout">${lidTask(s.m,s,true)}${lidLesson(s.m,s.checked)}</div>`+lidFooter();lidBindTask(s.m,s,lidMix,()=>{r.pos++;lidState.hint=false;lidMix();},true);}
const lidPairSets=[{module:1,pairs:[['Bundestag','Beschließt Bundesgesetze'],['Bundesrat','Vertritt die Bundesländer'],['Gerichte','Entscheiden unabhängig nach dem Recht'],['Grundgesetz','Die deutsche Verfassung']]},{module:3,pairs:[['Krankenversicherung','Medizinische Versorgung'],['Rentenversicherung','Absicherung im Alter'],['Arbeitslosenversicherung','Absicherung bei Arbeitslosigkeit'],['Soziale Marktwirtschaft','Wettbewerb mit sozialer Absicherung']]},{module:0,pairs:[['Meinungsfreiheit','Die Regierung kritisieren dürfen'],['Religionsfreiheit','Auch ohne Religion leben dürfen'],['Menschenwürde','Jeder Mensch hat den gleichen Wert'],['Rechtsstaat','Auch der Staat beachtet Gesetze']]}];
function lidNewMatch(){lidState.hint=false;let n=lidState.match?(lidState.match.n+1)%lidPairSets.length:0;lidState.match={n,left:lidShuffle([0,1,2,3]),right:lidShuffle([0,1,2,3]),selected:null,done:[],message:'Wähle zuerst einen Begriff, dann die passende Erklärung.'};}
function lidMatch(){if(!lidState.match)lidNewMatch();let s=lidState.match,set=lidPairSets[s.n];main.innerHTML=lidHeader('Begriffe verbinden.','Finde vier passende Paare. Du kannst alle Karten mit Maus, Touch oder Tastatur bedienen.')+`<div class="lid-layout"><section class="lid-task"><h2>${lidModules[set.module].title}</h2><p>${s.done.length} von 4 Paaren gefunden</p><div class="lid-pairs"><div>${s.left.map(i=>`<button class="lid-pair ${s.selected===i?'selected':''}" data-left="${i}" aria-pressed="${s.selected===i}" ${s.done.includes(i)?'disabled':''}>${s.done.includes(i)?'✓ ':''}${set.pairs[i][0]}</button>`).join('')}</div><div>${s.right.map(i=>`<button class="lid-pair" data-right="${i}" ${s.done.includes(i)?'disabled':''}>${s.done.includes(i)?'✓ ':''}${set.pairs[i][1]}</button>`).join('')}</div></div><p role="status" class="lid-feedback">${s.message}</p><button id="lid-new-pairs" class="btn secondary">Andere Begriffe ↻</button></section>${lidLesson(lidModules[set.module],s.done.length===4)}</div>`+lidFooter();document.querySelectorAll('[data-left]').forEach(b=>b.onclick=()=>{s.selected=Number(b.dataset.left);s.message='Jetzt die passende Erklärung wählen.';lidMatch();});document.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>{let i=Number(b.dataset.right);if(s.selected===null){s.message='Wähle zuerst links einen Begriff.';}else if(i===s.selected){s.done.push(i);s.selected=null;s.message=s.done.length===4?'Alle vier Paare passen! Wähle nun andere Begriffe.':'Das passt. Finde das nächste Paar.';}else{s.message='Dieses Paar passt noch nicht. Nutze die Erklärung rechts und versuche es erneut.';}lidMatch();});document.querySelector('#lid-new-pairs').onclick=()=>{lidNewMatch();lidMatch();};lidBindLang(lidMatch);}
const lidEvents=[['1949','Gründung der Bundesrepublik und der DDR'],['1961','Bau der Berliner Mauer'],['1989','Öffnung der Berliner Mauer'],['1990','Deutsche Wiedervereinigung']];
function lidTime(){let s=lidState.time||(lidState.time={order:lidShuffle([0,1,2,3]),answers:{},checked:false});main.innerHTML=lidHeader('Zeitreise Deutschland.','Gib jedem Ereignis das richtige Jahr. Anschließend wird daraus deine Zeitleiste.')+`<div class="lid-layout"><section class="lid-task"><h2>Was geschah wann?</h2>${s.order.map(i=>`<label class="lid-event" for="lid-year-${i}"><span>${lidEvents[i][1]}</span><select id="lid-year-${i}" data-event="${i}"><option value="">Jahr wählen</option>${lidEvents.map(([y])=>`<option ${s.answers[i]===y?'selected':''}>${y}</option>`).join('')}</select>${s.checked?`<b class="${s.answers[i]===lidEvents[i][0]?'lid-good':'lid-error'}">${s.answers[i]===lidEvents[i][0]?'✓ Richtig':'Noch nicht: '+lidEvents[i][0]}</b>`:''}</label>`).join('')}<div class="lid-actions"><button class="btn" id="lid-time-check">Zeitreise prüfen</button><button class="btn secondary" id="lid-time-new">Neu mischen ↻</button></div><div role="status">${s.checked?`<p>${lidEvents.filter((e,i)=>s.answers[i]===e[0]).length} von 4 Ereignissen richtig zugeordnet.</p><ol class="lid-timeline">${lidEvents.map(([y,t])=>`<li><b>${y}</b><span>${t}</span></li>`).join('')}</ol>`:''}</div></section>${lidLesson(lidModules[5],s.checked)}</div>`+lidFooter();document.querySelectorAll('[data-event]').forEach(x=>x.onchange=()=>{s.answers[x.dataset.event]=x.value;});document.querySelector('#lid-time-check').onclick=()=>{s.checked=true;lidTime();};document.querySelector('#lid-time-new').onclick=()=>{lidState.time=null;lidState.hint=false;lidTime();};lidBindLang(lidTime);}
const beforeLidTraining=training;training=function(id){if(id==='lid')lidHome();else if(id==='lid-mix')lidMix();else if(id==='lid-match')lidMatch();else if(id==='lid-time')lidTime();else{let m=lidModules.find(x=>'lid-'+x.id===id);if(m)lidMission(m);else beforeLidTraining(id);}};
// Separate orientation-course routes; existing shared LiD links remain valid.
const beforeOrientationRoute=route;
route=function(){
 const h=location.hash.slice(1),p=h.split('/');
 if(p[0]==='orientierungskurs'||h==='training/lid'||h.startsWith('training/lid-')){
  document.querySelectorAll('audio').forEach(a=>a.pause());
  const id=p[0]==='orientierungskurs'?(p[1]?'lid-'+p[1]:'lid'):p[1];
  training(id);
  document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav==='orientation';a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
  window.scrollTo(0,0);
 }else{document.querySelector('[data-nav="orientation"]')?.removeAttribute('aria-current');beforeOrientationRoute();}
};
route();
