/* Shared student feedback; user content is always rendered as text. */
(()=>{
 const owned=()=>{try{return JSON.parse(localStorage.getItem('da-pinnwand-owned')||'{}');}catch{return {};}};
 let pending=null;
 async function api(path,options){const r=await fetch('/api/pinnwand'+path,{cache:'no-store',...options});let data;try{data=await r.json();}catch{throw Error('Die Pinnwand ist gerade nicht erreichbar. Bitte versuche es später erneut.');}if(!r.ok)throw Error(data.error||'Bitte versuche es später erneut.');return data;}
 function page(){
 main.innerHTML=`<section class="pl-course-head"><span class="pl-kicker">DEINE STIMME ZÄHLT</span><h1>Unsere Pinnwand</h1><p>Was gefällt dir? Was möchtest du lernen?</p></section><div class="pw-layout"><form class="pw-form pl-panel"><h2>📌 Zettel anpinnen</h2><fieldset><legend>Was möchtest du teilen?</legend><label class="pw-choice"><input type="radio" name="kind" value="feedback" checked> 💬 Feedback</label><label class="pw-choice"><input type="radio" name="kind" value="wunsch"> 💡 Wunsch</label></fieldset><label for="pw-name">Dein Name <span>(freiwillig)</span></label><input id="pw-name" name="name" maxlength="40" placeholder="Oder bleibe anonym" autocomplete="off"><label for="pw-message">Dein Zettel</label><textarea id="pw-message" name="message" required minlength="3" maxlength="600" rows="5" placeholder="Ich wünsche mir …"></textarea><span class="pw-count">0 / 600</span><div class="pw-honey" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="pw-hint">Alle können deinen Zettel lesen. Bitte bleibe freundlich und schreibe keine privaten Kontaktdaten.</p><button class="btn" type="submit">Zettel anpinnen</button><p class="pw-status" role="status" aria-live="polite"></p></form><section class="pw-posts" aria-label="Zettel der Lernenden"><div class="pw-toolbar"><h2>Feedback & Wünsche</h2><button type="button" class="btn secondary pw-refresh">Aktualisieren</button></div><p class="pw-load" role="status">Zettel werden geladen …</p><div class="pw-grid"></div><button type="button" class="btn secondary pw-more" hidden>Weitere Zettel</button></section></div>`;
 const root=main.querySelector('.pw-layout'),form=root.querySelector('form'),grid=root.querySelector('.pw-grid'),status=root.querySelector('.pw-status'),load=root.querySelector('.pw-load'),more=root.querySelector('.pw-more');let cursor=null;
 const showNote=n=>{const card=document.createElement('article');card.className='pw-note '+(n.kind==='wunsch'?'pw-wish':'pw-feedback');const tag=document.createElement('span');tag.className='pw-tag';tag.textContent=n.kind==='wunsch'?'💡 Wunsch':'💬 Feedback';const text=document.createElement('p');text.className='pw-message';text.textContent=n.message;const by=document.createElement('p');by.className='pw-by';by.textContent=n.name+' · '+new Date(n.created).toLocaleDateString('de-DE');card.append(tag,text,by);if(owned()[n.id]){const del=document.createElement('button');del.type='button';del.className='pw-delete';del.textContent='Meinen Zettel löschen';del.onclick=async()=>{if(!confirm('Deinen Zettel wirklich löschen?'))return;del.disabled=true;try{await api('/'+n.id,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:owned()[n.id]})});card.remove();const keys=owned();delete keys[n.id];try{localStorage.setItem('da-pinnwand-owned',JSON.stringify(keys));}catch{}status.textContent='Dein Zettel wurde gelöscht.';}catch(e){status.textContent=e.message;del.disabled=false;}};card.append(del);}grid.append(card);};
 async function refresh(append=false){more.disabled=true;try{const data=await api(append&&cursor?'?before='+cursor:'');if(!root.isConnected)return;if(!append)grid.replaceChildren();data.notes.forEach(showNote);cursor=data.notes.at(-1)?.created||cursor;more.hidden=!data.more;load.textContent=grid.children.length?'':'Hier ist noch Platz für deinen ersten Zettel.';}catch(e){load.textContent=e.message;}finally{more.disabled=false;}}
 root.querySelector('.pw-refresh').onclick=()=>refresh();more.onclick=()=>refresh(true);
 form.elements.namedItem('message').oninput=()=>{root.querySelector('.pw-count').textContent=form.elements.namedItem('message').value.length+' / 600';pending=null;};
 form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]');button.disabled=true;status.textContent='Dein Zettel wird angepinnt …';const values=Object.fromEntries(new FormData(form));const fingerprint=JSON.stringify(values);if(!pending||pending.fingerprint!==fingerprint)pending={id:crypto.randomUUID(),token:crypto.randomUUID(),fingerprint};const record={...values,id:pending.id,token:pending.token};try{await api('',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});let saved=true;try{localStorage.setItem('da-pinnwand-owned',JSON.stringify({...owned(),[record.id]:record.token}));}catch{saved=false;}pending=null;form.reset();root.querySelector('.pw-count').textContent='0 / 600';status.textContent=saved?'Danke! Dein Zettel hängt jetzt an der Pinnwand.':'Danke! Dein Zettel ist veröffentlicht. Dein Browser konnte die Berechtigung zum späteren Löschen nicht speichern.';await refresh();}catch(e){status.textContent=e.message;}finally{button.disabled=false;}};
 refresh();
 }
 const previous=route;route=function(){if(location.hash!=='#pinnwand')return previous();document.body.dataset.learningLevel='';page();document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav==='pinnwand';a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.querySelector('header').classList.remove('menu-open');document.querySelector('#pl-menu')?.setAttribute('aria-expanded','false');window.scrollTo({top:0,behavior:'instant'});};route();
})();
