/* Fresh exercises use language templates with verified answer rules. */
const practiceState=new Map();
const P_NAMES=['Mina','Alex','Samira','Pavel','Noor','Elena','Yusuf','Daria','Leo','Nora','Amir','Lina'];
const P_CITY=['Hagen','Essen','Bonn','Dortmund','Bochum','Köln','Wuppertal','Düsseldorf'];
const P_DAY=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag'];
const pick=a=>a[Math.floor(Math.random()*a.length)];
const gap=(s,a,options,why)=>({s,a,options,why});
const grammarBank={
ankommen:[gap('Ich … in Hagen.','wohne',['wohnst','wohnt'],'Bei „ich“ lautet die Endung -e.'),gap('Woher … Sie?','kommen',['kommt','kommst'],'Die höfliche Anrede „Sie“ verwendet die Pluralform.'),gap('Du … Deutsch.','lernst',['lernen','lernt'],'Bei „du“ lautet die Endung -st.')],
einkaufen:[gap('Ich kaufe … Apfel.','einen',['ein','eine'],'Apfel ist maskulin; nach kaufen steht Akkusativ.'),gap('Ich brauche … Milch.','keine',['keinen','kein'],'Milch ist feminin: keine Milch.'),gap('Wie viel … das Brot?','kostet',['kosten','kostest'],'Das Brot steht im Singular: es kostet.')],
termine:[gap('Der Termin ist … Montag.','am',['um','im'],'Vor Wochentagen steht am.'),gap('Wir treffen uns … zehn Uhr.','um',['am','an'],'Eine Uhrzeit wird mit um angeschlossen.'),gap('… Sie morgen Zeit?','Haben',['Hat','Habt'],'Die höfliche Frage beginnt mit Haben Sie.')],
wohnen:[gap('Die Wohnung hat … Balkon.','keinen',['keine','kein'],'Balkon ist maskulin und steht im Akkusativ.'),gap('Die Küche ist … groß.','nicht',['kein','keine'],'Ein Adjektiv wird hier mit nicht verneint.'),gap('Das Haus hat … Garage.','eine',['einen','ein'],'Garage ist feminin: eine Garage.')],
alltag:[gap('Gestern … ich nach Bonn gefahren.','bin',['habe','hat'],'Fahren mit Ortswechsel bildet das Perfekt mit sein.'),gap('Am Abend habe ich … .','gekocht',['kochen','kochte'],'Das Perfekt braucht ein Partizip: gekocht.'),gap('Wir … unsere Freunde besucht.','haben',['sind','ist'],'Besuchen bildet das Perfekt mit haben.')],
gesundheit:[gap('Noor … die Karte mitbringen.','soll',['sollen','sollst'],'Noor ist eine Person: sie soll.'),gap('Ich … den Termin absagen.','muss',['musst','müssen'],'Bei ich heißt es muss.'),gap('Du … heute zu Hause bleiben.','sollst',['soll','sollen'],'Bei du lautet die Form sollst.')],
unterwegs:[gap('Ich warte an … Haltestelle.','der',['die','den'],'Wo? verlangt hier Dativ: an der Haltestelle.'),gap('Ich gehe in … Park.','den',['dem','der'],'Wohin? verlangt hier Akkusativ: in den Park.'),gap('Das Auto steht vor … Haus.','dem',['das','den'],'Wo? verlangt Dativ: vor dem Haus.')],
schule:[gap('Mein Kind fehlt, weil es krank … .','ist',['sein','sind'],'Nach weil steht das konjugierte Verb am Ende.'),gap('Könnten Sie … bitte die Aufgaben schicken?','mir',['ich','mich'],'Die empfangende Person steht bei schicken im Dativ.'),gap('Ich komme später, weil der Bus nicht … .','fährt',['fahren','fahre'],'Der Bus ist Singular: er fährt.')],
reklamation:[gap('Der Drucker, … ich gekauft habe, ist kaputt.','den',['der','dem'],'Im Relativsatz ist der Drucker Akkusativobjekt.'),gap('Die Schuhe, … ich bestellt habe, sind zu klein.','die',['den','der'],'Das Relativpronomen im Akkusativ Plural lautet die.'),gap('Das Gerät, … gestern angekommen ist, funktioniert.','das',['dem','den'],'Das Gerät ist das Subjekt des Relativsatzes.')],
meinung:[gap('Ich bin müde. Trotzdem … ich weiter.','lerne',['lernen','lernst'],'Nach trotzdem steht das Verb auf Position 2.'),gap('Obwohl es regnet, … wir spazieren.','gehen',['geht','gehst'],'Subjekt wir verlangt gehen.'),gap('Meiner Meinung … ist das hilfreich.','nach',['zu','mit'],'Die feste Formulierung lautet meiner Meinung nach.')],
arbeit:[gap('Ich lerne Deutsch, … eine Stelle zu finden.','um',['weil','obwohl'],'Um … zu drückt einen Zweck aus.'),gap('Ich interessiere mich … die Stelle.','für',['an','mit'],'Sich interessieren verbindet sich mit für.'),gap('Ich bewerbe mich … die Stelle als Koch.','um',['für','zu'],'Sich um eine Stelle bewerben ist die passende Verbindung.')],
planen:[gap('Wir … ein Frühstück organisieren.','könnten',['könntest','könnte'],'Bei wir lautet der Konjunktiv II könnten.'),gap('Wie wäre es … Samstag?','mit',['für','bei'],'Die Vorschlagsformel lautet Wie wäre es mit …?'),gap('Das … eine gute Idee.','ist',['sind','sein'],'Das verlangt hier die Singularform ist.')],
'bewerbung-b2':[gap('Ich möchte Verantwortung … .','übernehmen',['treffen','machen'],'Verantwortung übernehmen ist eine feste Verbindung.'),gap('Ich bin … die Terminplanung zuständig.','für',['um','an'],'Zuständig wird mit für verbunden.'),gap('Im Praktikum habe ich Erfahrung … .','gesammelt',['getroffen','gemacht'],'Man sammelt Erfahrung.')],
'beschwerde-b2':[gap('Die Lieferung … morgen geprüft.','wird',['hat','werden'],'Vorgangspassiv Singular: wird + Partizip II.'),gap('Die fehlenden Teile werden morgen … .','versendet',['versenden','versandten'],'Das Passiv benötigt das Partizip versendet.'),gap('Wir bitten … Entschuldigung.','um',['für','an'],'Die feste Verbindung lautet um Entschuldigung bitten.')],
'forum-b2':[gap('Einerseits sparen wir Zeit, … fehlt der Austausch.','andererseits',['trotz','sowohl'],'Einerseits und andererseits stellen zwei Seiten gegenüber.'),gap('Das ist zwar praktisch, … auch teuer.','aber',['oder','denn'],'Die feste Verbindung lautet zwar … aber.'),gap('Ich schlage vor, … wir feste Zeiten vereinbaren.','dass',['weil','obwohl'],'Der dass-Satz benennt den Inhalt des Vorschlags.')],
'loesungen-b2':[gap('Falls die Ware rechtzeitig …, können wir beginnen.','ankommt',['kommt an','ankommen'],'Im falls-Satz steht das Verb am Ende.'),gap('Wir müssen eine Entscheidung … .','treffen',['machen','nehmen'],'Man trifft eine Entscheidung.'),gap('Ich informiere die Leitung … 15 Uhr.','bis',['seit','ab'],'Bis nennt den spätesten Zeitpunkt der Handlung.')],
kleidung:[gap('Die Frau trägt eine … Jacke.','schwarze',['schwarzen','schwarzer'],'Nach eine im Akkusativ Femininum steht -e.'),gap('Der Mann trägt einen … Pullover.','roten',['roter','rote'],'Nach einen im Akkusativ Maskulinum steht -en.'),gap('Das Kind mit dem … T-Shirt lacht.','blauen',['blaue','blaues'],'Nach mit dem im Dativ steht -en.')]
};
function sceneFor(id){const n=pick(P_NAMES),city=pick(P_CITY),day=pick(P_DAY),hour=pick([9,10,11,14,15,16,17]),count=pick([2,3,4,5,6]),job=pick(['Koch','Verkäufer','Hausmeister','Fahrer']),food=pick(['Brot','Reis','Obst','Gemüse']),place=pick(['Bahnhof','Rathaus','Supermarkt','Kino']);let text,a,q;
switch(id){
case 'ankommen':text=`${n} wohnt in ${city}. Der Deutschkurs beginnt am ${day} um ${hour} Uhr. Nach dem Kurs lernt ${n} zu Hause weiter.`;q='In welcher Stadt wohnt die Person?';a=city;break;
case 'einkaufen':text=`${n} kauft ${count} Brote. Ein Brot kostet ${pick([2,3,4])} Euro. Außerdem braucht ${n} ${food==='Brot'?'Milch':food}. Der Laden schließt um ${hour+3} Uhr.`;q='Wie viele Brote kauft die Person? Antworte mit einer Zahl.';a=String(count);break;
case 'termine':text=`${n} hat am ${day} um ${hour} Uhr einen Termin. Die Praxis liegt in ${city}. Die Mitarbeiterin bittet darum, zehn Minuten früher zu kommen.`;q='An welchem Wochentag ist der Termin?';a=day;break;
case 'wohnen':text=`${n} sucht eine Wohnung in ${city}. Sie soll ${count} Zimmer haben. Ein Balkon ist wichtig, eine Garage wird nicht gebraucht.`;q='Wie viele Zimmer soll die Wohnung haben? Antworte mit einer Zahl.';a=String(count);break;
case 'alltag':text=`Gestern ist ${n} nach ${city} gefahren. Dort hat ${n} ${food} gekauft. Am Abend hat ${n} Deutsch gelernt und eine Freundin angerufen.`;q='In welche Stadt ist die Person gefahren?';a=city;break;
case 'gesundheit':text=`${n} kann am ${day} nicht zum Kurs kommen. Seit ${count} Tagen bestehen Halsschmerzen. Der Termin in der Praxis ist um ${hour} Uhr.`;q='Seit wie vielen Tagen bestehen die Beschwerden? Antworte mit einer Zahl.';a=String(count);break;
case 'unterwegs':text=`Wegen Bauarbeiten fährt der Bus heute nicht zum Bahnhof. Die Ersatzhaltestelle liegt am ${place==='Bahnhof'?'Rathaus':place}. ${n} fährt um ${hour} Uhr ab. Die Fahrt nach ${city} dauert 30 Minuten.`;q='Um wie viel Uhr fährt die Person ab? Schreibe nur die Zahl.';a=String(hour);break;
case 'schule':text=`Die Klasse macht am ${day} einen Ausflug nach ${city}. Treffpunkt ist um ${hour} Uhr am Schultor. Alle bringen Wasser und eine Regenjacke mit.`;q='Wohin fährt die Klasse?';a=city;break;
case 'reklamation':text=`${n} hat vor ${count} Tagen einen Drucker bestellt. Das Gerät druckt nur leere Seiten. Die Lieferung kam aus ${city}. ${n} bittet um ein Ersatzgerät.`;q='Vor wie vielen Tagen wurde der Drucker bestellt? Schreibe die Zahl.';a=String(count);break;
case 'meinung':text=`Im Kurs in ${city} diskutieren die Teilnehmenden über Onlineunterricht. ${n} findet ihn praktisch, weil die Fahrt entfällt. Ein persönliches Treffen soll jeden ${day} stattfinden.`;q='An welchem Wochentag ist ein persönliches Treffen vorgesehen?';a=day;break;
case 'arbeit':text=`Ein Betrieb in ${city} sucht einen ${job}. Die Arbeitszeit beginnt um ${hour} Uhr. Bewerbungen sollen per E-Mail geschickt werden. Berufserfahrung ist erwünscht.`;q='Welche Stelle ist ausgeschrieben?';a=job;break;
case 'planen':text=`${n} plant mit dem Kurs ein Frühstück am ${day}. Es beginnt um ${hour} Uhr. Jede Person gibt ${count} Euro dazu. ${n} bringt ${food} mit.`;q='Wie viel gibt jede Person dazu? Schreibe nur die Zahl.';a=String(count);break;
case 'bewerbung-b2':text=`${n} bewirbt sich bei einem Unternehmen in ${city}. Nach ${count} Jahren Berufserfahrung möchte ${n} mehr Verantwortung übernehmen. Das Vorstellungsgespräch findet am ${day} um ${hour} Uhr statt.`;q='Wie viele Jahre Berufserfahrung werden genannt? Schreibe die Zahl.';a=String(count);break;
case 'beschwerde-b2':text=`Bei einer Lieferung nach ${city} fehlen ${count} Stühle. Der Versand der fehlenden Stühle ist für ${day} bestätigt. Ob eine frühere Zustellung möglich ist, wird noch geprüft. ${n} beantwortet die Kundenmail.`;q='Für welchen Tag ist der Versand bestätigt?';a=day;break;
case 'forum-b2':text=`Das Team in ${city} diskutiert neue Arbeitszeiten. ${n} möchte an ${count} Tagen pro Woche früher beginnen. Ein Vorteil wäre mehr freie Zeit am Nachmittag. Die Kundenbetreuung muss bis ${hour+2} Uhr besetzt bleiben.`;q='An wie vielen Tagen möchte die Person früher beginnen? Schreibe die Zahl.';a=String(count);break;
case 'loesungen-b2':text=`Für eine Veranstaltung in ${city} fehlen ${count*10} Namensschilder. ${n} organisiert Papier. Die Datei muss bis ${hour} Uhr fertig sein. Danach übernimmt ein Kollege den Druck.`;q='Bis wie viel Uhr muss die Datei fertig sein? Schreibe nur die Zahl.';a=String(hour);break;
case 'kleidung':{const color=pick(['rote','blaue','grüne','graue','schwarze']);text=`Stell dir diese Szene vor: ${n} trägt eine ${color} Jacke und weiße Schuhe. Daneben stehen ${count} Personen. Sie warten am ${place}.`;q='Welche Farbe hat die Jacke? Schreibe die Grundform.';a={rote:'rot',blaue:'blau',grüne:'grün',graue:'grau',schwarze:'schwarz'}[color];break;}
}
return {text,q,a,n,day,city,hour,count};}
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const normal=s=>String(s).toLocaleLowerCase('de').trim().replace(/[.!?,;:]/g,'').replace(/\s+/g,' ');
function freshPractice(id,difficulty='same'){let prev=practiceState.get(id),s;do{s=sceneFor(id);}while(prev&&s.text===prev.text);let bank=grammarBank[id],g=bank[Math.floor(Math.random()*bank.length)];if(prev&&g===prev.g)g=bank[(bank.indexOf(g)+1)%bank.length];let wrongs=/^\d+$/.test(s.a)?[String(Number(s.a)+1),String(Number(s.a)+2)]:P_CITY.includes(s.a)?P_CITY.filter(x=>x!==s.a).slice(0,2):P_DAY.includes(s.a)?P_DAY.filter(x=>x!==s.a).slice(0,2):['rot','blau','grün','grau','schwarz'].includes(s.a)?['rot','blau','grün','grau','schwarz'].filter(x=>x!==s.a).slice(0,2):['Koch','Verkäufer','Hausmeister','Fahrer'].filter(x=>x!==s.a).slice(0,2);const sentence=g.s.replace('…',g.a).replace(/\s+\./g,'.');let questions=[{q:s.q,a:s.a,opts:shuffle([s.a,...wrongs]),why:`Die gesuchte Angabe im Text ist „${s.a}“.`,type:difficulty==='hard'?'input':'choice'},{q:'Ergänze: '+g.s,a:g.a,opts:shuffle([g.a,...g.options]),why:g.why,type:difficulty==='easy'?'choice':'input'},{q:difficulty==='easy'?'Welche Aussage passt zum Text?':'Bilde den Satz. Beginne mit „'+sentence.split(' ').slice(0,2).join(' ')+'“. Verwende alle Wörter: '+shuffle(sentence.replace(/[.?!]/g,'').split(' ')).join(' / '),a:difficulty==='easy'?s.text.split('. ')[0]+'.':sentence,opts:shuffle([s.text.split('. ')[0]+'.','Alle Angaben fehlen.','Die Situation wird nicht beschrieben.']),why:difficulty==='easy'?'Diese Aussage entspricht dem ersten Satz des Textes.':`Eine passende Lösung lautet: ${sentence}`,type:difficulty==='easy'?'choice':'input'}];let r={...s,g,questions,difficulty,round:(prev?.round||0)+1,task:difficulty==='easy'?`Schreibe zwei Sätze über die neue Situation. Verwende den Namen ${s.n}.`:`Schreibe ${difficulty==='hard'?'sechs bis acht':'vier'} zusammenhängende Sätze zur neuen Situation. Verwende ${s.n} und die Angaben aus dem Text. Ergänze ${difficulty==='hard'?'eine Begründung und eine höfliche Frage':'eine passende Frage'}.`,model:s.text+' Welche weiteren Informationen brauchen Sie?',checks:['Ich habe die Angaben aus der aktuellen Situation verwendet.','Mein Text ist verständlich.','Ich habe eine eigene Frage ergänzt.']};practiceState.set(id,r);attempts.delete(id);drafts.delete(id);return r;}
function currentPractice(id){return practiceState.get(id)||freshPractice(id);}
const legacyQuiz=quiz,legacyBindQuiz=bindQuiz,legacyWriting=writing;
quiz=function(qs,id){if(!grammarBank[id])return legacyQuiz(qs,id);let r=currentPractice(id);return `<div class="practice-switch"><label class="muted" for="difficulty">Schwierigkeit</label><select id="difficulty"><option value="easy" ${r.difficulty==='easy'?'selected':''}>Leichter</option><option value="same" ${r.difficulty==='same'?'selected':''}>Gleich schwer</option><option value="hard" ${r.difficulty==='hard'?'selected':''}>Schwieriger</option></select><button class="btn secondary" id="new-practice" type="button">Andere Übung ↻</button></div><p class="round-note">Übungsrunde ${r.round} · Neue Situation und Aufgaben zum selben Thema</p><form id="quiz" novalidate>${r.questions.map((q,i)=>`<fieldset><legend>${i+1}. ${esc(q.q)}</legend>${q.type==='choice'?q.opts.map(o=>`<label class="option"><input type="radio" name="q${i}" value="${esc(o)}"><span>${esc(o)}</span></label>`).join(''):`<label class="muted" for="answer-${i}">Deine Antwort</label><input class="input-answer" id="answer-${i}" type="text" name="q${i}" autocomplete="off">`}<div id="f${i}" class="feedback"></div></fieldset>`).join('')}<div class="actions"><button class="btn" type="submit">Antworten prüfen</button><button class="btn secondary" id="reset" type="button">Neu versuchen</button></div><p id="score" role="status" aria-live="polite"></p><button class="btn secondary" hidden id="next-round" type="button">Fertig? Neue Runde →</button></form>`;};
bindQuiz=function(qs,id){if(!grammarBank[id])return legacyBindQuiz(qs,id);let f=document.querySelector('#quiz');if(!f)return;let r=currentPractice(id);const change=()=>{freshPractice(id,document.querySelector('#difficulty').value);route();};document.querySelector('#new-practice').onclick=change;document.querySelector('#difficulty').onchange=change;document.querySelector('#next-round').onclick=change;f.onsubmit=e=>{e.preventDefault();let points=0,filled=0;r.questions.forEach((q,i)=>{let value=new FormData(f).get('q'+i)||'',ok=normal(value)===normal(q.a);if(value.trim())filled++;if(ok)points++;let el=document.querySelector('#f'+i);el.className='feedback '+(ok?'good':'bad');el.textContent=value.trim()?`${ok?'Richtig.':'Noch nicht richtig.'} ${q.type==='input'?'Lösung: '+q.a+'. ':''}${q.why}`:'Bitte gib eine Antwort ein.';});document.querySelector('#score').textContent=filled<3?`${filled} von 3 Aufgaben beantwortet.`:`${points} von 3 richtig. Du kannst weiterüben oder eine neue Runde beginnen.`;document.querySelector('#next-round').hidden=filled<3;};document.querySelector('#reset').onclick=()=>{f.reset();f.querySelectorAll('.feedback').forEach(x=>x.textContent='');document.querySelector('#score').textContent='Versuche es noch einmal.';document.querySelector('#next-round').hidden=true;};};
writing=function(u,id){if(!grammarBank[id])return legacyWriting(u,id);let r=currentPractice(id);return `<p class="context">${esc(r.text)}</p><div class="practice-switch"><label for="writing-difficulty">Schwierigkeit</label><select id="writing-difficulty"><option value="easy" ${r.difficulty==='easy'?'selected':''}>Leichter</option><option value="same" ${r.difficulty==='same'?'selected':''}>Gleich schwer</option><option value="hard" ${r.difficulty==='hard'?'selected':''}>Schwieriger</option></select><button class="btn secondary" id="new-writing">Andere Übung ↻</button></div>`+legacyWriting({...u,...r,modelLabel:'Beispielanfang ansehen und selbst ergänzen'},id);};
const bindPracticeWriting=bindWriting;
bindWriting=function(id){bindPracticeWriting(id);if(!grammarBank[id]||!document.querySelector('#new-writing'))return;const change=()=>{freshPractice(id,document.querySelector('#writing-difficulty').value);route();};document.querySelector('#new-writing').onclick=change;document.querySelector('#writing-difficulty').onchange=change;};
