/* Ring-binder vocabulary, word dossiers and reusable learning games. */
const vocabLanguages={uk:'Українська · Ukrainisch',de:'Deutsch',ar:'العربية',fa:'فارسی',ru:'Русский',tr:'Türkçe',zh:'中文',en:'English',it:'Italiano',es:'Español'};
const lowLevel=l=>['A1','A2'].includes(l.level);
const vwords=l=>lessonWords[l.id].map(key=>({...wordLibrary[key],key}));
const vshuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
let vocabLanguage='de';
const vlangSelect=l=>lowLevel(l)?`<label class="v-language">Wortübersetzung <select id="v-language">${Object.entries(vocabLanguages).map(([k,v])=>`<option value="${k}" ${k===vocabLanguage?'selected':''}>${v}</option>`).join('')}</select></label>`:'<p class="muted">Ab B1: Bedeutungen und Beispiele auf Deutsch.</p>';
const vtranslation=(l,w)=>lowLevel(l)&&vocabLanguage!=='de'?`<p class="v-translation" lang="${vocabLanguage}" dir="${['ar','fa'].includes(vocabLanguage)?'rtl':'ltr'}">${esc(wordTranslations[w.key]?.[vocabLanguage]||'')}</p>`:'';
const vlink=(l,w)=>`#wort/${l.id}/${encodeURIComponent(w.key)}`;
function vcard(l,w){return `<a class="v-card ${w.pos==='Verb'?'v-verb':w.pos==='Adjektiv'?'v-adj':'v-noun'}" href="${vlink(l,w)}"><small>${w.pos}</small><strong>${esc(w.word)}</strong><span>${esc(w.pos==='Verb'?`ich ${w.forms[0]} · ${w.hint}`:w.hint)}</span>${vtranslation(l,w)}<em>Grammatik & Beispiele ↗</em></a>`;}
function vnav(l,active){return `<nav class="v-tabs" aria-label="Wortschatzseiten">${['Nomen','Verben','Adjektive','Lernkarten','Bild & Wort','Satzbau'].map((x,i)=>`<a ${active===i?'aria-current="page"':''} href="#wortschatz/${l.id}/${i}">${x}</a>`).join('')}<a href="#lektion/${l.id}">Zur Lektion ↗</a></nav>`;}
const oldVocabularyLesson=lesson;
lesson=function(id){const l=lessons.find(x=>x.id===id);if(l&&(!lowLevel(l)||!vocabLanguages[language]))language='de';oldVocabularyLesson(id);if(!l||!lessonWords[id])return;const toolbar=document.createElement('div');toolbar.className='v-entry';toolbar.innerHTML=`<div><b>20 Wörter. Viele neue Sätze.</b><span>8 Nomen · 6 Verben · 6 Adjektive · Grammatik zum Aufklappen</span></div><a class="btn" href="#wortschatz/${id}/0">Wortschatz entdecken →</a>`;main.querySelector('.book-top')?.after(toolbar);const tags=main.querySelector('.word-tags');if(tags)tags.innerHTML=vwords(l).map(w=>`<a href="${vlink(l,w)}">${esc(w.word)}</a>`).join('');const table=main.querySelector('.vocab');if(table){table.insertAdjacentHTML('afterend',`<a class="btn secondary" href="#wortschatz/${id}/0">Alle 20 Wortkarten & Lernspiele →</a>`);}const sel=main.querySelector('#book-language');if(sel){if(!lowLevel(l)){sel.closest('label')?.remove();sel.previousElementSibling?.matches('label')&&sel.previousElementSibling.remove();sel.hidden=true;}else [...sel.options].forEach(o=>{if(!vocabLanguages[o.value])o.remove();});}};
function bindVLanguage(l){const s=document.querySelector('#v-language');if(s)s.onchange=()=>{vocabLanguage=s.value;route();};}
function vocabBook(id,raw=0){const l=lessons.find(x=>x.id===id);if(!l)return missing();level=l.level;let step=Math.max(0,Math.min(5,Number(raw)||0));const ws=vwords(l),titles=['Nomen sammeln','Verben in Bewegung','Eigenschaften entdecken','Dreh die Karte um.','Vom Bild zum Wort.','Baue deinen Satz.'];const sections=[()=>`<p>Merke dir immer den Artikel und die Pluralform. Ein Nomen kann im Satz zum Beispiel Subjekt oder Objekt sein.</p><div class="v-grid">${ws.filter(w=>w.pos==='Nomen').map(w=>vcard(l,w)).join('')}</div>`,()=>`<p>Was macht jemand? Öffne eine Karte: Du findest Konjugation, Satzmuster und passende Präpositionen.</p><div class="v-grid">${ws.filter(w=>w.pos==='Verb').map(w=>vcard(l,w)).join('')}</div>`,()=>`<p>Wie ist etwas? Vergleiche Eigenschaften und finde Gegensätze.</p><div class="v-grid">${ws.filter(w=>w.pos==='Adjektiv').map(w=>vcard(l,w)).join('')}</div>`,()=>gameShell('flash',l),()=>gameShell('picture',l),()=>gameShell('sentence',l)];const left=page(`<span class="tape-label">${l.level} · ${l.title}</span><h1>${titles[step]}</h1>${vlangSelect(l)}${sections[step]()}`,step+1,'WORTSCHATZ');const right=page(`<span class="step-label">Dein Wörteratelier</span><h2>Entdecken.<br>Verstehen. Anwenden.</h2>${vnav(l,step)}${teacherTip(step<3?'Lerne Wörter zusammen mit einem Satz. Öffne ein Wort und finde heraus, wie du es selbst verwenden kannst.':'Probiere zuerst ohne Hilfe. Eine neue Runde mischt die Aufgaben neu. Wörter, die du schon kannst, kannst du noch einmal im Satz verwenden.')}<img class="lesson-art" src="assets/${artFor(l)}.png" alt="${altFor(artFor(l))}"><a class="btn secondary" href="material/wortschatz-${id}.pdf" download>20 Wörter & Grammatik als PDF ↓</a><p class="muted">Die Übungen verwenden die Wörter dieser Lektion. Wähle eine neue Runde oder ändere den Schwierigkeitsgrad.</p>`, '','LERNWEG');bookFrame(left,mq.matches?'':right,{title:`${l.level} / Wortschatz / ${l.title}`,prev:step?`#wortschatz/${id}/${step-1}`:`#lektion/${id}`,next:step<5?`#wortschatz/${id}/${step+1}`:`#lektion/${id}/2`});if(mq.matches){main.querySelector('.book-top').insertAdjacentHTML('afterend',vnav(l,step));main.querySelector('.paper').insertAdjacentHTML('beforeend',`<a class="btn secondary" href="material/wortschatz-${id}.pdf" download>20 Wörter & Grammatik als PDF ↓</a>`);}bindVLanguage(l);bindGame(l,['','','','flash','picture','sentence'][step]);}
function wordGrammar(l,w){if(w.pos==='Nomen')return `<h3>Artikel & Plural</h3><p class="v-big">${esc(w.word)} → ${esc(w.plural)}</p><p>Der Artikel gehört zum Nomen. Im Satz hängt der Fall von der Funktion und der Präposition ab.</p>${l.level==='B2'&&w.key==='Kunde'?'<p><b>n-Deklination:</b> der Kunde → den Kunden → dem Kunden → des Kunden.</p>':''}`;if(w.pos==='Adjektiv')return `<h3>Eigenschaft & Gegensatz</h3><p class="v-big">${esc(w.word)} ↔ ${esc(w.opposite)}</p><p>Nach „sein“ bleibt das Adjektiv ohne Endung: ${esc(w.example)}</p>${l.level==='A1'?'':`<h3>Vergleichen</h3><p>${esc(w.comparison)}</p><p>Vor einem Nomen kann das Adjektiv eine Endung bekommen. Sie hängt von Artikel, Fall, Genus und Zahl ab.</p>`}`;return `<h3>Präsens · Wer macht etwas?</h3><table class="v-forms"><tbody>${['ich','du','er / sie / es','wir','ihr','sie / Sie'].map((p,i)=>`<tr><th>${p}</th><td>${esc(w.forms[i])}</td></tr>`).join('')}</tbody></table>${l.level!=='A1'?`<h3>Vergangenheit</h3><p><b>Perfekt:</b> er/sie ${esc(w.perf)}</p>${['B1','B2'].includes(l.level)?`<p><b>Präteritum:</b> er/sie ${esc(w.past)}</p>`:''}`:''}<h3>Mit welchen Wörtern?</h3><p class="v-pattern">${esc(w.prep)}</p>`;}
function wordBook(id,key){const l=lessons.find(x=>x.id===id),w=wordLibrary[key];if(!l||!w||!lessonWords[id]?.includes(key))return missing();level=l.level;const item={...w,key},ws=vwords(l),idx=lessonWords[id].indexOf(key);const explanation=page(`<span class="tape-label">${l.level} · ${w.pos} · Wort ${idx+1}/20</span><h1>${esc(w.word)}</h1>${vlangSelect(l)}${vtranslation(l,item)}<p class="v-definition">${esc(w.meaning)}</p>${wordGrammar(l,w)}`,idx+1,'WORT GENAU');const examples=page(`<span class="step-label">Verstehen & selbst verwenden</span><h2>Ein Wort wird<br>zu deinem Satz.</h2><div class="notebook"><p class="example">${esc(w.example)}</p>${w.example2?`<p class="example">${esc(w.example2)}</p>`:""}</div><h3>Entdecke das Muster</h3><p>${esc(w.pos==='Verb'?w.prep:w.pos==='Nomen'?'Suche das Nomen im Satz. Ist es ein Subjekt, ein Objekt oder Teil einer Orts- oder Zeitangabe?':'Was wird im Beispiel beschrieben? Ersetze das Adjektiv durch sein Gegenteil. Passt der Satz noch?')}</p>${l.level==='B2'?`<p class="v-pattern">Beruflicher Transfer: Verwende „${esc(w.word)}“ in einer Nachricht an dein Team. Begründe deinen Vorschlag und ergänze einen konkreten nächsten Schritt.</p>`:''}<h3>Jetzt du</h3><label for="v-own">Schreibe einen eigenen Satz mit „${esc(w.word)}“.</label><textarea id="v-own" rows="3" placeholder="Mein Beispielsatz …"></textarea><details class="v-help"><summary>So überprüfst du deinen Satz</summary><p>Steht das konjugierte Verb im Aussagesatz an zweiter Position? Stimmen Artikel und Fall? Vergleiche dein Satzmuster mit dem Beispiel. Dein eigener Satz wird hier nicht automatisch bewertet.</p></details>${teacherTip('Verändere eine Information im Beispiel: Person, Ort oder Zeit. Lies deinen neuen Satz laut vor.')}<a class="btn secondary" href="#wortschatz/${id}/${w.pos==='Nomen'?0:w.pos==='Verb'?1:2}">Zurück zu den Wortkarten</a>`, '','ANWENDEN');bookFrame(explanation,mq.matches?'':examples,{title:`${l.title} / ${w.word}`,prev:idx?vlink(l,ws[idx-1]):`#wortschatz/${id}/0`,next:idx<19?vlink(l,ws[idx+1]):`#wortschatz/${id}/3`});if(mq.matches)main.querySelector('.spread').insertAdjacentHTML('beforeend',examples);bindVLanguage(l);const own=document.querySelector('#v-own'),storage=`word-draft:${id}:${key}`;if(own){own.value=sessionStorage.getItem(storage)||'';own.oninput=()=>sessionStorage.setItem(storage,own.value);}}
const gameState={};
function gameShell(type,l){return `<div class="v-game" data-game="${type}"><div class="v-game-controls"><label>Schwierigkeit <select id="v-difficulty"><option value="easy">Leichter</option><option value="same" selected>Gleich schwer</option><option value="hard">Schwieriger</option></select></label><button class="btn secondary" id="v-new">Neue Runde ↻</button></div><div id="v-game-body"></div><p id="v-feedback" role="status" aria-live="polite"></p></div>`;}
const picturePrompts={
ankommen:[['alltag','sprechen','Welche Tätigkeit passt zu den zwei Menschen rechts im Gespräch?'],['alltag','Stadt','Viele Häuser, Geschäfte und Verkehr: Welcher Ort ist dargestellt?']],
einkaufen:[['sprechen/markt','Apfel','Welche runde Frucht wird hier gekauft?'],['sprechen/kueche','Gemüse','Wie heißt der Sammelbegriff für die Zutaten, die hier geschnitten werden?']],
termine:[['sprechen/bus','warten','Was tun die Menschen an der Haltestelle, bevor sie einsteigen?'],['sprechen/arzt','Termin','Für den Arztbesuch vereinbart man eine feste Zeit. Wie heißt sie?']],
wohnen:[['sprechen/kueche','Küche','In welchem Raum bereiten die Menschen das Essen zu?'],['beruf','Tisch','Auf welchem Möbelstück liegen die Unterlagen der Besprechung?']],
alltag:[['sprechen/kueche','kochen','Welche Tätigkeit passt zur gemeinsamen Zubereitung des Essens?'],['sprechen/bus','Bus','Welches Verkehrsmittel kommt zur Haltestelle?']],
gesundheit:[['sprechen/arzt','Ärztin','Wie heißt der Beruf der Frau im weißen Kittel?'],['sprechen/arzt','helfen','Die Ärztin unterstützt den Patienten. Welches Verb passt?']],
unterwegs:[['sprechen/bus','Haltestelle','An welchem Ort warten die Menschen auf den Bus?'],['sprechen/bus','Bus','Welches Fahrzeug nähert sich den Wartenden?']],
schule:[['sprechen/park','Kind','Wie nennt man den jungen Menschen mit dem Ball?'],['beruf','erklären','Eine Person macht dem Team eine Aufgabe verständlich. Welches Verb passt zur Situation?']],
reklamation:[['beruf','Lieferung','Die Kartons enthalten bestellte Waren. Wie nennt man das Bringen dieser Waren?'],['beruf','prüfen','Vor dem Versand werden die Kartons auf Schäden kontrolliert. Welches Verb passt?']],
meinung:[['beruf','diskutieren','Das Team tauscht verschiedene Ansichten aus. Welches Verb passt?'],['beruf','Meinung','Eine Person sagt: „Ich finde die Idee gut.“ Was äußert sie?']],
arbeit:[['beruf','Team','Wie nennt man die Gruppe, die zusammenarbeitet?'],['beruf','Gespräch','Wie nennt man den mündlichen Austausch am Tisch?']],
planen:[['sprechen/park','Ausflug','Die Gruppe verbringt gemeinsam einen Tag im Park. Wie heißt eine solche kurze Unternehmung?'],['beruf','planen','Die Gruppe überlegt, wie das nächste Treffen stattfinden soll. Welches Verb passt?']],
kleidung:[['kleidung','Jacke','Welches schwarze Kleidungsstück trägt die Frau am Oberkörper?'],['kleidung','Pullover','Welches rote Kleidungsstück trägt der Mann?'],['kleidung','Hose','Welches blaue Kleidungsstück trägt die Frau an den Beinen?']],
'bewerbung-b2':[['beruf','Verantwortung','Die Leitung steht für die Aufgaben und ihre Folgen ein. Was übernimmt sie?'],['beruf','teilnehmen','Eine Mitarbeiterin ist bei der Besprechung dabei. Welches Verb verwendet man mit „an + Dativ“?']],
'beschwerde-b2':[['beruf','prüfen','Das Team kontrolliert eine Lieferung auf Fehler. Welches Verb passt?'],['beruf','Rückmeldung','Nach dem Gespräch erhält die Kundin eine Antwort. Welches Nomen passt?']],
'forum-b2':[['beruf','diskutieren','Die Beschäftigten tauschen Argumente über neue Arbeitszeiten aus. Welches Verb passt?'],['beruf','Kompromiss','Bei der Einigung geben beide Seiten etwas nach. Wie heißt diese Lösung?']],
'loesungen-b2':[['beruf','festlegen','Das Team bestimmt verbindlich den Abgabetermin. Welches Verb passt?'],['beruf','Qualität','Die gelieferten Waren werden auf ihre Güte untersucht. Was kontrolliert das Team?']]
};
function bindGame(l,type){if(!type)return;const body=document.querySelector('#v-game-body'),feedback=document.querySelector('#v-feedback'),difficulty=document.querySelector('#v-difficulty');let bag=[],last=null,selected=[],cursor=0;const state=gameState[l.id+type]||(gameState[l.id+type]={difficulty:'same'});difficulty.value=state.difficulty;const nextWord=()=>{if(!bag.length){bag=vshuffle(vwords(l));if(bag.length>1&&bag.at(-1).key===last)bag.unshift(bag.pop());}const w=bag.pop();last=w.key;return w;};function round(){feedback.textContent='';selected=[];const d=difficulty.value;state.difficulty=d;
if(type==='flash'){const w=nextWord();body.innerHTML=`<p class="muted">${20-bag.length}/20 · Erst überlegen, dann umdrehen</p><button class="v-flash" id="v-flip" aria-expanded="false"><small>${w.pos}</small><strong>${esc(d==='hard'?w.meaning:w.word)}</strong><span>Antwort aufdecken ↻</span></button><div id="v-answer" hidden><h3>${esc(w.word)}</h3><p>${esc(w.meaning)}</p>${vtranslation(l,w)}<p class="v-pattern">${esc(w.hint)}</p><p>${esc(w.example)}</p><a href="${vlink(l,w)}">Grammatik ansehen ↗</a><div class="v-game-controls"><button class="btn" id="v-known">Gewusst →</button><button class="btn secondary" id="v-again">Noch einmal üben</button></div></div>`;document.querySelector('#v-flip').onclick=e=>{document.querySelector('#v-answer').hidden=false;document.querySelector('#v-flip').setAttribute('aria-expanded','true');};document.querySelector('#v-known').onclick=round;document.querySelector('#v-again').onclick=()=>{bag.unshift(w);round();};}
if(type==='picture'){const prompts=picturePrompts[l.id];const p=prompts[cursor++%prompts.length],w={...wordLibrary[p[1]],key:p[1]};const choices=vshuffle([w,...vshuffle(vwords(l).filter(x=>x.key!==w.key)).slice(0,d==='easy'?1:d==='hard'?5:3)]);body.innerHTML=`<img class="v-game-image" src="assets/${p[0]}.png" alt="${p[0]==='kleidung'?altFor('kleidung'):p[0]==='beruf'?altFor('beruf'):p[0]==='alltag'?altFor('alltag'):{'sprechen/markt':'Eine Kundin kauft auf einem Markt einen Apfel.','sprechen/kueche':'Zwei Erwachsene bereiten Gemüse in einer Küche zu.','sprechen/bus':'Menschen warten an einer Haltestelle auf einen Bus.','sprechen/arzt':'Eine Ärztin untersucht einen Patienten.','sprechen/park':'Erwachsene und ein Kind mit einem Ball im Park.'}[p[0]]}"><p><b>${esc(p[2])}</b></p><div class="v-options">${choices.map(x=>`<button class="btn secondary" data-answer="${esc(x.key)}">${esc(x.word)}</button>`).join('')}</div>`;body.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(b.dataset.answer===w.key){feedback.textContent=`Richtig: ${w.word}. ${w.meaning}`;body.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);}else{feedback.textContent='Noch nicht. Lies den Hinweis und betrachte die Szene noch einmal.';b.disabled=true;}});}
if(type==='sentence'){const w=nextWord();let chunks=w.example.replace(/\.$/,'').split(' ');if(d==='easy'){const grouped=[];for(let i=0;i<chunks.length;i+=2)grouped.push(chunks.slice(i,i+2).join(' '));chunks=grouped;}const needed=chunks.length;if(d==='hard')chunks.push('obwohl','trotzdem');const order=vshuffle(chunks.map((text,i)=>({text,i})));body.innerHTML=`<p>Baue den Beispielsatz. Beginne mit <b>„${esc(chunks[0])}“</b>. ${d==='hard'?'Zwei Bausteine bleiben übrig.':''}</p>${d==='easy'?`<p class="muted">Lernwort: ${esc(w.word)} · ${esc(w.meaning)}</p>`:''}<div class="v-sentence" id="v-built" aria-live="polite">Dein Satz …</div><div class="v-options">${order.map(c=>`<button class="btn secondary" data-chunk="${c.i}">${esc(c.text)}</button>`).join('')}</div><div class="v-game-controls"><button class="btn" id="v-check">Prüfen</button><button class="btn secondary" id="v-reset">Zurücksetzen</button></div><details class="v-help"><summary>Hinweis zum Satzbau</summary><p>${esc(w.pos==='Verb'?w.prep:'Im Aussagesatz steht das konjugierte Verb an zweiter Position.')}</p></details>`;const built=document.querySelector('#v-built');body.querySelectorAll('[data-chunk]').forEach(b=>b.onclick=()=>{selected.push(Number(b.dataset.chunk));b.disabled=true;built.textContent=selected.map(i=>chunks[i]).join(' ')+'.';});document.querySelector('#v-reset').onclick=()=>{selected=[];built.textContent='Dein Satz …';body.querySelectorAll('[data-chunk]').forEach(b=>b.disabled=false);feedback.textContent='';};document.querySelector('#v-check').onclick=()=>{if(selected.length<needed){feedback.textContent=d==='hard'?'Dein Satz braucht noch weitere Bausteine.':'Verwende noch alle Bausteine.';return;}const correct=selected.map(i=>chunks[i]).join(' ')+'.'===w.example;feedback.textContent=correct?'Genau: Das ist der Beispielsatz. Lies ihn jetzt laut vor.':`Vergleiche mit dem Beispielsatz: ${w.example} Andere Wortstellungen können je nach Kontext ebenfalls möglich sein.`;};}}
document.querySelector('#v-new').onclick=round;difficulty.onchange=()=>{bag=[];round();};round();}
const beforeVocabRoute=route;
route=function(){const p=location.hash.slice(1).split('/');if(p[0]==='wortschatz'){document.querySelectorAll('audio').forEach(a=>a.pause());vocabBook(p[1],p[2]);window.scrollTo(0,0);}else if(p[0]==='wort'){document.querySelectorAll('audio').forEach(a=>a.pause());wordBook(p[1],decodeURIComponent(p[2]||''));window.scrollTo(0,0);}else beforeVocabRoute();};
route();
